import {useState} from 'react';
import {api} from '../api';
import {Modal} from './UI';
export default function DockerConnection({owner,refresh}:{owner:boolean;refresh:()=>Promise<any>}){
 const [open,setOpen]=useState(false),[saved,setSaved]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const r=await api('/connections/docker');setSaved(r.connection);setOpen(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const submit=async(e:any)=>{e.preventDefault();setBusy(true);setError('');setMessage('');const test=e.nativeEvent.submitter?.value==='test',body=Object.fromEntries(new FormData(e.currentTarget));try{const r=await api('/connections/docker'+(test?'/test':''),{method:test?'POST':'PUT',body:JSON.stringify(body)});setMessage(`Connected to ${r.host.hostname} · Docker ${r.host.version}`);if(!test){setOpen(false);await refresh()}}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!owner)return null;
 return <><button className="btn secondary" disabled={busy} onClick={load}>Configure Docker Connection</button>{!open&&error&&<p className="error">{error}</p>}<Modal open={open} title="Docker Connection" onClose={()=>!busy&&setOpen(false)}><form className="form-grid" onSubmit={submit}><label className="cluster-wide">Docker HTTPS endpoint<input name="url" type="url" required defaultValue={saved?.url||''} placeholder="https://docker-host:2376"/></label><label className="cluster-wide">CA certificate<textarea name="ca" rows={3} placeholder={saved?.hasCa?'Saved — leave blank to keep':'Paste PEM CA certificate (optional for a trusted public CA)'}/></label><label className="cluster-wide">Client certificate<textarea name="cert" rows={3} placeholder={saved?.hasClientCertificate?'Saved — leave blank to keep':'Paste PEM client certificate'} required={!saved?.hasClientCertificate}/></label><label className="cluster-wide">Client private key<textarea name="key" rows={3} placeholder={saved?.hasClientCertificate?'Saved — leave blank to keep':'Paste PEM client private key'} required={!saved?.hasClientCertificate}/></label><p className="muted cluster-wide">Saved credentials are encrypted on the server and never returned to your browser. Saving applies immediately without editing files or restarting. The Docker host must already accept TLS connections authenticated with this client certificate.</p>{error&&<p className="error cluster-wide" role="alert">{error}</p>}{message&&<p className="cluster-wide" role="status">{message}</p>}<div className="header-actions cluster-wide"><button className="btn secondary" value="test" disabled={busy}>Test Connection</button><button className="btn primary" disabled={busy}>{busy?'Connecting...':'Save & Connect'}</button></div></form></Modal></>;
}
