import {useState} from 'react';
import {api} from '../api';
import {useApi} from '../hooks';
import {Card,Badge} from './UI';
export default function IntegrationChecks(){
 const channels=useApi<any>('/notifications',null),[diagnostics,setDiagnostics]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const check=async()=>{setBusy('diagnostics');setError('');try{setDiagnostics(await api('/diagnostics'))}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const test=async(channel:string)=>{setBusy(channel);setError('');setMessage('');try{await api('/notifications/test',{method:'POST',body:JSON.stringify({channel})});setMessage(`${channel} test notification delivered.`);await channels.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}};
 return <><Card><h3>External Notifications</h3>{channels.error&&<p className="error">{channels.error}</p>}<p className="muted">Configure Discord, Telegram or SMTP on the HomeCloud server. Credentials stay on the server. Active alerts and recoveries are delivered with retries.</p>{channels.data?.channels?.map((c:string)=><div className="header-actions" key={c}><Badge tone="green">{c}</Badge><button className="btn secondary small" disabled={!!busy} onClick={()=>test(c)}>Send test notification</button></div>)}{channels.data&&!channels.data.channels.length&&<p>No external channels configured.</p>}{channels.data?.incomplete?.map((text:string)=><p className="error" key={text}>{text}</p>)}<p>Pending deliveries: {channels.data?.pending??'Unknown'}</p>{channels.data?.failures?.map((f:any,i:number)=><p className="error" key={i}>{f.error} Next attempt: {new Date(f.nextAttempt).toLocaleString()}</p>)}</Card><Card><h3>Provider Compatibility Checks</h3><p className="muted">Check configured API reads and permission access. This does not create guests, change shares or verify write compatibility.</p><button className="btn secondary" disabled={!!busy} onClick={check}>{busy==='diagnostics'?'Checking providers…':'Run read-only checks'}</button>{diagnostics&&<><p>{diagnostics.note}</p><div className="table-wrap"><table><thead><tr><th>Provider</th><th>API read</th><th>Result</th></tr></thead><tbody>{diagnostics.checks.map((c:any)=><tr key={c.provider+c.method}><td>{c.provider}</td><td>{c.method}</td><td><Badge tone={c.status==='passed'?'green':'red'}>{c.status}</Badge>{c.message&&<small>{c.message}</small>}</td></tr>)}</tbody></table></div>{!diagnostics.checks.length&&<p>No configured providers.</p>}<pre>{JSON.stringify(diagnostics.versions,null,2)}</pre></>}</Card>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</>;
}
