import {useState,useEffect} from 'react';
import {useApi} from '../hooks';
import {api,setDockerHost} from '../api';
import {Modal,Badge,Card} from './UI';
export default function NodeAgents({owner}:{owner:boolean}){
 const hosts=useApi<any>('/docker/hosts',{hosts:[]}),nodes=useApi<any>(owner?'/node-agents':'/docker/hosts',{nodes:[]});
 const [open,setOpen]=useState(false),[pairing,setPairing]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const pair=async()=>{setBusy(true);setError('');try{setPairing(await api('/node-agents/pairing',{method:'POST',body:'{}'}));setOpen(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(localStorage.getItem('homecloud_docker_host')===null){const first=hosts.data.hosts.find((h:any)=>h.online);if(first){setDockerHost(first.id);window.location.reload()}}},[hosts.data]);
 const choose=(id:string)=>{setDockerHost(id);window.location.reload()};
 return <Card><div className="volume-toolbar"><h3>Automatic Docker Hosts</h3><select aria-label="Docker host" value={localStorage.getItem('homecloud_docker_host')||''} onChange={e=>choose(e.target.value)}><option value="">Configured Engine / Guest Inventory</option>{hosts.data.hosts.map((h:any)=><option key={h.id} value={h.id} disabled={!h.online}>{h.node} › {h.name} ({h.id.split(':')[1]}){h.online?'':' · Unavailable'}</option>)}</select>{owner&&<button className="btn primary" onClick={pair} disabled={busy}>Pair Proxmox Node</button>}</div>{error&&<p className="error">{error}</p>}{owner&&nodes.data.nodes?.map((n:any)=><details key={n.id}><summary>{n.name} <Badge tone={n.online?'green':'gray'}>{n.online?'Agent Online':'Offline'}</Badge> · {n.hosts.filter((h:any)=>h.online).length} Docker hosts</summary>{n.hosts.filter((h:any)=>h.error).map((h:any)=><p className="muted" key={h.id}>{h.name}: {h.error}</p>)}<button className="btn danger small" onClick={async()=>{if(window.confirm(`Revoke node agent ${n.name}?`)){await api('/node-agents/'+n.id,{method:'DELETE'});await nodes.refresh();await hosts.refresh()}}}>Revoke Agent</button></details>)}<small className="muted">Install once on each Proxmox node. Running guests are scanned automatically every minute. Linux guests require curl and a local Docker socket; VMs also require a running QEMU Guest Agent. No per-guest Docker port or certificate setup.</small><Modal open={open} title="Pair Proxmox Node" onClose={()=>setOpen(false)}><p>On the Proxmox node, download and run the installer:</p><pre className="task-log">{`curl --fail --show-error ${window.location.origin}/api/node-agent/install -o /tmp/homecloud-node-agent-install.sh\nsudo bash /tmp/homecloud-node-agent-install.sh`}</pre><p>Enter this HomeCloud HTTPS address when prompted:</p><code>{window.location.origin}</code>{window.location.protocol!=='https:'&&<p className="error">Serve HomeCloud over trusted HTTPS before pairing. Agent credentials must use an authenticated encrypted connection.</p>}<p>Then paste this one-use pairing code (expires in 10 minutes):</p><pre className="task-log">{pairing?.code}</pre><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(pairing?.code||'')}>Copy Pairing Code</button><p className="muted">The node service runs as root to reach guests using pct and qm. It only relays Docker API requests for discovered hosts. Revoke its credentials here at any time. Guest operating systems and Docker daemon settings are left unchanged.</p></Modal></Card>;
}
