import {useState,useEffect} from 'react';
import {useApi} from '../hooks';
import {api,confirmedApi,setDockerHost} from '../api';
import {Modal,Badge,Card} from './UI';
export default function NodeAgents({owner}:{owner:boolean}){
 const hosts=useApi<any>('/docker/hosts',{hosts:[]}),nodes=useApi<any>(owner?'/node-agents':'/docker/hosts',{nodes:[]});
 const [open,setOpen]=useState(false),[pairing,setPairing]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const pair=async()=>{setBusy(true);setError('');setCopied('');try{setPairing(await api('/node-agents/pairing',{method:'POST',body:'{}'}));setOpen(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(localStorage.getItem('homecloud_docker_host')===null){const first=hosts.data.hosts.find((h:any)=>h.online);if(first){setDockerHost(first.id);window.location.reload()}}},[hosts.data]);
 const [copied,setCopied]=useState('');
 const copy=async(value:string,label:string)=>{try{await navigator.clipboard.writeText(value);setCopied(label+' copied.')}catch{setCopied('Select the text and copy it manually.')}};
 const origin=window.location.origin,secure=window.location.protocol==='https:';
 const installCommand=`curl --fail --show-error '${origin}/api/node-agent/install' -o /tmp/homecloud-node-agent-install.sh &&\nbash /tmp/homecloud-node-agent-install.sh`;
 const choose=(id:string)=>{setDockerHost(id);window.location.reload()};
 const [setupBusy,setSetupBusy]=useState(''),[message,setMessage]=useState('');
 const setup=async(n:any,h:any)=>{const id=n.id+':'+h.id;if(!window.confirm(`Install and start Docker in ${h.name}? This installs distribution packages and enables CT nesting. No guest is restarted automatically.`))return;setSetupBusy(id);setError('');setMessage(`Setting up ${h.name}. This may take several minutes.`);try{const r=await confirmedApi('/node-agents/guest/setup',{method:'POST',body:JSON.stringify({host:id})});setMessage(r.result.message);await nodes.refresh();await hosts.refresh()}catch(e:any){setError(e.message);setMessage('')}finally{setSetupBusy('')}};
 const guestRows=<>{message&&<p role="status">{message}</p>}{owner&&nodes.data.nodes?.map((n:any)=><Card key={n.id}><h3>{n.name}: Guest Setup</h3>{(n.version||1)<2?<><p>Update this node agent once to enable guest installation. Run as root on the Proxmox node; your existing pairing is retained.</p><pre className="task-log">{`curl --fail --show-error '${window.location.origin}/api/node-agent/download' -o /tmp/homecloud-node-agent.py &&\npython3 -m py_compile /tmp/homecloud-node-agent.py &&\ninstall -m 700 /tmp/homecloud-node-agent.py /usr/local/sbin/homecloud-node-agent.py &&\nsystemctl restart homecloud-node-agent`}</pre></>:<div className="table-wrap"><table><thead><tr><th>Guest</th><th>Status</th><th>Action</th></tr></thead><tbody>{n.hosts.filter((h:any)=>h.id!=='node').map((h:any)=><tr key={h.id}><td>{h.name}</td><td>{h.online?'Connected':h.setup?'Setup available':'Guest access required'}{h.error&&<small className="docker-image">{h.error}</small>}</td><td>{h.online?<button className="btn secondary small" onClick={()=>choose(n.id+':'+h.id)}>Connect</button>:h.setup?<button className="btn primary small" disabled={!n.online||!!setupBusy} onClick={()=>setup(n,h)}>{setupBusy===n.id+':'+h.id?'Installing…':'Install & Connect'}</button>:h.id.startsWith('qemu/')?<details><summary>VM setup instructions</summary><p>Enable QEMU Guest Agent in Proxmox VM Options. Inside a Debian/Ubuntu VM console, run:</p><pre>{'sudo apt-get update\nsudo apt-get install -y qemu-guest-agent\nsudo systemctl start qemu-guest-agent'}</pre><p>A VM restart may be needed after enabling the guest-agent channel. Other operating systems require their own guest-agent installation.</p></details>:null}</td></tr>)}</tbody></table></div>}</Card>)}</>;
 return <Card><div className="volume-toolbar"><h3>Automatic Docker Hosts</h3><select aria-label="Docker host" value={localStorage.getItem('homecloud_docker_host')||''} onChange={e=>choose(e.target.value)}><option value="">Select a Docker host</option>{hosts.data.hosts.map((h:any)=><option key={h.id} value={h.id} disabled={!h.online}>{h.node} › {h.name} ({h.id.split(':')[1]}){h.online?'':' · Unavailable'}</option>)}</select>{owner&&<button className="btn primary" onClick={pair} disabled={busy}>Pair Proxmox Node</button>}</div>{error&&<p className="error">{error}</p>}{owner&&nodes.data.nodes?.map((n:any)=><details key={n.id}><summary>{n.name} <Badge tone={n.online?'green':'gray'}>{n.online?'Agent Online':'Offline'}</Badge> · {n.hosts.filter((h:any)=>h.online).length} Docker hosts</summary>{n.hosts.filter((h:any)=>h.id==='node'&&h.online).map((h:any)=><p key={h.id}>Node Docker is connected.</p>)}<button className="btn danger small" onClick={async()=>{if(window.confirm(`Revoke node agent ${n.name}?`)){await api('/node-agents/'+n.id,{method:'DELETE'});await nodes.refresh();await hosts.refresh()}}}>Revoke Agent</button></details>)}{guestRows}<small className="muted">Install once on each Proxmox node. Running guests are scanned automatically every minute. Linux guests require curl and a local Docker socket; VMs also require a running QEMU Guest Agent. No per-guest Docker port or certificate setup.</small><Modal open={open} title="Pair Proxmox Node" onClose={()=>setOpen(false)}><div className="node-pairing">
 <p>Install once on each Proxmox node, such as node01 and node02. Open the node's <b>Shell</b> and run as <b>root</b>. Do not run this installer inside a VM or CT. Root does not need sudo.</p>
 {!secure&&<p className="error" role="alert">You opened HomeCloud over HTTP. Open its working HTTPS address and generate a fresh pairing code before continuing. Changing http to https alone does not enable TLS.</p>}
 <details><summary>First time on this node? Trust the HomeCloud certificate</summary><p>If HomeCloud uses a private CA, each node must trust it before downloading or pairing. Skip this step for a certificate already trusted by the node.</p><p>On the <b>Ubuntu VM hosting HomeCloud</b>, print the public CA certificate:</p><pre className="node-command">{'sudo docker compose --project-directory /opt/homecloud-hub -f /opt/homecloud-hub/docker-compose.yml exec -T caddy cat /data/caddy/pki/authorities/local/root.crt'}</pre><p>On the <b>Proxmox node as root</b>, run:</p><pre className="node-command">{'cat > /usr/local/share/ca-certificates/homecloud.crt'}</pre><p>Paste the entire certificate, including BEGIN and END CERTIFICATE. Press Enter, then Ctrl+D. Run:</p><pre className="node-command">{'update-ca-certificates'}</pre><p className="muted">Repeat on every node. An 'unable to get local issuer certificate' error means the node has not trusted the issuing CA. Do not bypass certificate verification.</p></details>
 <h3>1. Download and install on the Proxmox node</h3><pre className="node-command">{secure?installCommand:'Open HomeCloud over HTTPS to show the installation command.'}</pre><button className="btn secondary small" disabled={!secure} onClick={()=>copy(installCommand,'Installer command')}>Copy Installer Command</button>
 <h3>2. Enter the HomeCloud address</h3><p>When asked <b>HomeCloud HTTPS URL</b>, enter this address. It is the HomeCloud server address, not the Proxmox node address.</p><pre className="node-command">{origin}</pre><button className="btn secondary small" disabled={!secure} onClick={()=>copy(origin,'HomeCloud address')}>Copy Address</button>
 <h3>3. Enter the pairing code</h3><p>Paste this code when asked <b>One-time pairing code</b>. It works once for one node; generate a new code for the next node.</p><pre className="node-command node-pair-code">{pairing?.code}</pre><div className="header-actions"><button className="btn secondary small" onClick={()=>copy(pairing?.code||'','Pairing code')}>Copy Pairing Code</button><button className="btn secondary small" disabled={busy} onClick={pair}>Generate New Code</button></div><small className="muted">Expires {pairing?.expiresAt?new Date(pairing.expiresAt).toLocaleString():'in 10 minutes'}.</small>{copied&&<p role="status">{copied}</p>}
 <h3>4. Verify and connect</h3><pre className="node-command">{'systemctl status homecloud-node-agent --no-pager'}</pre><p>Wait about a minute, then select a discovered Docker host above. Use <b>Install &amp; Connect</b> for a supported guest that needs Docker. VMs require a running QEMU Guest Agent before guest setup can execute.</p><p className="muted">The node service runs as root to discover guests and perform authorized Docker actions. Revoke access from the node entry. Guest installation requires separate confirmation.</p>
 </div></Modal></Card>;
}
