import {useState,useEffect} from 'react';
import {useApi} from '../hooks';
import {api,confirmedApi,setDockerHost} from '../api';
import {Modal,Badge,Card} from './UI';
export default function NodeAgents({owner}:{owner:boolean}){
 const hosts=useApi<any>('/docker/hosts',{hosts:[]}),nodes=useApi<any>(owner?'/node-agents':'/docker/hosts',{nodes:[]});
 const [open,setOpen]=useState(false),[pairing,setPairing]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const pair=async()=>{setBusy(true);setError('');try{setPairing(await api('/node-agents/pairing',{method:'POST',body:'{}'}));setOpen(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(localStorage.getItem('homecloud_docker_host')===null){const first=hosts.data.hosts.find((h:any)=>h.online);if(first){setDockerHost(first.id);window.location.reload()}}},[hosts.data]);
 const choose=(id:string)=>{setDockerHost(id);window.location.reload()};
 const [setupBusy,setSetupBusy]=useState(''),[message,setMessage]=useState('');
 const setup=async(n:any,h:any)=>{const id=n.id+':'+h.id;if(!window.confirm(`Install and start Docker in ${h.name}? This installs distribution packages and enables CT nesting. No guest is restarted automatically.`))return;setSetupBusy(id);setError('');setMessage(`Setting up ${h.name}. This may take several minutes.`);try{const r=await confirmedApi('/node-agents/guest/setup',{method:'POST',body:JSON.stringify({host:id})});setMessage(r.result.message);await nodes.refresh();await hosts.refresh()}catch(e:any){setError(e.message);setMessage('')}finally{setSetupBusy('')}};
 const guestRows=<>{message&&<p role="status">{message}</p>}{owner&&nodes.data.nodes?.map((n:any)=><Card key={n.id}><h3>{n.name}: Guest Setup</h3>{(n.version||1)<2?<><p>Update this node agent once to enable guest installation. Run as root on the Proxmox node; your existing pairing is retained.</p><pre className="task-log">{`curl --fail --show-error '${window.location.origin}/api/node-agent/download' -o /tmp/homecloud-node-agent.py &&\npython3 -m py_compile /tmp/homecloud-node-agent.py &&\ninstall -m 700 /tmp/homecloud-node-agent.py /usr/local/sbin/homecloud-node-agent.py &&\nsystemctl restart homecloud-node-agent`}</pre></>:<div className="table-wrap"><table><thead><tr><th>Guest</th><th>Status</th><th>Action</th></tr></thead><tbody>{n.hosts.filter((h:any)=>h.id!=='node').map((h:any)=><tr key={h.id}><td>{h.name}</td><td>{h.online?'Connected':h.setup?'Setup available':'Guest access required'}{h.error&&<small className="docker-image">{h.error}</small>}</td><td>{h.online?<button className="btn secondary small" onClick={()=>choose(n.id+':'+h.id)}>Connect</button>:h.setup?<button className="btn primary small" disabled={!n.online||!!setupBusy} onClick={()=>setup(n,h)}>{setupBusy===n.id+':'+h.id?'Installing…':'Install & Connect'}</button>:h.id.startsWith('qemu/')?<details><summary>VM setup instructions</summary><p>Enable QEMU Guest Agent in Proxmox VM Options. Inside a Debian/Ubuntu VM console, run:</p><pre>{'sudo apt-get update\nsudo apt-get install -y qemu-guest-agent\nsudo systemctl start qemu-guest-agent'}</pre><p>A VM restart may be needed after enabling the guest-agent channel. Other operating systems require their own guest-agent installation.</p></details>:null}</td></tr>)}</tbody></table></div>}</Card>)}</>;
 return <Card><div className="volume-toolbar"><h3>Automatic Docker Hosts</h3><select aria-label="Docker host" value={localStorage.getItem('homecloud_docker_host')||''} onChange={e=>choose(e.target.value)}><option value="">Select a Docker host</option>{hosts.data.hosts.map((h:any)=><option key={h.id} value={h.id} disabled={!h.online}>{h.node} › {h.name} ({h.id.split(':')[1]}){h.online?'':' · Unavailable'}</option>)}</select>{owner&&<button className="btn primary" onClick={pair} disabled={busy}>Pair Proxmox Node</button>}</div>{error&&<p className="error">{error}</p>}{owner&&nodes.data.nodes?.map((n:any)=><details key={n.id}><summary>{n.name} <Badge tone={n.online?'green':'gray'}>{n.online?'Agent Online':'Offline'}</Badge> · {n.hosts.filter((h:any)=>h.online).length} Docker hosts</summary>{n.hosts.filter((h:any)=>h.id==='node'&&h.online).map((h:any)=><p key={h.id}>Node Docker is connected.</p>)}<button className="btn danger small" onClick={async()=>{if(window.confirm(`Revoke node agent ${n.name}?`)){await api('/node-agents/'+n.id,{method:'DELETE'});await nodes.refresh();await hosts.refresh()}}}>Revoke Agent</button></details>)}{guestRows}<small className="muted">Install once on each Proxmox node. Running guests are scanned automatically every minute. Linux guests require curl and a local Docker socket; VMs also require a running QEMU Guest Agent. No per-guest Docker port or certificate setup.</small><Modal open={open} title="Pair Proxmox Node" onClose={()=>setOpen(false)}><p>On the Proxmox node, download and run the installer:</p><pre className="task-log">{`curl --fail --show-error ${window.location.origin}/api/node-agent/install -o /tmp/homecloud-node-agent-install.sh\nbash /tmp/homecloud-node-agent-install.sh`}</pre><p>Enter this HomeCloud HTTPS address when prompted:</p><code>{window.location.origin}</code>{window.location.protocol!=='https:'&&<p className="error">Serve HomeCloud over trusted HTTPS before pairing. Agent credentials must use an authenticated encrypted connection.</p>}<p>Then paste this one-use pairing code (expires in 10 minutes):</p><pre className="task-log">{pairing?.code}</pre><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(pairing?.code||'')}>Copy Pairing Code</button><p className="muted">The node service runs as root to reach guests using pct and qm. It only relays Docker API requests for discovered hosts. Revoke its credentials here at any time. Guest installation runs only after explicit setup confirmation.</p></Modal></Card>;
}
