import {truenas,httpError,required,integer} from './infrastructure.js';
import {pve} from './connectors.js';
export function shareProtocol(v){if(!['smb','nfs'].includes(v))throw httpError('Unsupported share protocol');return v;}
export function shareInput(protocol,input){shareProtocol(protocol);const path=required(input.path,'Share path');if(!path.startsWith('/mnt/')||path.split('/').some(p=>['.','..'].includes(p))||/[\x00-\x1f]/.test(path))throw httpError('Use an existing absolute path under /mnt');const body={path,comment:String(input.comment||'').slice(0,1024)};if(typeof input.enabled==='boolean')body.enabled=input.enabled;
 if(protocol==='smb'){body.name=required(input.name,'Share name');if(/[\\/\x00-\x1f]/.test(body.name)||body.name.length>80)throw httpError('Invalid SMB share name');}
 else {if(typeof input.ro==='boolean')body.ro=input.ro;body.networks=Array.isArray(input.networks)?input.networks:[];if(body.networks.some(n=>typeof n!=='string'||!n.includes('/')||/\s/.test(n)))throw httpError('Use CIDR networks such as 192.168.10.0/24');if(!body.networks.length)throw httpError('Specify at least one allowed NFS network');}
 return body;
}
export async function detectedShare(protocol,id,tn=truenas){shareProtocol(protocol);const number=integer(id,'Share ID');const rows=await tn(`sharing.${protocol}.query`,[[['id','=',number]]]);const share=rows.find(s=>s.id===number);if(!share)throw httpError('Share not found',404);const path=share.path||share.paths?.[0];if(typeof path!=='string'||!path.startsWith('/mnt/')||path.split('/').some(p=>['.','..'].includes(p)))throw httpError('Share has no accessible local path');return {...share,path};}
export async function shareInventory({truenasEnabled=false,proxmox=false,tn=truenas,query=pve}={}){
 const resources=[],errors=[],services=[];
 if(truenasEnabled){for(const protocol of ['smb','nfs'])try{for(const s of await tn(`sharing.${protocol}.query`))resources.push({id:`truenas:${protocol}:${s.id}`,resourceId:s.id,provider:'truenas',protocol:protocol.toUpperCase(),name:s.name||s.comment||s.path||s.paths?.join(', '),path:s.path||s.paths?.[0],paths:s.paths||null,enabled:s.enabled,locked:s.locked,readonly:s.ro??null,description:s.comment||'',networks:s.networks||[],hosts:s.hosts||[],hostsallow:s.hostsallow||[],hostsdeny:s.hostsdeny||[]});}catch(e){errors.push(`TrueNAS ${protocol.toUpperCase()}: ${e.message}`)}try{services.push(...await tn('service.query',[[['service','in',['cifs','nfs']]]]));}catch(e){errors.push(`Share service status: ${e.message}`)}}
 if(proxmox)try{for(const s of await query('/storage'))if(s.type==='nfs')resources.push({id:`proxmox:nfs:${s.storage}`,resourceId:s.storage,provider:'proxmox',protocol:'NFS mount',name:s.storage,path:s.export,server:s.server,nodes:s.nodes||'All configured nodes',enabled:!s.disable,readonly:null,description:'Remote NFS storage registered in Proxmox'});}catch(e){errors.push(`Proxmox NFS mounts: ${e.message}`)}
 return {resources,services,errors,truenasEnabled,proxmoxEnabled:proxmox,sampledAt:new Date().toISOString()};
}
export async function shareWrite(protocol,id,input,tn=truenas){const body=shareInput(protocol,input);const stat=await tn('filesystem.stat',[body.path]);if(stat.type!=='DIRECTORY')throw httpError('The share path must be an existing directory');if(id!=null){await detectedShare(protocol,id,tn);return tn(`sharing.${protocol}.update`,[integer(id,'Share ID'),body]);}return tn(`sharing.${protocol}.create`,[body]);}
