import {pve} from './connectors.js';
import {truenas,encode,integer,required,httpError,pveWrite} from './infrastructure.js';
const numeric=v=>{const n=Number(v?.rawvalue??v?.parsed??v);return v==null||!Number.isFinite(n)?null:n;};
export function snapshotName(v){const name=required(v,'Snapshot name');if(!/^[A-Za-z][A-Za-z0-9_-]{0,79}$/.test(name)||name==='current')throw httpError('Use a snapshot name starting with a letter, followed by letters, numbers, underscores or hyphens');return name;}
export function guestBase(input){if(!['qemu','lxc'].includes(input.kind))throw httpError('Unsupported guest type');return `/nodes/${encode(required(input.node,'Node'))}/${input.kind}/${integer(input.vmid,'Guest ID')}`;}
export async function snapshotInventory({proxmox=false,truenasEnabled=false,query=pve,tn=truenas}={}){
 const resources=[],targets=[],errors=[],schedules=[];
 if(proxmox)try{const guests=(await query('/cluster/resources?type=vm')).filter(g=>['qemu','lxc'].includes(g.type));
 for(let i=0;i<guests.length;i+=5)await Promise.all(guests.slice(i,i+5).map(async g=>{const target={id:`proxmox:${g.node}:${g.type}:${g.vmid}`,provider:'proxmox',node:g.node,kind:g.type,vmid:g.vmid,name:g.name||String(g.vmid)};targets.push(target);try{for(const s of await query(`${guestBase(target)}/snapshot`)){if(s.name==='current')continue;resources.push({...target,id:`${target.id}:${s.name}`,targetId:target.id,name:s.name,resourceId:s.name,dataset:`${g.node} / ${target.name}`,type:g.type==='qemu'?'VM':'CT',created:s.snaptime?new Date(s.snaptime*1000).toISOString():null,size:null,status:s.snapstate||'Reported',description:s.description||null,parent:s.parent||null});}}catch(e){errors.push(`${g.node}/${target.name}: ${e.message}`)}}));
 }catch(e){errors.push(`Proxmox: ${e.message}`)}
 if(truenasEnabled){for(const [label,method,handler] of [['Snapshots','pool.snapshot.query',rows=>{for(const s of rows){const id=s.id||s.name,p=s.properties||{};resources.push({id:`truenas:${id}`,resourceId:id,provider:'truenas',targetId:`truenas:${s.dataset||id.split('@')[0]}`,name:s.snapshot_name||id.split('@')[1],dataset:s.dataset||id.split('@')[0],type:'ZFS',created:numeric(p.creation)?new Date(numeric(p.creation)*1000).toISOString():null,size:numeric(p.used),referenced:numeric(p.referenced),status:'Reported',guid:p.guid?.value||null});}}],['Datasets','pool.dataset.query',rows=>targets.push(...rows.map(d=>({id:`truenas:${d.id||d.name}`,provider:'truenas',name:d.name,resourceId:d.id||d.name})))],['Schedules','pool.snapshottask.query',rows=>schedules.push(...rows)]])try{handler(await tn(method))}catch(e){errors.push(`TrueNAS ${label}: ${e.message}`)}}
 return {resources,targets,schedules,errors,sampledAt:new Date().toISOString()};
}
export async function guestSnapshot(input,operation,query=pve,write=pveWrite){const base=guestBase(input),name=snapshotName(input.name);if(operation==='create')return {task:await write(`${base}/snapshot`,'POST',{snapname:name,description:'Created by HomeCloud Hub'})};const list=await query(`${base}/snapshot`);if(!list.some(s=>s.name===name))throw httpError('Snapshot not found',404);if(operation==='delete')return {task:await query(`${base}/snapshot/${encode(name)}`,{method:'DELETE'})};if(operation==='rollback')return {task:await write(`${base}/snapshot/${encode(name)}/rollback`,'POST',{})};throw httpError('Unsupported snapshot operation');}
