import {useEffect,useState} from 'react';
import {Server,Cpu,MemoryStick,HardDrive,Clock,Search,List,LayoutGrid,Terminal,Power,RefreshCw,Plus} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,Tooltip} from 'recharts';
import {api,confirmedApi} from '../api';
import {useApi} from '../hooks';
import {Card,Badge,Modal} from '../components/UI';
import {DataTable} from '../components/DataTable';
const bytes=(v:any)=>v==null?'Unknown':`${(v/1024**3).toFixed(1)} GiB`;
const pct=(v:any)=>v==null?'Unknown':`${v}%`;
const age=(v:any)=>v==null?'Unknown':`${Math.floor(v/86400)}d ${Math.floor(v%86400/3600)}h`;
const sum=(rows:any[],key:string)=>rows.length&&rows.every(r=>typeof r[key]==='number')?rows.reduce((n,r)=>n+r[key],0):null;
export default function ClusterNodes({data,metrics,tasks,network,hours,role,refresh}:{data:any;metrics:any[];tasks:any[];network:any;hours:string;role?:string;refresh:()=>Promise<void>}){
 const nodes=data?.nodes||[],storage=data?.storage||[],services=data?.nodeServices||[];
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('name'),[membership,setMembership]=useState('all'),[grid,setGrid]=useState(false),[selected,setSelected]=useState(''),[tab,setTab]=useState('Overview'),[joining,setJoining]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[taskResult,setTaskResult]=useState<any>(null);
 useEffect(()=>{if(nodes.length&&!nodes.some((n:any)=>n.name===selected))setSelected(nodes[0].name);},[nodes.map((n:any)=>n.name).join(','),selected]);
 const localName=data?.clusterStatus?.find((r:any)=>r.type==='node'&&r.local)?.name;
 const filtered=nodes.filter((n:any)=>`${n.name} ${n.ip||''}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||n.status===status)&&(membership==='all'||(membership==='endpoint'?n.name===localName:n.name!==localName))).sort((a:any,b:any)=>sort==='name'?a.name.localeCompare(b.name):(b[sort]??-1)-(a[sort]??-1));
 const node=nodes.find((n:any)=>n.name===selected),nodeStorage=storage.filter((s:any)=>s.node===selected),nodeServices=services.filter((s:any)=>s.node===selected),nodeTasks=tasks.filter((t:any)=>t.node===selected);
 const detail=useApi<any>(selected?`/proxmox/node/${encodeURIComponent(selected)}/details`:'/auth/me',null);
 const details=detail.data?.node===selected?detail.data:null;
 const online=nodes.filter((n:any)=>n.status==='online').length,cores=sum(nodes,'cores'),mem=sum(nodes,'memoryBytes'),maxMem=sum(nodes,'memoryTotal'),disk=sum(storage,'used'),maxDisk=sum(storage,'capacity');
 const usedCores=nodes.length&&nodes.every((n:any)=>n.cpu!=null&&n.cores!=null)?nodes.reduce((v:number,n:any)=>v+n.cpu*n.cores/100,0):null;
 const earliest=nodes.length&&nodes.every((n:any)=>n.status==='online'&&n.uptime!=null)?Math.min(...nodes.map((n:any)=>n.uptime)):null;
 const admin=['admin','owner'].includes(role||'');
 const perform=async(path:string)=>{setBusy(true);setError('');setMessage('');try{const response:any=await confirmedApi(path,{method:'POST',body:'{}'});setMessage(response.result?.message||response.message);await refresh();await detail.refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const openConsole=()=>window.open(data.cluster.url,'_blank','noopener,noreferrer');
 const inspect=async(t:any,logs=false)=>{setError('');try{setTaskResult(await api(`/tasks/${encodeURIComponent(t.node)}/${encodeURIComponent(t.upid)}${logs?'/log':''}`));}catch(e:any){setError(e.message);}};
 const traces=(name:string,key:string)=>metrics.filter(m=>new Date(m.time).getTime()>Date.now()-Number(hours)*3600000).map(m=>({time:m.time,value:key==='storage'?usage((m.storage||[]).filter((s:any)=>s.node===name)):m.nodes?.find((n:any)=>n.name===name)?.[key]??null}));
 const servicePills=(name:string)=><div className="node-service-pills">{services.filter((s:any)=>s.node===name).slice(0,3).map((s:any)=><button key={s.id} onClick={()=>{setSelected(name);setTab('Services');}}><i className={s.status==='running'?'online':''}/>{s.name}</button>)}</div>;
 const nodeColumns=[{key:'name',label:'Node',render:(n:any)=><div className="pve-node-name"><Server size={24}/><span><b>{n.name}</b><small>{n.ip||'IP not reported'}</small></span></div>},{key:'status',label:'Status',render:(n:any)=><Badge tone={n.status==='online'?'green':'gray'}>{n.status||'Unknown'}</Badge>},{key:'membership',label:'Membership',render:()=> 'Cluster member'},{key:'cpu',label:'CPU',render:(n:any)=><Measurement value={pct(n.cpu)} points={traces(n.name,'cpu')} color="#3b82f6"/>},{key:'memory',label:'Memory',render:(n:any)=><Measurement value={pct(n.memoryPercent)} points={traces(n.name,'memory')} color="#a855f7"/>},{key:'storage',label:'Storage',render:(n:any)=><Measurement value={pct(usage(storage.filter((s:any)=>s.node===n.name)))} points={traces(n.name,'storage')} color="#f59e0b"/>},{key:'uptime',label:'Uptime',render:(n:any)=>age(n.uptime)},{key:'services',label:'Services',render:(n:any)=>servicePills(n.name)},{key:'actions',label:'Actions',render:(n:any)=><button className="btn secondary" onClick={()=>{setSelected(n.name);setTab('Overview');}}>View</button>}];
 return <section className="cluster-nodes"><div className="nodes-title"><div><h2>Cluster Nodes</h2><p>Monitor performance, services and status across your connected cluster.</p></div><button className="btn primary" disabled={!data?.cluster?.url} onClick={()=>setJoining(true)}><Plus size={14}/> Add Node</button></div>
 <div className="nodes-stats">{[['Total Nodes',nodes.length,`${online}/${nodes.length} Online`,Server],['Total CPU',usedCores==null?'Unknown':`${usedCores.toFixed(1)} / ${cores}`, 'Cores in use',Cpu],['Total Memory',bytes(mem),`of ${bytes(maxMem)}`,MemoryStick],['Total Storage',bytes(disk),`of ${bytes(maxDisk)} · per-node entries`,HardDrive],['Oldest common uptime',age(earliest),'Shortest online node uptime',Clock]].map(([label,value,sub,Icon]:any)=><div className="nodes-stat" key={label}><Icon size={25}/><div><small>{label}</small><strong>{value}</strong><span>{sub}</span></div></div>)}</div>
 <Card><div className="nodes-toolbar"><div><h3>Nodes</h3><small>{filtered.length} of {nodes.length} nodes</small></div><label className="nodes-search"><Search size={14}/><input aria-label="Search nodes" placeholder="Search nodes or IP…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter node status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="online">Online</option><option value="offline">Offline</option></select><select aria-label="Filter node membership" value={membership} onChange={e=>setMembership(e.target.value)}><option value="all">All Members</option>{localName&&<><option value="endpoint">Connected endpoint</option><option value="other">Other nodes</option></>}</select><select aria-label="Sort nodes" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort by Name</option><option value="cpu">Highest CPU</option><option value="memoryPercent">Highest Memory</option><option value="uptime">Longest Uptime</option></select><button className={`btn ${!grid?'primary':'secondary'}`} aria-label="List view" onClick={()=>setGrid(false)}><List size={16}/></button><button className={`btn ${grid?'primary':'secondary'}`} aria-label="Grid view" onClick={()=>setGrid(true)}><LayoutGrid size={16}/></button></div>
 {grid?<div className="nodes-grid">{filtered.map((n:any)=><button className={`node-grid-card ${n.name===selected?'selected':''}`} key={n.name} onClick={()=>{setSelected(n.name);setTab('Overview');}}><Server size={24}/><b>{n.name}</b><small>{n.ip||'IP not reported'} · {n.status}</small><span>CPU {pct(n.cpu)} · Memory {pct(n.memoryPercent)}</span><span>Uptime {age(n.uptime)}</span></button>)}</div>:<DataTable rows={filtered} columns={nodeColumns}/>}{!filtered.length&&<p className="muted">No nodes match these filters.</p>}</Card>
 {node&&<Card className="node-details"><div className="nodes-detail-head"><div className="pve-node-name"><Server size={27}/><span><b>{node.name} <Badge tone={node.status==='online'?'green':'gray'}>{node.status}</Badge></b><small>Cluster member · {node.ip||'IP not reported'}</small></span></div><div>{data?.cluster?.url&&<button className="btn secondary" onClick={openConsole}><Terminal size={14}/> Shell</button>}{admin&&<><button className="btn secondary" disabled={busy||node.status!=='online'} onClick={()=>perform(`/proxmox/node/${encodeURIComponent(selected)}/power/reboot`)}><RefreshCw size={14}/> Reboot</button><button className="btn danger" disabled={busy||node.status!=='online'} onClick={()=>perform(`/proxmox/node/${encodeURIComponent(selected)}/power/shutdown`)}><Power size={14}/> Shutdown</button></>}<select aria-label="More node actions" value="" onChange={e=>setTab(e.target.value)}><option value="" disabled>More Actions</option>{['Services','Storage','Network','Tasks','Logs','Configuration'].map(t=><option key={t}>{t}</option>)}</select></div></div>
 <div className="nodes-detail-tabs">{['Overview','Services','Storage','Network','Tasks','Logs','Configuration'].map(t=><button key={t} className={t===tab?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {error&&<p role="alert" className="login-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {tab==='Overview'?<><div className="node-resource-grid">{[['CPU Usage',pct(node.cpu),`${node.cores??'Unknown'} cores`,'cpu','#3b82f6',Cpu],['Memory Usage',pct(node.memoryPercent),`${bytes(node.memoryBytes)} / ${bytes(node.memoryTotal)}`,'memory','#a855f7',MemoryStick],['Storage Usage',pct(usage(nodeStorage)),`${bytes(sum(nodeStorage,'used'))} / ${bytes(sum(nodeStorage,'capacity'))}`,'storage','#f59e0b',HardDrive]].map(([title,value,sub,key,color,Icon]:any)=><div key={title}><Icon size={24}/><small>{title}</small><strong>{value}</strong><span>{sub}</span><Chart points={traces(selected,key)} color={color} height={45}/></div>)}<div className="node-information"><h3>Node Information</h3>{[['Node Name',node.name],['IP Address',node.ip],['Membership','Cluster member'],['Kernel Version',details?.status?.['current-kernel']?.release||details?.status?.kversion],['PVE Version',details?.version?.version],['Uptime',age(node.uptime)],['Load Average',details?.status?.loadavg?.join(', ')]].map(([key,value])=><p key={key}><span>{key}</span><b>{value??'Unknown'}</b></p>)}<button className="btn secondary" onClick={()=>setTab('Configuration')}>View Configuration</button></div></div><div className="widget-title"><h3>Reported Services</h3><button className="pve-text-button" onClick={()=>setTab('Services')}>View All Services →</button></div><div className="node-services-grid">{nodeServices.slice(0,8).map((s:any)=><button key={s.id} onClick={()=>setTab('Services')}><Server size={16}/><span>{s.name}<small>{s.status}</small></span></button>)}</div>{!nodeServices.length&&<p className="muted">No service readings available for this node.</p>}</>
 :tab==='Services'?<DataTable rows={nodeServices} columns={[{key:'name',label:'Service'},{key:'status',label:'Status'},...(admin?[{key:'action',label:'Actions',render:(s:any)=><div className="row-actions">{['start','stop','restart'].map(operation=><button key={operation} className="btn secondary" disabled={busy} onClick={()=>perform(`/proxmox/node/${encodeURIComponent(selected)}/service/${encodeURIComponent(s.service)}/${operation}`)}>{operation}</button>)}</div>}]:[])]}/>
 :tab==='Storage'?<DataTable rows={nodeStorage} columns={[{key:'name',label:'Storage'},{key:'status',label:'Status'},...['capacity','used','available'].map(key=>({key,label:key,render:(s:any)=>bytes(s[key])})),{key:'usage',label:'Usage',render:(s:any)=>pct(s.usage)}]}/>
 :tab==='Network'?<><DataTable rows={(network?.interfaces||[]).filter((n:any)=>n.provider==='proxmox'&&n.node===selected)} columns={['name','address','type','active'].map(key=>({key,label:key}))}/>{network?.errors?.filter((e:string)=>e.startsWith(selected)).map((e:string)=><p key={e} role="alert">{e}</p>)}</>
 :tab==='Tasks'?<><DataTable rows={nodeTasks} columns={[{key:'upid',label:'Task'},{key:'type',label:'Type'},{key:'status',label:'Status',render:(t:any)=>t.status||(t.endtime?'Unknown':'Running')},{key:'starttime',label:'Started',render:(t:any)=>new Date(t.starttime*1000).toLocaleString()},{key:'actions',label:'Actions',render:(t:any)=><><button className="btn secondary" onClick={()=>inspect(t)}>Status</button><button className="btn secondary" onClick={()=>inspect(t,true)}>Logs</button></>}]}/>{taskResult&&<pre className="live-output">{JSON.stringify(taskResult,null,2)}</pre>}</>
 :tab==='Logs'?<NodeLogs key={selected} node={selected}/>
 :<><p className="muted">Live node configuration. Edit settings in the Proxmox console; the next refresh reads the changes.</p>{detail.error&&<p role="alert">{detail.error}</p>}<pre className="live-output">{JSON.stringify(details?.config||{},null,2)}</pre>{data?.cluster?.url&&<button className="btn secondary" onClick={openConsole}>Edit in Proxmox</button>}</>}
 {!!details?.errors?.length&&<details className="pve-errors"><summary>Some node details are unavailable</summary><ul>{details.errors.map((e:string)=><li key={e}>{e}</li>)}</ul></details>}</Card>}
 <p className="nodes-note">Proxmox cluster nodes are peers; master/worker roles are not inferred. Shared storage may appear on several nodes. Shell and configuration editing use the Proxmox web console.</p>
 <Modal open={joining} title="Add a node to your Proxmox cluster" onClose={()=>setJoining(false)}><p>In Proxmox, open Datacenter → Cluster → Join Information. On the new Proxmox node, open Datacenter → Cluster → Join Cluster and use that information. Proxmox validates the join and credentials.</p><p>When the node joins, HomeCloud detects it on the next refresh. You do not need another HomeCloud connection.</p><div className="modal-actions"><button className="btn secondary" onClick={openConsole}>Open Proxmox</button><button className="btn primary" onClick={async()=>{await refresh();setJoining(false);}}>Refresh Cluster</button></div></Modal></section>;
}
function usage(rows:any[]){const used=sum(rows,'used'),capacity=sum(rows,'capacity');return used!=null&&capacity?Math.round(used/capacity*100):null;}
function Measurement({value,points,color}:{value:string;points:any[];color:string}){return <div className="node-measure"><span>{value}</span><Chart points={points} color={color} height={25}/></div>;}
function Chart({points,color,height}:{points:any[];color:string;height:number}){return points.some(p=>p.value!=null)?<div style={{height,minWidth:65}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={points}><Tooltip labelFormatter={(v:any)=>points[v]?.time?new Date(points[v].time).toLocaleString():''}/><Area dataKey="value" stroke={color} fill={`${color}20`} strokeWidth={1.5} isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div>:<small className="muted">No history yet</small>;}
function NodeLogs({node}:{node:string}){const {data,error,loading,refresh}=useApi<any>(`/proxmox/node/${encodeURIComponent(node)}/logs`,null);return <><button className="btn secondary" onClick={refresh}>Refresh Logs</button>{error?<p role="alert" className="login-error">{error}. Proxmox requires Sys.Syslog permission to read system logs.</p>:<pre className="live-output">{loading&&!data?'Loading…':(data?.logs||[]).map((l:any)=>l.t).join('\n')||'No log lines returned.'}</pre>}</>;}
