import {useEffect,useState} from 'react';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(n:number)=>`${(n/1024**2).toFixed(1)} MiB`;
export default function DockerImages({data,enabled,admin,refresh}:{data:any;enabled:boolean;admin:boolean;refresh:()=>Promise<any>}){
 const images=data?.images||[],containers=data?.containers||[];
 const users=(i:any)=>containers.filter((c:any)=>c.imageId===i.id||i.tags?.includes(c.image));
 const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[id,setId]=useState(''),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[notice,setNotice]=useState('');
 const selected=images.find((i:any)=>i.id===id)||images[0];
 useEffect(()=>{setDetail(null);if(!selected||!data?.host)return;let active=true;api(`/docker/image/${encodeURIComponent(selected.id)}`).then(r=>{if(active)setDetail(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[selected?.id,data]);
 const filtered=images.filter((i:any)=>`${i.name} ${i.id}`.toLowerCase().includes(search.toLowerCase())&&(status==='all'||(status==='used'?users(i).length>0:users(i).length===0)));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages-1),used=images.filter((i:any)=>users(i).length),total=images.reduce((s:number,i:any)=>s+(i.size||0),0);
 const run=async(path:string,method='POST',body:any={})=>{setBusy(true);setError('');setNotice('');try{await confirmedApi(path,{method,body:method==='DELETE'?undefined:JSON.stringify(body)});setNotice('Operation completed.');setModal('');await refresh();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const submit=(e:any)=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));if(modal==='Build Image')return run('/docker/image/build','POST',b);if(modal==='Pull Image')return run('/docker/image/pull','POST',b);if(modal==='Tag Image')return run(`/docker/image/${encodeURIComponent(selected.id)}/tag`,'POST',b);return run('/docker/container','POST',{...b,image:selected.tags?.[0]||selected.id});};
 return <div className="docker-images"><div className="vm-toolbar"><div><h2>Docker Images</h2><small className="muted">Manage images on this Docker Engine.</small></div><button className="btn primary" disabled={!enabled||busy} onClick={()=>setModal('Pull Image')}>Pull Image</button><button className="btn secondary" disabled={!enabled||!admin||busy} onClick={()=>run('/docker/prune/images')}>Clean Up Dangling Images</button><button className="btn primary" disabled={!enabled||busy} onClick={()=>setModal('Build Image')}>Build Image</button></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="image-summary">{[['Total Images',data?images.length:'Unknown',bytes(total)+' listed size'],['In Use',used.length,'Referenced by containers'],['Unused',images.length-used.length,'No container references']].map(([label,value,sub])=><Card key={label}><small>{label}</small><strong>{value}</strong><small className="muted">{sub}</small></Card>)}</div>
 <div className="image-workspace"><Card><div className="vm-toolbar"><input aria-label="Search images" placeholder="Search name, tag or ID..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Image usage" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="all">All Images</option><option value="used">In Use</option><option value="unused">Unused</option></select><button className="btn secondary small" onClick={refresh}>Refresh</button></div><div className="table-wrap"><table><thead><tr>{['Repository / Tag','Image ID','Size','Created','Used By','Actions'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map((i:any)=><tr key={i.id} className={selected?.id===i.id?'image-selected':''}><td><button className="image-name" onClick={()=>{setId(i.id);setError('')}}>{i.name}</button><Badge tone={users(i).length?'green':'gray'}>{users(i).length?'In Use':'Unused'}</Badge></td><td title={i.id}>{i.id.replace('sha256:','').slice(0,12)}</td><td>{bytes(i.size)}</td><td>{new Date(i.created*1000).toLocaleDateString()}</td><td>{users(i).length} containers</td><td><button className="btn secondary small" onClick={()=>setId(i.id)}>View</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">No matching images reported. Connect Docker Engine to load its image inventory.</p>}<div className="vm-pagination"><small>{filtered.length} images</small><button className="btn secondary small" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1}/{pages}</span><button className="btn secondary small" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></Card>
 <div className="docker-side">{selected?<><Card><h3>{selected.name}</h3><Badge tone={users(selected).length?'green':'gray'}>{users(selected).length?'In Use':'Unused'}</Badge><dl className="task-details">{Object.entries({'Image ID':selected.id,Size:bytes(selected.size),Created:new Date(selected.created*1000).toLocaleString(),Architecture:detail?.Architecture,OS:detail?.Os,Digest:selected.digests?.join(', ')}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not reported'}</dd></div>)}</dl><div className="backup-quick"><button className="btn primary" disabled={!enabled||busy} onClick={()=>setModal('Run Container')}>Run Container</button><button className="btn secondary" disabled={!detail} onClick={()=>setModal('Inspect Image')}>Inspect</button><button className="btn secondary" disabled={!enabled||busy||!selected.tags?.length} onClick={()=>run('/docker/image/pull','POST',{image:selected.tags[0]})}>Pull</button><button className="btn secondary" disabled={!enabled||busy} onClick={()=>setModal('Tag Image')}>Tag</button><button className="btn danger" disabled={!enabled||!admin||busy} onClick={()=>run(`/docker/image/${encodeURIComponent(selected.id)}`,'DELETE')}>Delete</button></div></Card><Card><h3>Container Usage</h3>{users(selected).map((c:any)=><p key={c.id}>{c.name} <Badge tone={c.status==='running'?'green':'gray'}>{c.status}</Badge></p>)}{!users(selected).length&&<p className="muted">No container references.</p>}</Card><Card><h3>Image Layers</h3><small className="muted">Layer digests reported by Docker; individual sizes are not reported.</small><div className="image-layers">{detail?.RootFS?.Layers?.map((l:string)=><p title={l} key={l}>{l.slice(0,24)}…</p>)}</div></Card></>:<Card><p>Select an image to view details.</p></Card>}</div></div>
 <Card><h3>Top Images by Size</h3>{[...images].sort((a:any,b:any)=>b.size-a.size).slice(0,5).map((i:any)=><div className="image-size-row" key={i.id}><span>{i.name}</span><progress max={Math.max(1,total)} value={i.size}/><small>{bytes(i.size)}</small></div>)}<small className="muted">Listed image sizes may share layers. Pull history and registry update status are not provided by this inventory.</small></Card>
 <Modal open={!!modal} title={modal} onClose={()=>!busy&&setModal('')}>{error&&<p className="error" role="alert">{error}</p>}{modal==='Inspect Image'?<pre className="task-log">{JSON.stringify(detail,null,2)}</pre>:<form className="form-grid" onSubmit={submit}>{modal==='Build Image'?<><label>Image tag<input name="tag" required placeholder="my-app:latest"/></label><label>Dockerfile<textarea name="dockerfile" required rows={8} placeholder="FROM nginx:alpine"/></label><p className="muted">Build context contains only this Dockerfile. COPY and ADD of local files require an external build context.</p></>:modal==='Pull Image'?<label>Image reference<input name="image" required placeholder="nginx:latest"/></label>:modal==='Tag Image'?<><label>Repository<input name="repository" required placeholder="my-app"/></label><label>Tag<input name="tag" defaultValue="latest" required/></label></>:<><p>Image: {selected?.name}. Creates a stopped container.</p><label>Container name<input name="name" required/></label><label>Port mappings<input name="ports" placeholder="8080:80"/></label></>}<button className="btn primary" disabled={busy}>{busy?'Working...':'Submit'}</button></form>}</Modal>
 </div>;
}