import {useState} from 'react';
import {Layers,Play,Square,Container} from 'lucide-react';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
export default function DockerStacks({data,enabled,refresh}:{data:any;enabled:boolean;refresh:()=>Promise<any>}){
 const rows=data?.containers||[],stacks=data?.stacks||[];
 const members=(s:any)=>rows.filter((c:any)=>c.labels?.['com.docker.compose.project']===s.name);
 const state=(s:any)=>{const cs=members(s),n=cs.filter((c:any)=>c.status==='running').length;return n===cs.length&&n>0?'Running':n===0?'Stopped':'Partial'};
 const services=(s:any)=>[...new Set(members(s).map((c:any)=>c.labels?.['com.docker.compose.service']).filter(Boolean))];
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[id,setId]=useState(''),[modal,setModal]=useState(''),[logs,setLogs]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const filtered=stacks.filter((s:any)=>`${s.name} ${services(s).join(' ')} ${members(s).map((c:any)=>c.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||state(s)===filter));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages-1),selected=stacks.find((s:any)=>s.id===id)||filtered[0],cs=selected?members(selected):[];
 const label=(name:string)=>[...new Set(cs.map((c:any)=>c.labels?.[name]).filter(Boolean))].join(', ')||'Not reported';
 const action=async(a:string)=>{setBusy(true);setError('');setNotice('');try{await confirmedApi(`/docker/stack/${encodeURIComponent(selected.id)}/${a}`,{method:'POST',body:'{}'});setNotice(`Stack ${a} completed.`);await refresh();}catch(e:any){setError(e.message);await refresh();}finally{setBusy(false)}};
 const log=async(c:any)=>{setModal(`Logs: ${c.name}`);setLogs('Loading...');try{setLogs((await api(`/docker/container/${encodeURIComponent(c.id)}/logs`)).logs||'No log output.')}catch(e:any){setLogs(e.message)}};
 const exportInventory=()=>{const text=JSON.stringify({stack:selected.name,services:services(selected),containers:cs.map((c:any)=>({id:c.id,name:c.name,image:c.image,status:c.status,service:c.labels?.['com.docker.compose.service']}))},null,2);const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stack-inventory.json';a.click();URL.revokeObjectURL(url)};
 const inspect=async()=>{setModal('Inspect Stack');setLogs('Loading...');try{const result=await Promise.all(cs.map(async(c:any)=>({name:c.name,id:c.id,status:c.status,service:c.labels?.['com.docker.compose.service'],mounts:c.mounts||[],image:c.image})));setLogs(JSON.stringify(result,null,2))}catch(e:any){setLogs(e.message)}};
 return <div className="compose-manager"><div className="volume-header"><div><small className="muted">Docker › {data?.host?.hostname||'Engine connection'} › Compose Stacks</small><h2>Compose Stacks</h2><p className="muted">Monitor and control applications discovered from Docker Compose labels.</p></div><div className="header-actions"><button className="btn secondary" disabled={busy} onClick={refresh}>Refresh</button><a className="btn secondary" href="https://docs.docker.com/compose/" target="_blank" rel="noreferrer">Compose Documentation</a></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="volume-summary">{[[Layers,'Total Stacks',stacks.length],[Play,'Running',stacks.filter((s:any)=>state(s)==='Running').length],[Square,'Stopped',stacks.filter((s:any)=>state(s)==='Stopped').length],[Container,'Total Containers',stacks.reduce((n:number,s:any)=>n+members(s).length,0)]].map(([Icon,title,value]:any)=><Card key={title}><Icon size={26}/><div><small>{title}</small><strong>{data?.host?value:'Unknown'}</strong></div></Card>)}</div>
 <div className="compose-workspace"><Card><div className="volume-toolbar"><h3>Stacks</h3><input aria-label="Search stacks" placeholder="Search stack or service..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Stack status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="all">All Status</option>{['Running','Stopped','Partial'].map(s=><option key={s}>{s}</option>)}</select></div><div className="table-wrap"><table><thead><tr>{['Name','Services','Containers','Status','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map((s:any)=><tr key={s.id} className={selected?.id===s.id?'image-selected':''}><td><button className="image-name" onClick={()=>setId(s.id)}>{s.name}</button></td><td>{services(s).length||'Not reported'}</td><td>{members(s).filter((c:any)=>c.status==='running').length}/{members(s).length} running</td><td><Badge tone={state(s)==='Running'?'green':state(s)==='Partial'?'yellow':'gray'}>{state(s)}</Badge></td><td><button className="btn secondary small" onClick={()=>setId(s.id)}>View</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">No matching Compose projects reported. Connect Docker Engine to discover its Compose labels.</p>}<div className="vm-pagination"><small>{filtered.length} stacks</small><button className="btn secondary small" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1}/{pages}</span><button className="btn secondary small" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></Card>
 <Card>{selected?<><h3>Stack Details</h3><h3>{selected.name} <Badge tone={state(selected)==='Running'?'green':'gray'}>{state(selected)}</Badge></h3><dl className="task-details">{Object.entries({Location:label('com.docker.compose.project.working_dir'),'Compose Files':label('com.docker.compose.project.config_files'),Services:services(selected).join(', ')||'Not reported',Containers:cs.length,Volumes:[...new Set(cs.flatMap((c:any)=>(c.mounts||[]).filter((m:any)=>m.Type==='volume').map((m:any)=>m.Name)))].join(', ')||'None reported','Compose Version':label('com.docker.compose.version')}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="header-actions">{['start','stop','restart'].map(a=><button className="btn secondary" key={a} disabled={!enabled||busy||(a==='start'&&state(selected)==='Running')||(a==='stop'&&state(selected)==='Stopped')} onClick={()=>action(a)}>{a}</button>)}</div><div className="header-actions compose-quick"><button className="btn secondary small" onClick={inspect}>Inspect Services</button><button className="btn secondary small" onClick={exportInventory}>Export Inventory</button></div></>:<p>Select a stack to see details.</p>}</Card></div>
 <div className="compose-bottom"><Card><h3>Services {selected?`· ${selected.name}`:''}</h3><div className="table-wrap"><table><thead><tr><th>Service</th><th>Container</th><th>Image</th><th>Status</th><th>Logs</th></tr></thead><tbody>{cs.map((c:any)=><tr key={c.id}><td>{c.labels?.['com.docker.compose.service']||'Not reported'}</td><td>{c.name}</td><td>{c.image}</td><td><Badge tone={c.status==='running'?'green':'gray'}>{c.status}</Badge></td><td><button className="btn secondary small" disabled={!data?.host} onClick={()=>log(c)}>View Logs</button></td></tr>)}</tbody></table></div></Card><Card><h3>Compose File and Deployment</h3><p className="muted">Docker Engine reports project labels and containers. It does not expose the original Compose file or its environment variables.</p><p className="muted">Import, validation, deployment, editing, updates and duplication require Docker Compose access on the host. Inventory export contains service metadata, not a deployable Compose file.</p></Card></div>
 <Modal open={!!modal} title={modal} onClose={()=>setModal('')}><pre className="task-log">{logs}</pre></Modal></div>;
}