import {useCallback,useEffect,useRef,useState} from 'react';
import {Activity,Calendar,Info,TriangleAlert,OctagonAlert} from 'lucide-react';
import {api} from '../api';
import {Card,Badge} from '../components/UI';
const severity=(e:any)=>e.Action==='oom'||(e.Action==='die'&&e.Actor?.Attributes?.exitCode&&e.Actor.Attributes.exitCode!=='0')?'Error':e.Action==='health_status: unhealthy'?'Warning':'Info';
const time=(e:any)=>Number(e.time||e.timeNano/1e9||0);
export default function DockerEvents({host}:{host:any}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[hours,setHours]=useState('24'),[live,setLive]=useState(true),[search,setSearch]=useState(''),[type,setType]=useState('all'),[source,setSource]=useState('all'),[object,setObject]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null),[timeline,setTimeline]=useState(false),[cutoff,setCutoff]=useState(0),[copy,setCopy]=useState('');
 const pending=useRef(false),requestId=useRef(0);
 const refresh=useCallback(async()=>{if(pending.current||!host)return;pending.current=true;const ticket=++requestId.current;setLoading(true);try{const result=await api(`/docker/events?hours=${hours}`);if(ticket===requestId.current){setData(result);setError('')}}catch(e:any){if(ticket===requestId.current)setError(e.message)}finally{if(ticket===requestId.current){pending.current=false;setLoading(false)}}},[hours,host?.hostname]);
 useEffect(()=>{pending.current=false;setData(null);setCutoff(0);setPage(0);setSelected(null);refresh();},[refresh]);
 useEffect(()=>{if(!live)return;const timer=window.setInterval(refresh,10000);return()=>window.clearInterval(timer)},[live,refresh]);
 const all=(Array.isArray(data?.events)?data.events:[]).filter((e:any)=>time(e)>cutoff).sort((a:any,b:any)=>time(b)-time(a));
 const name=(e:any)=>e.Actor?.Attributes?.name||e.Actor?.ID||e.id||'Not reported';
 const filtered=all.filter((e:any)=>(type==='all'||severity(e)===type)&&(source==='all'||e.Type===source)&&(object==='all'||name(e)===object)&&`${name(e)} ${e.Type} ${e.Action||e.status} ${JSON.stringify(e.Actor?.Attributes||{})}`.toLowerCase().includes(search.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/15)),current=Math.min(page,pages-1),detail=selected||filtered[0];
 const reset=()=>{setSearch('');setType('all');setSource('all');setObject('all');setPage(0);setCutoff(0)};
 const exportEvents=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({since:data.since,until:data.until,events:filtered},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='docker-events.json';a.click();URL.revokeObjectURL(url)};
 const counts=['Info','Warning','Error'].map(t=>all.filter((e:any)=>severity(e)===t).length),top=Object.entries(all.reduce((acc:any,e:any)=>{acc[name(e)]=(acc[name(e)]||0)+1;return acc},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,5);
 const bins=Array.from({length:12},(_,i)=>{const start=(data?.since||0)+i*((data?.until||0)-(data?.since||0))/12,end=start+((data?.until||0)-(data?.since||0))/12;return {start,count:all.filter((e:any)=>time(e)>=start&&time(e)<end).length}}),max=Math.max(1,...bins.map(b=>b.count));
 return <div className="docker-events"><div className="volume-header"><div><small className="muted">Docker › {host?.hostname||'Engine connection'} › Events</small><h2>Events</h2><p className="muted">Docker Engine events retained by the connected daemon.</p></div><div className="header-actions"><button className="btn secondary" disabled={!data} onClick={exportEvents}>Export Events</button><button className="btn secondary" disabled={!all.length} onClick={()=>{setCutoff(data.until);setSelected(null)}}>Clear View</button><label className="event-live"><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/> Auto-refresh (10s)</label></div></div>
 {error&&<p role="alert" className="error">{error}</p>}{!host&&<p className="muted">Connect Docker Engine to read events.</p>}
 <div className="event-summary">{[[Calendar,'Total Events',all.length],[Info,'Info',counts[0]],[TriangleAlert,'Warnings',counts[1]],[OctagonAlert,'Errors',counts[2]],[Activity,'Last Event',all[0]?new Date(time(all[0])*1000).toLocaleTimeString():'None reported']].map(([Icon,title,value]:any)=><Card key={title}><Icon size={24}/><div><small>{title}</small><strong>{data?value:'Unknown'}</strong></div></Card>)}</div>
 <div className="compose-workspace"><Card><div className="header-actions"><button className={`btn ${!timeline?'primary':'secondary'} small`} onClick={()=>setTimeline(false)}>Event Log</button><button className={`btn ${timeline?'primary':'secondary'} small`} onClick={()=>setTimeline(true)}>Event Timeline</button></div><div className="volume-toolbar event-toolbar"><input aria-label="Search events" placeholder="Search event or object..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><button className="btn secondary small" disabled={loading||!host} onClick={refresh}>{loading?'Refreshing...':'Refresh'}</button></div><div className="table-wrap">{timeline?<ol className="event-timeline">{filtered.slice(current*15,current*15+15).map((e:any,i:number)=><li key={i}><button className="image-name" onClick={()=>setSelected(e)}>{new Date(time(e)*1000).toLocaleString()} · {e.Action||e.status} · {name(e)}</button><Badge tone={severity(e)==='Error'?'red':severity(e)==='Warning'?'yellow':'green'}>{severity(e)}</Badge></li>)}</ol>:<table><thead><tr>{['Time','Type','Source','Object','Action','Details'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice(current*15,current*15+15).map((e:any,i:number)=><tr key={`${e.timeNano}-${e.Actor?.ID}-${i}`}><td>{new Date(time(e)*1000).toLocaleString()}</td><td><Badge tone={severity(e)==='Error'?'red':severity(e)==='Warning'?'yellow':'green'}>{severity(e)}</Badge></td><td>{e.Type||'Not reported'}</td><td><span className="event-object" title={name(e)}>{name(e)}</span></td><td>{e.Action||e.status}</td><td><button className="btn secondary small" onClick={()=>{setSelected(e);setCopy('')}}>View</button></td></tr>)}</tbody></table>}</div>{!filtered.length&&<p className="muted">{loading?'Loading events...':'No matching events returned for this period.'}</p>}<div className="vm-pagination"><small>{filtered.length} events</small><button className="btn secondary small" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1}/{pages}</span><button className="btn secondary small" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></Card>
 <div className="docker-side"><Card><h3>Event Details</h3>{detail?<><h3>{detail.Action||detail.status}</h3><Badge tone={severity(detail)==='Error'?'red':severity(detail)==='Warning'?'yellow':'green'}>{severity(detail)}</Badge><dl className="task-details">{Object.entries({Time:new Date(time(detail)*1000).toLocaleString(),Source:detail.Type,Object:name(detail),ID:detail.Actor?.ID||detail.id,Attributes:JSON.stringify(detail.Actor?.Attributes||{})}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not reported'}</dd></div>)}</dl><pre className="event-json">{JSON.stringify(detail,null,2)}</pre><button className="btn secondary small" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(detail,null,2));setCopy('Copied')}catch{setCopy('Copy unavailable; select the event JSON manually')}}}>Copy Event</button><small role="status">{copy}</small></>:<p className="muted">Select an event to inspect its reported attributes.</p>}</Card><Card><div className="volume-toolbar"><h3>Event Filters</h3><button className="btn secondary small" onClick={reset}>Reset</button></div><div className="event-filters"><label>Time Range<select value={hours} onChange={e=>setHours(e.target.value)}>{['1','24','168'].map(h=><option key={h} value={h}>Last {h} hours</option>)}</select></label><label>Type<select value={type} onChange={e=>{setType(e.target.value);setPage(0)}}><option value="all">All Types</option>{['Info','Warning','Error'].map(t=><option key={t}>{t}</option>)}</select></label><label>Source<select value={source} onChange={e=>{setSource(e.target.value);setPage(0)}}><option value="all">All Sources</option>{Array.from(new Set(all.map((e:any)=>e.Type))).filter(Boolean).map((s:any)=><option key={s}>{s}</option>)}</select></label><label>Object<select value={object} onChange={e=>{setObject(e.target.value);setPage(0)}}><option value="all">All Objects</option>{Array.from(new Set(all.map(name))).map((n:any)=><option key={n}>{n}</option>)}</select></label></div></Card></div></div>
 <div className="volume-bottom"><Card><h3>Events by Type</h3>{['Info','Warning','Error'].map((t,i)=><p key={t}>{t}: <b>{counts[i]}</b></p>)}<small className="muted">Severity is derived from actions: OOM and non-zero exits are errors; unhealthy health checks are warnings.</small></Card><Card><h3>Events Timeline</h3><div className="event-bars">{bins.map((b,i)=><div key={i} title={`${new Date(b.start*1000).toLocaleString()}: ${b.count}`}><span style={{height:`${b.count/max*100}%`}}/></div>)}</div><small className="muted">Counts across the selected period.</small></Card><Card><h3>Top Objects by Events</h3>{top.map(([n,c]:any)=><p className="event-ranking" key={n}><span>{n}</span><b>{c}</b></p>)}</Card></div><p className="muted small">Docker may return only its most recent retained events. Clear View hides events locally; Reset restores them. It does not delete daemon logs.</p></div>;
}