import DockerImages from './DockerImages';
import {useState} from 'react';
import {Container,Layers,Cpu,MemoryStick,Database,RefreshCw,Plus,Play,Square,RotateCcw,FileText} from 'lucide-react';
import {useApi} from '../hooks';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(v:any)=>v==null?'Unknown':`${(v/(v>=1024**3?1024**3:1024**2)).toFixed(1)} ${v>=1024**3?'GiB':'MiB'}`;
export default function Docker(){
 const live=useApi<any>('/docker',null),session=useApi<any>('/auth/me',null),events=useApi<any>('/docker/events',null),data=live.data,rows=data?.containers||[],host=data?.host;
 const role=session.data?.user?.role,admin=['owner','admin'].includes(role||''),operator=admin||role==='operator',enabled=operator&&!!host&&!data?.readOnly;
 const [view,setView]=useState('Containers'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null),[logs,setLogs]=useState(''),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const execute=async(path:string,method='POST',body:any={})=>{setBusy(true);setError('');try{const r=await confirmedApi(path,{method,body:method==='GET'?undefined:JSON.stringify(body)});setMessage('Docker operation completed.');await live.refresh();return r;}catch(e:any){setError(e.message);return null;}finally{setBusy(false);}};
 const action=(r:any,a:string)=>execute(`/actions/docker/container/${encodeURIComponent(r.id)}/${a}`);
 const inspect=async(r:any)=>{setSelected(r);setLogs('Loading logs...');setModal('Logs');try{setLogs((await api(`/docker/container/${encodeURIComponent(r.id)}/logs`)).logs||'No log output.');}catch(e:any){setLogs(e.message);}};
 const changeView=(v:string)=>{setView(v);setPage(0);setSearch('');setStatus('all');};
 const filtered=rows.filter((r:any)=>(status==='all'||r.status===status)&&`${r.name} ${r.image}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/10)),actual=Math.min(page,pages-1),shown=filtered.slice(actual*10,actual*10+10);
 const running=rows.filter((r:any)=>r.status==='running'),cpu=running.length&&running.every((r:any)=>typeof r.cpu==='number')?running.reduce((s:number,r:any)=>s+r.cpu,0):running.length?null:host?0:null,memory=running.length&&running.every((r:any)=>typeof r.memory==='number')?running.reduce((s:number,r:any)=>s+r.memory,0):running.length?null:host?0:null;
 const resourceKey=({Images:'images',Volumes:'volumes',Networks:'networks','Compose Stacks':'stacks'} as any)[view],resourceRows=(data?.[resourceKey]||[]).filter((r:any)=>Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase()));
 const submit=async(e:any)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const path=modal==='Prune'?`/docker/prune/${body.kind}`:modal==='Create Container'?'/docker/container':modal==='Create Volume'?'/docker/volume':'/docker/network';if(await execute(path,'POST',body))setModal('');};
 return <section className={`docker-manager ${view==='Images'?'docker-images-view':' '}`}><div className="page-header"><div><small className="muted">Docker › {host?.hostname||'Engine connection'}</small><h1>Docker Host: {host?.hostname||'Not connected'} <Badge tone={host?'green':'gray'}>{host?'Connected':'Unavailable'}</Badge></h1><p className="muted">Manage live containers, images, volumes and networks.</p></div><div className="header-actions"><button className="btn secondary" onClick={live.refresh} disabled={live.loading}><RefreshCw size={15}/> Refresh</button><button className="btn primary" disabled={!enabled} onClick={()=>{setError('');setModal('Create Container');}}><Plus size={15}/> Create Container</button></div></div>
 {(live.error||error)&&<p className="error" role="alert">{live.error||error}</p>}{message&&<p role="status">{message}</p>}{!host&&<Card><h3>Connect Docker Engine</h3><p className="muted">Container inventory may be discovered from guests. Management requires a configured Docker Engine connection.</p><p className="muted">On your Ubuntu server, run <code>sudo homecloud config</code>, configure the Docker connector, then run <code>sudo homecloud restart</code>.</p></Card>}
 <div className="docker-stats">{[[Container,data?rows.length:'Unknown','Containers',`${running.length} running`],[Layers,data?.images?.length??'Unknown','Images','Reported image inventory'],[Cpu,cpu==null?'Unknown':`${cpu.toFixed(1)}%`,'Container CPU',`${host?.cores??'Unknown'} host cores`],[MemoryStick,bytes(memory),'Container Memory',`${bytes(host?.memoryTotal)} host capacity`],[Database,data?.volumes?.length??'Unknown','Volumes',`${data?.networks?.length??'Unknown'} networks`]].map(([Icon,value,label,sub]:any)=><Card className="vm-stat" key={label}><span className="vm-stat-icon"><Icon size={24}/></span><div><small>{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div></Card>)}</div>
 <div className="tabs" role="tablist" aria-label="Docker resources">{['Containers','Images','Volumes','Networks','Compose Stacks','Events','Settings'].map(v=><button role="tab" aria-selected={view===v} className={view===v?'active':''} key={v} onClick={()=>changeView(v)}>{v}</button>)}</div>
 {view==="Images"?<DockerImages data={data} enabled={enabled} admin={admin} refresh={live.refresh}/>:<><div className="docker-workspace"><Card className="vm-list-card"><div className="vm-toolbar"><h3>{view}</h3>{resourceKey||view==='Containers'?<input aria-label="Search Docker resources" placeholder="Search resources..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/>:null}{view==='Containers'&&<select aria-label="Container status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">All Status</option>{Array.from(new Set(rows.map((r:any)=>r.status))).map((s:any)=><option key={s}>{s}</option>)}</select>}</div>
 {view==='Containers'?<><div className="table-wrap"><table className="docker-table"><thead><tr>{['Name / Image','Status','Ports','CPU','Memory','Actions'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{shown.map((r:any)=><tr key={r.id}><td><b>{r.name}</b><small className="docker-image" title={r.image}>{r.image||'Unknown'}</small></td><td><Badge tone={r.status==='running'?'green':'gray'}>{r.status}</Badge></td><td>{r.ports||'Not reported'}</td><td>{r.cpu==null?'Unknown':`${r.cpu}%`}</td><td>{bytes(r.memory)}</td><td><div className="header-actions"><button className="btn secondary small" disabled={!enabled||busy||r.status==='running'} onClick={()=>action(r,'start')} title="Start"><Play size={13}/></button><button className="btn secondary small" disabled={!enabled||busy||r.status!=='running'} onClick={()=>action(r,'stop')} title="Stop"><Square size={13}/></button><button className="btn secondary small" disabled={!enabled||busy||r.status!=='running'} onClick={()=>action(r,'restart')} title="Restart"><RotateCcw size={13}/></button><button className="btn secondary small" disabled={!enabled} onClick={()=>inspect(r)} title="Logs"><FileText size={13}/></button><button className="btn secondary small" disabled={!enabled} onClick={()=>{setSelected(r);setModal('Container Actions');}}>More</button></div>{r.statsError&&<small className="error">{r.statsError}</small>}</td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Loading containers...':'No matching containers reported.'}</p>}<div className="vm-pagination"><small>Showing {filtered.length?actual*10+1:0}–{Math.min(actual*10+10,filtered.length)} of {filtered.length}</small><button className="btn secondary small" disabled={!actual} onClick={()=>setPage(actual-1)}>Previous</button><span>{actual+1}/{pages}</span><button className="btn secondary small" disabled={actual>=pages-1} onClick={()=>setPage(actual+1)}>Next</button></div></>
 :resourceKey?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Details</th><th>Actions</th></tr></thead><tbody>{resourceRows.map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{view==='Images'?`${bytes(r.size)} · ${r.created?new Date(r.created*1000).toLocaleString():'Unknown'}`:view==='Volumes'?`${r.driver} · ${r.mountpoint}`:view==='Networks'?`${r.driver} · ${r.subnets||'No subnet reported'}`:`${r.containers} containers`}</td><td>{view==='Compose Stacks'?['start','stop','restart'].map(a=><button className="btn secondary small" disabled={!enabled||busy} key={a} onClick={()=>execute(`/docker/stack/${encodeURIComponent(r.id)}/${a}`)}>{a}</button>):['Volumes','Networks'].includes(view)&&<button className="btn secondary small" disabled={!admin||!host||busy} onClick={()=>execute(`/docker/${view==='Volumes'?'volume':'network'}/${encodeURIComponent(r.id)}`,'DELETE')}>Remove</button>}</td></tr>)}</tbody></table>{!resourceRows.length&&<p className="muted">No resources reported.</p>}</div>
 :view==='Events'?<><button className="btn secondary" disabled={!host} onClick={events.refresh}>Refresh Events</button>{events.error&&<p className="error">{events.error}</p>}<pre className="task-log">{JSON.stringify(events.data?.events||[],null,2)}</pre><small className="muted">Docker events from the last hour.</small></>:<><h3>Docker Connection</h3><p className="muted">This installation manages one configured Engine API. Configure its endpoint and TLS credentials on the server with <code>sudo homecloud config</code>, then restart with <code>sudo homecloud restart</code>.</p><p className="muted">Compose controls operate on discovered project containers. Compose deployment, shell commands and image builds are not available through this page.</p></>}
 </Card><div className="docker-side"><Card><h3>Docker Host Info</h3><dl className="task-details">{Object.entries({Hostname:host?.hostname,OS:host?.os,'Docker Engine':host?.version,'Storage Driver':host?.storageDriver,Kernel:host?.kernel,'Docker Root Directory':host?.rootDirectory,Cores:host?.cores,'Memory Capacity':bytes(host?.memoryTotal)}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Unknown'}</dd></div>)}</dl></Card><Card><h3>Resource Usage</h3><p>Measured container CPU: <b>{cpu==null?'Unknown':`${cpu.toFixed(1)}%`}</b></p><p>Measured container memory: <b>{bytes(memory)}</b></p><small className="muted">Container totals exclude host processes. Filesystem capacity, host uptime and image update availability are not inferred.</small></Card><Card><h3>Quick Actions</h3><div className="backup-quick">{['Create Container','Create Volume','Create Network','Prune'].map(m=><button className="btn secondary" key={m} disabled={!enabled||(m==='Prune'&&!admin)} onClick={()=>{setError('');setModal(m);}}>{m}</button>)}</div></Card></div></div>
 <Card className="docker-stacks"><div className="vm-toolbar"><h3>Compose Stacks</h3><button className="btn secondary small" onClick={()=>changeView('Compose Stacks')}>View All Stacks</button></div><div className="docker-stack-grid">{data?.stacks?.map((s:any)=>{const members=rows.filter((r:any)=>r.labels?.['com.docker.compose.project']===s.name);return <div key={s.id}><h3>{s.name}</h3><p className="muted">{members.length} containers · {members.filter((r:any)=>r.status==='running').length} running</p><div className="header-actions">{['start','stop','restart'].map(a=><button className="btn secondary small" key={a} disabled={!enabled||busy} onClick={()=>execute(`/docker/stack/${encodeURIComponent(s.id)}/${a}`)}>{a}</button>)}</div></div>})}</div>{!data?.stacks?.length&&<p className="muted">No Compose project labels reported.</p>}</Card>
 </>}<Modal open={!!modal} title={modal==='Logs'?`Logs: ${selected?.name}`:modal} onClose={()=>!busy&&setModal('')}>{error&&<p role="alert" className="error">{error}</p>}{modal==='Logs'?<><pre className="task-log">{logs}</pre><button className="btn secondary" onClick={()=>inspect(selected)}>Refresh Logs</button></>:modal==='Container Actions'?<><p>{selected?.name}</p><div className="header-actions">{['pause','unpause','remove'].map(a=><button className="btn secondary" key={a} disabled={busy} onClick={()=>action(selected,a)}>{a}</button>)}</div></>:<form onSubmit={submit} className="form-grid">{modal==='Prune'?<label>Unused resource type<select name="kind">{['containers','images','volumes','networks'].map(k=><option key={k}>{k}</option>)}</select></label>:<label>Name<input name="name" required/></label>}{modal==='Create Container'&&<><label>Image<input name="image" required placeholder="nginx:alpine"/></label><label>Port mappings (optional)<input name="ports" placeholder="8080:80"/></label></>}<button className="btn primary" disabled={busy}>{busy?'Working...':'Submit'}</button></form>}</Modal></section>;
}
