import {useEffect,useState} from 'react';
import {Network,Activity,Unplug,Layers} from 'lucide-react';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
export default function DockerNetworks({data,enabled,admin,refresh}:{data:any;enabled:boolean;admin:boolean;refresh:()=>Promise<any>}){
 const networks=data?.networks||[],[search,setSearch]=useState(''),[driver,setDriver]=useState('all'),[page,setPage]=useState(0),[id,setId]=useState(''),[detail,setDetail]=useState<any>(null),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const members=(n:any)=>(data?.containers||[]).filter((c:any)=>c.networks?.[n.name]);
 const filtered=networks.filter((n:any)=>`${n.name} ${n.driver} ${n.subnets}`.toLowerCase().includes(search.toLowerCase())&&(driver==='all'||n.driver===driver)),pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages-1),selected=networks.find((n:any)=>n.id===id)||filtered[0];
 useEffect(()=>{setDetail(null);if(!selected||!data?.host)return;let active=true;api(`/docker/network/${encodeURIComponent(selected.id)}`).then(r=>{if(active)setDetail(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[selected?.id,data]);
 const run=async(path:string,method='POST',body:any={})=>{setBusy(true);setError('');setNotice('');try{const r=await confirmedApi(path,{method,body:method==='DELETE'?undefined:JSON.stringify(body)});setNotice(r.result?.NetworksDeleted?`Removed ${r.result.NetworksDeleted.length} unused networks.`:'Operation completed.');setModal('');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const count=(n:any)=>members(n).length;
 const protectedNetwork=(n:any)=>['bridge','host','none'].includes(n.name);
 return <div className="docker-networks"><div className="volume-header"><div><small className="muted">Docker › {data?.host?.hostname||'Engine connection'} › Networks</small><h2>Docker Networks</h2><p className="muted">Manage network drivers, connected containers and addressing.</p></div><div className="header-actions"><button className="btn secondary" disabled={!enabled||!admin||busy} onClick={()=>run('/docker/prune/networks')}>Prune Networks</button><a className="btn secondary" href="https://docs.docker.com/engine/network/" target="_blank" rel="noreferrer">Network Docs</a><button className="btn primary" disabled={!enabled||busy} onClick={()=>setModal('Create Network')}>Create Network</button></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="volume-summary">{[[Network,'Total Networks',networks.length,'Engine inventory'],[Activity,'Attached Networks',networks.filter((n:any)=>count(n)>0).length,'With container attachments'],[Unplug,'Unattached Networks',networks.filter((n:any)=>!count(n)).length,'Includes built-in networks'],[Layers,'Network Drivers',new Set(networks.map((n:any)=>n.driver)).size,'Reported drivers']].map(([Icon,label,value,sub]:any)=><Card key={label}><Icon size={25}/><div><small>{label}</small><strong>{data?.host?value:'Unknown'}</strong><small className="muted">{sub}</small></div></Card>)}</div>
 <div className="volume-workspace"><Card><div className="volume-toolbar"><h3>Networks</h3><input aria-label="Search networks" placeholder="Search name, driver, subnet..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Network driver" value={driver} onChange={e=>{setDriver(e.target.value);setPage(0)}}><option value="all">All Drivers</option>{Array.from(new Set(networks.map((n:any)=>n.driver))).map((d:any)=><option key={d}>{d}</option>)}</select><button className="btn secondary small" onClick={refresh}>Refresh</button></div><div className="table-wrap"><table><thead><tr>{['Name','Driver','Scope','Subnet','Gateway','Containers','Status','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map((n:any)=><tr key={n.id} className={selected?.id===n.id?'image-selected':''}><td><button className="image-name" onClick={()=>setId(n.id)}>{n.name}</button></td><td>{n.driver}</td><td>{n.scope}</td><td>{n.subnets||'—'}</td><td>{n.gateways||'—'}</td><td>{count(n)}</td><td><Badge tone={count(n)?'green':'gray'}>{count(n)?'Attached':'Unattached'}</Badge></td><td><button className="btn secondary small" onClick={()=>setId(n.id)}>View</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">No matching networks reported.</p>}<div className="vm-pagination"><small>{filtered.length} networks</small><button className="btn secondary small" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1}/{pages}</span><button className="btn secondary small" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></Card>
 <div className="docker-side">{selected?<><Card><h3>Network Details</h3><h3>{selected.name}</h3><Badge tone={count(selected)?'green':'gray'}>{count(selected)?'Attached':'Unattached'}</Badge><dl className="task-details">{Object.entries({Driver:selected.driver,Scope:selected.scope,Subnet:selected.subnets,Gateway:selected.gateways,'IP Range':detail?.IPAM?.Config?.map((c:any)=>c.IPRange).filter(Boolean).join(', '),Created:detail?.Created||selected.created,Internal:selected.internal?'Yes':'No','IPv6':detail?.EnableIPv6?'Enabled':'Disabled',Labels:JSON.stringify(detail?.Labels||selected.labels||{})}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not reported'}</dd></div>)}</dl><div className="header-actions"><button className="btn secondary" disabled={!detail} onClick={()=>setModal('Inspect Network')}>Inspect</button><button className="btn secondary" onClick={()=>setModal('Connected Containers')}>View Containers</button><button className="btn danger" disabled={!enabled||!admin||busy||count(selected)>0||protectedNetwork(selected)} onClick={()=>run(`/docker/network/${encodeURIComponent(selected.id)}`,'DELETE')}>Delete</button></div></Card><Card><h3>Connected Containers</h3>{members(selected).map((c:any)=><p key={c.id}><b>{c.name}</b> <Badge tone={c.status==='running'?'green':'gray'}>{c.status}</Badge><small className="docker-image">{c.networks[selected.name]?.IPAddress||'IP not reported'}</small></p>)}{!count(selected)&&<p className="muted">No container attachments reported.</p>}</Card></>:<Card>Select a network to see its details.</Card>}</div></div>
 <div className="volume-bottom"><Card><h3>Networks by Driver</h3>{Array.from(new Set(networks.map((n:any)=>n.driver))).map((d:any)=><div className="volume-size-row" key={d}><button className="image-name" onClick={()=>{setDriver(d);setPage(0)}}>{d}</button><b>{networks.filter((n:any)=>n.driver===d).length}</b></div>)}</Card><Card><h3>Network Information</h3><p className="muted">Attachment counts include stopped containers. Docker protects its built-in networks from deletion.</p><p className="muted">The Engine API does not report per-network traffic history. Inspect provides current addressing and endpoints for troubleshooting.</p></Card><Card><h3>Quick Actions</h3><div className="backup-quick"><button className="btn secondary" disabled={!enabled} onClick={()=>setModal('Create Network')}>Create Network</button><button className="btn secondary" disabled={!enabled||!admin||busy} onClick={()=>run('/docker/prune/networks')}>Prune Networks</button><button className="btn secondary" disabled={!detail} onClick={()=>setModal('Inspect Network')}>Network Troubleshoot</button></div></Card></div>
 <Modal open={!!modal} title={modal} onClose={()=>!busy&&setModal('')}>{error&&<p className="error">{error}</p>}{modal==='Create Network'?<form className="form-grid" onSubmit={e=>{e.preventDefault();run('/docker/network','POST',Object.fromEntries(new FormData(e.currentTarget)))}}><label>Network name<input name="name" required/></label><p className="muted">Creates a bridge network with Docker-managed addressing.</p><button className="btn primary" disabled={busy}>{busy?'Creating...':'Create Network'}</button></form>:modal==='Connected Containers'?<div>{selected&&members(selected).map((c:any)=><p key={c.id}>{c.name} · {c.status} · {c.networks[selected.name]?.IPAddress||'IP not reported'}</p>)}{selected&&!count(selected)&&<p>No attachments reported.</p>}</div>:<pre className="task-log">{JSON.stringify(detail,null,2)}</pre>}</Modal>
 </div>;
}
