import {useEffect,useState} from 'react';
import {Database,HardDrive,Archive,Trash2} from 'lucide-react';
import {useApi} from '../hooks';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(n:any)=>n==null?'Unknown':`${(n/(n>=1024**3?1024**3:1024**2)).toFixed(1)} ${n>=1024**3?'GiB':'MiB'}`;
export default function DockerVolumes({data,enabled,admin,refresh}:{data:any;enabled:boolean;admin:boolean;refresh:()=>Promise<any>}){
 const usage=useApi<any>('/docker/volumes/usage',null),volumes=data?.volumes||[],containers=data?.containers||[];
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('name'),[page,setPage]=useState(0),[id,setId]=useState(''),[detail,setDetail]=useState<any>(null),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refs=(v:any)=>containers.filter((c:any)=>c.mounts?.some((m:any)=>m.Type==='volume'&&m.Name===v.name));
 const measure=(v:any)=>usage.data?.volumes?.find((r:any)=>r.name===v.name);
 const referenceCount=(v:any)=>measure(v)?.references??(data?.host?refs(v).length:null);
 const size=(v:any)=>measure(v)?.size??null;
 const unused=volumes.filter((v:any)=>referenceCount(v)===0),known=volumes.filter((v:any)=>size(v)!=null),total=known.length===volumes.length&&!!data?.host?known.reduce((s:number,v:any)=>s+size(v),0):null;
 const reclaimable=usage.data&&unused.every((v:any)=>size(v)!=null)?unused.reduce((s:number,v:any)=>s+size(v),0):null;
 const filtered=volumes.filter((v:any)=>`${v.name} ${v.mountpoint} ${refs(v).map((c:any)=>c.name).join(' ')}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='unused'?referenceCount(v)===0:referenceCount(v)>0))).sort((a:any,b:any)=>sort==='size'?(size(b)??-1)-(size(a)??-1):a.name.localeCompare(b.name));
 const pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages-1),selected=volumes.find((v:any)=>v.id===id)||filtered[0];
 useEffect(()=>{setDetail(null);if(!selected||!data?.host)return;let active=true;api(`/docker/volume/${encodeURIComponent(selected.id)}`).then(r=>{if(active)setDetail(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[selected?.id,data]);
 const reload=async()=>{await Promise.all([refresh(),usage.refresh()]);};
 const run=async(path:string,method='POST',body:any={})=>{setBusy(true);setError('');setNotice('');try{const result=await confirmedApi(path,{method,body:method==='DELETE'?undefined:JSON.stringify(body)});setNotice(result.result?.SpaceReclaimed!=null?`Completed. Docker reclaimed ${bytes(result.result.SpaceReclaimed)}.`:'Operation completed.');setModal('');await reload();}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const submit=(e:any)=>{e.preventDefault();return run('/docker/volume','POST',Object.fromEntries(new FormData(e.currentTarget)));};
 return <div className="docker-volumes"><div className="volume-header"><div><small className="muted">Docker › {data?.host?.hostname||'Engine connection'} › Volumes</small><h2>Docker Volumes</h2><p className="muted">Manage persistent storage for your containers.</p></div><div className="header-actions"><button className="btn secondary" disabled={!enabled||!admin||busy} onClick={()=>run('/docker/prune/volumes')}>Prune Unused Anonymous Volumes</button><button className="btn primary" disabled={!enabled||busy} onClick={()=>{setError('');setModal('Create Volume')}}>Create Volume</button></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="volume-summary">{[[Database,'Total Volumes',data?.host?volumes.length:'Unknown','Engine inventory'],[HardDrive,'Used Space',bytes(total),`${known.length} measured volumes`],[Archive,'Unused Volumes',data?.host?unused.length:'Unknown','No container references'],[Trash2,'Unused Data Size',bytes(reclaimable),'Pruning may remove only a subset']].map(([Icon,label,value,sub]:any)=><Card key={label}><Icon size={25}/><div><small>{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div></Card>)}</div>
 {usage.error&&data?.host&&<p className="muted">Volume sizes unavailable: {usage.error}. Inventory and container references remain available.</p>}
 <div className="volume-workspace"><Card><div className="volume-toolbar"><input aria-label="Search volumes" placeholder="Search volume, container or path..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Volume usage" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="all">All Volumes</option><option value="used">In Use</option><option value="unused">Unused</option></select><select aria-label="Sort volumes" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort by Name</option><option value="size">Sort by Size</option></select><button className="btn secondary small" disabled={busy} onClick={reload}>Refresh</button></div><div className="table-wrap"><table><thead><tr>{['Volume Name','Containers','Mount Point','Size','Status','Created','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map((v:any)=><tr key={v.id} className={selected?.id===v.id?'image-selected':''}><td><button className="image-name" onClick={()=>{setId(v.id);setError('')}}>{v.name}</button></td><td>{refs(v).map((c:any)=>c.name).join(', ')||'—'}</td><td title={v.mountpoint}><span className="volume-path">{v.mountpoint||'Not reported'}</span></td><td>{bytes(size(v))}</td><td><Badge tone={referenceCount(v)>0?'green':'gray'}>{referenceCount(v)==null?'Unknown':referenceCount(v)>0?'In Use':'Unused'}</Badge></td><td>{v.created?new Date(v.created).toLocaleDateString():'Not reported'}</td><td><button className="btn secondary small" onClick={()=>setId(v.id)}>View</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">No matching volumes reported. Connect Docker Engine to load its volumes.</p>}<div className="vm-pagination"><small>{filtered.length} volumes</small><button className="btn secondary small" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1}/{pages}</span><button className="btn secondary small" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></Card>
 <div className="docker-side">{selected?<><Card><h3>Volume Details</h3><h3>{selected.name}</h3><Badge tone={referenceCount(selected)>0?'green':'gray'}>{referenceCount(selected)>0?'In Use':'Unused'}</Badge><dl className="task-details">{Object.entries({'Name':selected.name,'Host Mount Point':detail?.Mountpoint||selected.mountpoint,'Size':bytes(size(selected)),'Created':detail?.CreatedAt||selected.created,'Driver':detail?.Driver||selected.driver,'Scope':detail?.Scope||selected.scope,'Labels':JSON.stringify(detail?.Labels||selected.labels||{}),'Mount Options':JSON.stringify(detail?.Options||selected.options||{})}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not reported'}</dd></div>)}</dl><div className="header-actions"><button className="btn secondary" disabled={!detail} onClick={()=>setModal('Inspect Volume')}>Inspect</button><button className="btn danger" disabled={!enabled||!admin||busy||referenceCount(selected)>0} onClick={()=>run(`/docker/volume/${encodeURIComponent(selected.id)}`,'DELETE')}>Remove</button></div></Card><Card><h3>Container Mounts</h3>{refs(selected).map((c:any)=><div key={c.id}><b>{c.name}</b><Badge tone={c.status==='running'?'green':'gray'}>{c.status}</Badge>{c.mounts.filter((m:any)=>m.Name===selected.name).map((m:any)=><p className="muted" key={m.Destination}>{m.Destination} · {m.RW?'Read/write':'Read-only'}</p>)}</div>)}{!refs(selected).length&&<p className="muted">No container mounts reported.</p>}<small className="muted">Stopped containers also retain volume references.</small></Card></>:<Card>Select a volume to inspect its details.</Card>}</div></div>
 <div className="volume-bottom"><Card><h3>Top Volumes by Size</h3>{[...known].sort((a:any,b:any)=>size(b)-size(a)).slice(0,5).map((v:any)=><div className="volume-size-row" key={v.id}><button className="image-name" onClick={()=>setId(v.id)}>{v.name}</button><b>{bytes(size(v))}</b></div>)}{!known.length&&<p className="muted">No size measurements reported.</p>}</Card><Card><h3>Volume Drivers</h3>{Array.from(new Set(volumes.map((v:any)=>v.driver))).map((d:any)=><p key={d}>{d}: <b>{volumes.filter((v:any)=>v.driver===d).length}</b></p>)}</Card><Card><h3>Storage Information</h3><p className="muted">Docker reports volume data sizes when supported. Free space and per-volume capacity are not reported by this API.</p><p className="muted">File browsing and data backups require access to the Docker host or a configured backup tool.</p></Card></div>
 <Modal open={!!modal} title={modal} onClose={()=>!busy&&setModal('')}>{error&&<p className="error" role="alert">{error}</p>}{modal==='Inspect Volume'?<pre className="task-log">{JSON.stringify(detail,null,2)}</pre>:<form className="form-grid" onSubmit={submit}><label>Volume name<input name="name" required placeholder="app_data"/></label><small className="muted">Creates a local Docker volume.</small><button className="btn primary" disabled={busy}>{busy?'Working...':'Create Volume'}</button></form>}</Modal>
 </div>;
}