import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Archive,Box,Columns3,Cpu,ExternalLink,Grid2X2,HardDrive,MemoryStick,MoreHorizontal,Play,Power,RefreshCw,RotateCw,Search,Tag,Terminal} from 'lucide-react';
import {api,confirmedApi} from '../api';
import {useApi} from '../hooks';
import {Badge,Card,Modal} from '../components/UI';

const bytes=(value:any)=>value==null?'Unavailable':Number(value)>=1024**3?`${(Number(value)/1024**3).toFixed(1)} GiB`:Number(value)>=1024**2?`${(Number(value)/1024**2).toFixed(1)} MiB`:`${Number(value)} B`;
const duration=(value:any)=>value==null?'Unavailable':`${Math.floor(Number(value)/86400)}d ${Math.floor(Number(value)%86400/3600)}h`;
const percent=(value:any)=>value==null?'Unavailable':`${Math.round(Number(value))}%`;
const sum=(rows:any[],key:string)=>rows.length&&rows.every(row=>typeof row[key]==='number')?rows.reduce((total,row)=>total+row[key],0):null;
const tone=(status:string)=>status==='running'?'green':status==='stopped'?'red':'gray';

export default function LxcContainers({data,role,clusterUrl,refresh}:{data:any;role?:string;clusterUrl?:string;refresh:()=>Promise<void>}){
 const [params,setParams]=useSearchParams();
 const containers=data?.lxc||[],nodes=data?.nodes||[],storage=data?.storage||[],operator=['operator','admin','owner'].includes(role||'');
 const [selected,setSelected]=useState<string>(containers[0]?.id||''),[search,setSearch]=useState(''),[node,setNode]=useState('all'),[status,setStatus]=useState('all'),[layout,setLayout]=useState<'list'|'grid'>('list'),[page,setPage]=useState(1);
 const [modal,setModal]=useState<'create'|'snapshot'|'backup'|null>(null),[pending,setPending]=useState(''),[message,setMessage]=useState(''),[failure,setFailure]=useState('');
 useEffect(()=>{if(!containers.some((ct:any)=>ct.id===selected))setSelected(containers[0]?.id||'');},[containers,selected]);
 useEffect(()=>{if(params.get('action')==='Create CT'){setModal('create');setParams({}, {replace:true});}},[params.get('action')]);
 const filtered=useMemo(()=>containers.filter((ct:any)=>(node==='all'||ct.node===node)&&(status==='all'||ct.status===status)&&`${ct.id} ${ct.name} ${ct.node}`.toLowerCase().includes(search.toLowerCase())),[containers,node,status,search]);
 useEffect(()=>setPage(1),[node,status,search]);
 const pages=Math.max(1,Math.ceil(filtered.length/10)),visible=filtered.slice((page-1)*10,page*10),current=containers.find((ct:any)=>ct.id===selected)||containers[0];
 const usedMemory=sum(containers,'memory'),totalMemory=sum(containers,'memoryTotal'),usedDisk=sum(containers,'disk'),totalDisk=sum(containers,'diskTotal');
 const measuredCpu=containers.filter((ct:any)=>typeof ct.cpu==='number'),averageCpu=measuredCpu.length?Math.round(measuredCpu.reduce((total:number,ct:any)=>total+ct.cpu,0)/measuredCpu.length):null;
 const run=async(operation:string)=>{if(!current)return;setPending(operation);setFailure('');setMessage('');try{const result:any=await confirmedApi(`/actions/proxmox/lxc/${encodeURIComponent(current.id)}/${operation}`,{method:'POST',body:JSON.stringify({node:current.node})});setMessage(result.message||`${operation} submitted.`);await refresh();}catch(e:any){setFailure(e.message);}finally{setPending('');}};
 const submit=async(event:any)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));setPending(modal||'');setFailure('');setMessage('');try{let result:any;if(modal==='create')result=await api('/proxmox/ct',{method:'POST',body:JSON.stringify(values)});else if(modal==='snapshot')result=await api(`/actions/proxmox/lxc/${encodeURIComponent(current.id)}/snapshot`,{method:'POST',body:JSON.stringify({node:current.node,name:values.name})});else result=await api('/proxmox/backup',{method:'POST',body:JSON.stringify({node:current.node,vmid:current.id,storage:values.storage})});setMessage(result.message||'Task accepted.');setModal(null);await refresh();}catch(e:any){setFailure(e.message);}finally{setPending('');}};
 const openConsole=()=>{if(!current||!clusterUrl)return;const url=new URL(clusterUrl);url.searchParams.set('console','lxc');url.searchParams.set('xtermjs','1');url.searchParams.set('vmid',current.id);url.searchParams.set('vmname',current.name);url.searchParams.set('node',current.node);window.open(url.toString(),'_blank','noopener,noreferrer');};
 return <section className="vm-manager">
  <div className="vm-title"><div><h2>LXC Containers</h2><p>Create, monitor and manage containers reported by the connected Proxmox cluster.</p></div><div><button className="btn secondary" onClick={refresh}><RefreshCw size={14}/>Refresh</button>{operator&&<button className="btn primary" onClick={()=>setModal('create')}>+ Create Container</button>}</div></div>
  {(failure||message)&&<p className={failure?'login-error':'vm-message'} role={failure?'alert':'status'}>{failure||message}</p>}
  <div className="vm-stats">
   <CtStat icon={Box} label="Total Containers" value={containers.length} detail={`${containers.filter((ct:any)=>ct.status==='running').length} running · ${containers.filter((ct:any)=>ct.status==='stopped').length} stopped`}/>
   <CtStat icon={Cpu} label="Average CPU" value={averageCpu==null?'Unavailable':`${averageCpu}%`} detail={`${measuredCpu.length}/${containers.length} containers reporting`}/>
   <CtStat icon={MemoryStick} label="Memory Usage" value={bytes(usedMemory)} detail={totalMemory==null?'Capacity unavailable':`of ${bytes(totalMemory)}`}/>
   <CtStat icon={HardDrive} label="Root Disk Usage" value={bytes(usedDisk)} detail={totalDisk==null?'Capacity unavailable':`of ${bytes(totalDisk)}`}/>
  </div>
  <div className="vm-workspace">
   <Card className="vm-list-card">
    <div className="vm-filters"><select aria-label="Filter containers by node" value={node} onChange={e=>setNode(e.target.value)}><option value="all">All Nodes</option>{nodes.map((item:any)=><option key={item.name}>{item.name}</option>)}</select><select aria-label="Filter containers by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option>{[...new Set(containers.map((ct:any)=>ct.status).filter(Boolean))].map((value:any)=><option key={value}>{value}</option>)}</select><label className="vm-search"><Search size={14}/><input aria-label="Search containers" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search containers…"/></label><div className="vm-layout"><button aria-label="List view" className={layout==='list'?'active':''} onClick={()=>setLayout('list')}><Columns3 size={15}/></button><button aria-label="Grid view" className={layout==='grid'?'active':''} onClick={()=>setLayout('grid')}><Grid2X2 size={15}/></button></div></div>
    {layout==='list'?<div className="table-wrap"><table className="vm-table"><thead><tr><th>ID</th><th>Name</th><th>Node</th><th>Status</th><th>CPU</th><th>Memory</th><th>Root disk</th><th>Uptime</th><th>Actions</th></tr></thead><tbody>{visible.map((ct:any)=><tr key={ct.id} className={current?.id===ct.id?'selected':''} onClick={()=>setSelected(ct.id)}><td>{ct.id}</td><td><b>{ct.name}</b></td><td>{ct.node}</td><td><Badge tone={tone(ct.status)}>{ct.status||'Unknown'}</Badge></td><td>{percent(ct.cpu)}</td><td><Meter value={ct.memoryPercent} text={ct.memoryTotal!=null?`${bytes(ct.memory)} / ${bytes(ct.memoryTotal)}`:bytes(ct.memory)}/></td><td><Meter value={ct.diskPercent} text={ct.diskTotal!=null?`${bytes(ct.disk)} / ${bytes(ct.diskTotal)}`:bytes(ct.disk)}/></td><td>{duration(ct.uptime)}</td><td><button className="icon-btn" aria-label={`View ${ct.name}`} onClick={event=>{event.stopPropagation();setSelected(ct.id)}}><MoreHorizontal size={15}/></button></td></tr>)}</tbody></table></div>:<div className="vm-card-grid">{visible.map((ct:any)=><button key={ct.id} className={current?.id===ct.id?'selected':''} onClick={()=>setSelected(ct.id)}><Box size={25}/><span><b>{ct.name}</b><small>CT {ct.id} · {ct.node}</small></span><Badge tone={tone(ct.status)}>{ct.status}</Badge><small>CPU {percent(ct.cpu)} · Memory {percent(ct.memoryPercent)}</small></button>)}</div>}
    {!visible.length&&<p className="vm-empty">No containers match these filters.</p>}
    <div className="vm-pagination"><span>Showing {visible.length?`${(page-1)*10+1}–${(page-1)*10+visible.length}`:'0'} of {filtered.length} containers</span><div><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>‹</button><b>{page} / {pages}</b><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>›</button></div></div>
   </Card>
   {current?<CtDetails ct={current} role={role} clusterUrl={clusterUrl} busy={pending} run={run} console={openConsole} snapshot={()=>setModal('snapshot')} backup={()=>setModal('backup')}/>:<Card><p className="vm-empty">No container selected.</p></Card>}
  </div>
  <Modal open={!!modal} title={modal==='create'?'Create LXC Container':modal==='snapshot'?'Create Snapshot':'Back Up Container'} onClose={()=>!pending&&setModal(null)}><form className="form-grid vm-form" onSubmit={submit}>
   {modal==='create'?<><label>Hostname<input name="name" required/></label><label>Node<select name="node" required>{nodes.map((item:any)=><option key={item.name}>{item.name}</option>)}</select></label><label className="cluster-wide">Template volume<input name="ostemplate" required placeholder="local:vztmpl/debian-12-standard.tar.zst"/></label><label>Root storage<select name="storage" required>{storage.map((item:any)=><option key={item.id} value={item.name}>{item.node} / {item.name}</option>)}</select></label><label>CPU cores<input name="cores" type="number" min="1" max="128" defaultValue="2" required/></label><label>Memory MB<input name="memory" type="number" min="128" max="1048576" defaultValue="1024" required/></label><label>Root disk GB<input name="disk" type="number" min="1" max="65536" defaultValue="8" required/></label><label>Network bridge<input name="bridge" defaultValue="vmbr0" required/></label><label className="cluster-wide">Public SSH key (optional)<textarea name="sshKey" rows={3}/></label></>:modal==='snapshot'?<label className="cluster-wide">Snapshot name<input name="name" pattern="[A-Za-z0-9][A-Za-z0-9_-]*" required placeholder="before-upgrade"/></label>:<label className="cluster-wide">Backup storage<select name="storage" required>{storage.map((item:any)=><option key={item.id} value={item.name}>{item.node} / {item.name}</option>)}</select></label>}
   {failure&&<p className="login-error cluster-wide">{failure}</p>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setModal(null)}>Cancel</button><button className="btn primary" disabled={!!pending}>{pending?'Submitting…':'Submit'}</button></div>
  </form></Modal>
 </section>;
}

function CtStat({icon:Icon,label,value,detail}:{icon:any;label:string;value:any;detail:string}){return <div className="vm-stat"><Icon size={25}/><div><small>{label}</small><strong>{value}</strong><span>{detail}</span></div></div>}
function Meter({value,text}:{value:any;text:string}){return <div className="vm-meter"><span>{text}</span><i><b style={{width:`${Math.max(0,Math.min(100,Number(value)||0))}%`}}/></i></div>}

function CtDetails({ct,role,clusterUrl,busy,run,console,snapshot,backup}:{ct:any;role?:string;clusterUrl?:string;busy:string;run:(action:string)=>void;console:()=>void;snapshot:()=>void;backup:()=>void}){
 const details=useApi<any>(`/proxmox/lxc/${encodeURIComponent(ct.node)}/${encodeURIComponent(ct.id)}/details`,null),[tab,setTab]=useState('Overview');
 const operator=['operator','admin','owner'].includes(role||''),config=details.data?.config||{},runtime=details.data?.status||{},snapshots=Array.isArray(details.data?.snapshots)?details.data.snapshots:[],interfaces=Array.isArray(details.data?.interfaces)?details.data.interfaces:[];
 useEffect(()=>{details.refresh();setTab('Overview');},[ct.id,ct.node]);
 const ipv4=interfaces.flatMap((item:any)=>[item.inet,item.address,item.ip]).find((value:any)=>value&&!String(value).startsWith('127.'));
 return <div className="vm-detail-stack"><Card className="vm-detail"><div className="vm-detail-head"><div><Box size={24}/><span><b>{ct.name}</b><small>CT {ct.id} · Node: {ct.node}</small></span><Badge tone={tone(ct.status)}>{ct.status}</Badge></div></div><div className="vm-detail-tabs">{['Overview','Console','Resources','Snapshots','Backups','Network','More'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
  {details.error&&<p className="login-error">{details.error}</p>}
  {tab==='Overview'&&<><div className="vm-overview-grid"><div><small>Status</small><b>{runtime.status||ct.status||'Unavailable'}</b></div><div><small>Uptime</small><b>{duration(runtime.uptime??ct.uptime)}</b></div><div><small>Hostname</small><b>{config.hostname||ct.name}</b></div><div><small>OS type</small><b>{config.ostype||'Unavailable'}</b></div><div><small>IPv4 address</small><b>{ipv4||'Unavailable'}</b></div><div><small>Unprivileged</small><b>{config.unprivileged==null?'Unavailable':config.unprivileged?'Yes':'No'}</b></div></div><div className="vm-detail-actions"><button disabled={!operator||ct.status==='running'||!!busy} onClick={()=>run('start')}><Play size={15}/>Start</button><button className="danger" disabled={!operator||ct.status!=='running'||!!busy} onClick={()=>run('shutdown')}><Power size={15}/>Shutdown</button><button disabled={!operator||ct.status!=='running'||!!busy} onClick={()=>run('reboot')}><RotateCw size={15}/>Reboot</button><button disabled={!clusterUrl} onClick={console}><ExternalLink size={15}/>Console</button></div></>}
  {tab==='Console'&&<div className="vm-tab-content"><Terminal size={34}/><p>Open the authenticated Proxmox terminal for this container.</p><button className="btn primary" disabled={!clusterUrl} onClick={console}>Open Console</button></div>}
  {tab==='Resources'&&<div className="vm-kv">{Object.keys(config).length?Object.entries(config).sort().map(([key,value])=><p key={key}><span>{key}</span><b>{typeof value==='object'?JSON.stringify(value):String(value)}</b></p>):<p>Container configuration is unavailable.</p>}</div>}
  {tab==='Snapshots'&&<div className="vm-tab-content"><button className="btn primary" disabled={!operator} onClick={snapshot}>Create Snapshot</button>{snapshots.length?<div className="vm-snapshots">{snapshots.map((item:any)=><p key={item.name}><b>{item.name}</b><span>{item.snaptime?new Date(item.snaptime*1000).toLocaleString():'Current state'}</span></p>)}</div>:<p>No snapshots reported.</p>}</div>}
  {tab==='Backups'&&<div className="vm-tab-content"><Archive size={32}/><p>Submit a snapshot-mode backup to a Proxmox backup-capable storage target.</p><button className="btn primary" disabled={!operator} onClick={backup}>Back Up Container</button></div>}
  {tab==='Network'&&<div className="vm-kv">{interfaces.length?interfaces.map((item:any,index:number)=><p key={item.name||index}><span>{item.name||`Interface ${index+1}`}</span><b>{item.inet||item.address||item.ip||JSON.stringify(item)}</b></p>):<p>Live interface details are unavailable. The container may be stopped or the token may need additional audit permission.</p>}</div>}
  {tab==='More'&&<div className="vm-tab-content"><p>Power actions are sent to Proxmox and their completion is reported in Tasks &amp; Logs.</p><div className="vm-detail-actions"><button disabled={!operator||!!busy} onClick={()=>run('stop')}>Force Stop</button><button disabled={!operator||!!busy} onClick={()=>run('suspend')}>Suspend</button><button disabled={!operator||!!busy} onClick={()=>run('resume')}>Resume</button></div></div>}
  {!!details.data?.errors?.length&&<details className="permission-help"><summary>{details.data.errors.length} container readings unavailable</summary>{details.data.errors.map((error:string)=><p key={error}>{error}</p>)}</details>}
 </Card><Card className="vm-resource"><div className="widget-title"><h3>Resource Usage</h3><Tag size={15}/></div><div><Meter value={ct.cpu} text={`CPU ${percent(ct.cpu)}`}/><Meter value={ct.memoryPercent} text={`Memory ${ct.memoryTotal!=null?`${bytes(ct.memory)} / ${bytes(ct.memoryTotal)}`:bytes(ct.memory)}`}/><Meter value={ct.diskPercent} text={`Root disk ${ct.diskTotal!=null?`${bytes(ct.disk)} / ${bytes(ct.diskTotal)}`:bytes(ct.disk)}`}/></div></Card></div>;
}
