import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Server,Monitor,Container,Bell,Archive,Plus,Activity,ShieldCheck,Network,RefreshCw,Download,Sparkles} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,XAxis,YAxis,Tooltip} from 'recharts';
import {useApi} from '../hooks';
import {api} from '../api';
import {Card,Modal} from '../components/UI';
import {downloadReport} from '../components/Discovery';
const percent=(value:any)=>typeof value==='number'?`${Math.round(value)}%`:'Unknown';
const average=(rows:any[],key:string)=>{const values=rows.map(r=>r[key]).filter(v=>typeof v==='number');return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;};
const widgets=['resources','health','alerts','history','guests','actions','map','backups','assistant','services'];
export default function Overview(){
 const {data,error,loading,refresh}=useApi<any>('/dashboard',null);
 const {data:backup}=useApi<any>('/backups',null);
 const navigate=useNavigate();
 const [node,setNode]=useState(''),[hours,setHours]=useState('24'),[search,setSearch]=useState(''),[customize,setCustomize]=useState(false),[failure,setFailure]=useState(''),[checking,setChecking]=useState(false),[answer,setAnswer]=useState('');
 const [visible,setVisible]=useState<string[]>(()=>{try{const stored=JSON.parse(localStorage.getItem('homecloud-widgets')||'null');return Array.isArray(stored)?stored.filter(w=>widgets.includes(w)):widgets;}catch{return widgets;}});
 useEffect(()=>{localStorage.setItem('homecloud-widgets',JSON.stringify(visible));},[visible]);
 const forceRefresh=async()=>{setFailure('');try{await api('/dashboard?refresh=1');await refresh();}catch(e:any){setFailure(e.message);}};
 const assess=async()=>{setChecking(true);setFailure('');try{setAnswer((await api('/ai/chat',{method:'POST',body:JSON.stringify({message:'Summarize current infrastructure health and the most urgent measured issues.'})})).result.answer);}catch(e:any){setFailure(e.message);}finally{setChecking(false);}};
 if(!data)return <Card>{error||'Loading infrastructure…'}</Card>;
 const nodes=(data.nodes||[]).filter((n:any)=>!node||n.name===node),guests=(data.guests||[]).filter((g:any)=>!node||g.node===node),storage=(data.storage||[]).filter((s:any)=>!node||s.node===node);
 const resources=(data.resources||[]).filter((r:any)=>(!node||r.host===node||r.node===node)&&(r.name+' '+r.host+' '+r.kind).toLowerCase().includes(search.toLowerCase()));
 const history=(data.metrics||[]).filter((m:any)=>Date.parse(m.time)>=Date.now()-Number(hours)*3600000).map((m:any)=>{const selected=node?m.nodes?.find((n:any)=>n.name===node):m;return {time:m.time,cpu:selected?.cpu??null,memory:selected?.memory??null};});
 const cpu=average(nodes,'cpu'),memory=average(nodes,'memoryPercent'),disk=average(storage,'usage');
 const alerts=(data.alerts||[]).filter((a:any)=>a.status!=='resolved'&&(!node||a.source===node));
 const online=nodes.filter((n:any)=>n.status==='online').length;
 const configured=data.services?.length||0,reachable=data.services?.filter((s:any)=>s.status==='reachable').length||0;
 const health=configured?Math.round(reachable/configured*100):null;
 const has=(name:string)=>visible.includes(name);
 const chart=(small=false)=><ResponsiveContainer width="100%" height={small?72:180}><AreaChart data={history}><XAxis hide={small} dataKey="time" minTickGap={40} tickFormatter={v=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}/><YAxis hide={small} domain={[0,100]} width={30}/><Tooltip labelFormatter={v=>new Date(v).toLocaleString()}/><Area name="CPU %" dataKey="cpu" stroke="#438eff" fill="#438eff22" connectNulls={false} isAnimationActive={false}/><Area name="Memory %" dataKey="memory" stroke="#a277ff" fill="#a277ff18" connectNulls={false} isAnimationActive={false}/></AreaChart></ResponsiveContainer>;
 return <div className="overview-v2">
 <div className="overview-toolbar"><div><h1>Overview</h1><p><span className={`status-dot ${alerts.length||configured!==reachable?'warning':''}`}/>{alerts.length?`${alerts.length} issue(s) need attention`:configured===reachable&&configured?'Connected infrastructure responding':'Connect a cluster to discover infrastructure'}</p></div><div className="overview-controls"><select aria-label="Select node" value={node} onChange={e=>setNode(e.target.value)}><option value="">All Nodes</option>{(data.nodes||[]).map((n:any)=><option key={n.name}>{n.name}</option>)}</select><select aria-label="History period" value={hours} onChange={e=>setHours(e.target.value)}>{['1','6','24'].map(h=><option key={h} value={h}>Last {h} hour{h==='1'?'':'s'}</option>)}</select><button className="btn primary" onClick={()=>setCustomize(true)}><Plus size={15}/>Add Widget</button><button className="icon-btn" aria-label="Refresh live measurements" disabled={loading} onClick={forceRefresh}><RefreshCw size={16}/></button><button className="icon-btn" aria-label="Export overview report" onClick={()=>downloadReport({...data,selectedNode:node,history})}><Download size={16}/></button></div></div>
 {(error||failure)&&<p className="login-error" role="alert">{error||failure}</p>}
 <div className="overview-stats">{[
  {label:'Total Servers',value:nodes.length,detail:`${online} Online`,icon:Server,path:'/proxmox'},
  {label:'Virtual Machines',value:guests.filter((g:any)=>g.type==='qemu').length,detail:`${guests.filter((g:any)=>g.type==='qemu'&&g.status==='running').length} Running`,icon:Monitor,path:'/proxmox'},
  {label:'Containers',value:guests.filter((g:any)=>g.type==='lxc').length+resources.filter((r:any)=>r.kind==='Docker container').length,detail:`${guests.filter((g:any)=>g.type==='lxc'&&g.status==='running').length+resources.filter((r:any)=>r.kind==='Docker container'&&r.status==='running').length} Running`,icon:Container,path:'/docker'},
  {label:'Alerts',value:alerts.length,detail:`${alerts.filter((a:any)=>a.severity==='critical').length} Critical`,icon:Bell,path:'/alerts'},
  {label:'Backups',value:backup?.points?.length??'—',detail:backup?'Discovered archives':'Not measured',icon:Archive,path:'/backups'}
 ].map((s,i)=><Link className={`overview-stat tone-${i}`} to={s.path} key={s.label}><div><span>{s.label}</span><strong>{s.value}</strong><small>{s.detail}</small></div><div className="overview-stat-icon"><s.icon size={26}/></div></Link>)}</div>
 <div className="overview-grid">
 {has('resources')&&<Card className="overview-resources"><div className="widget-heading"><h3>System Resources</h3><span>{node||'All Nodes'}</span></div><div className="resource-tiles">{[['CPU Usage',cpu,'Online node average'],['Memory Usage',memory,'Reported memory utilization'],['Storage Usage',disk,'Reported storage utilization']].map(([name,value,detail])=><div className="resource-tile" key={String(name)}><span>{String(name)}</span><strong>{percent(value)}</strong><small>{String(detail)}</small>{name==='Storage Usage'?<div className="mini-meter"><span style={{width:`${disk??0}%`}}/></div>:chart(true)}</div>)}</div></Card>}
 {has('health')&&<Card><div className="widget-heading"><h3>Infrastructure Health</h3><Link to="/monitoring">View Details</Link></div><div className="health-layout"><div className="actual-health" style={{background:`conic-gradient(#68cc3a ${(health??0)*3.6}deg,#253343 0)`}}><div><strong>{health??'—'}</strong><small>% APIs reachable</small></div></div><div>{[['Nodes online',nodes.length?online/nodes.length*100:null],['CPU available',cpu==null?null:100-cpu],['Memory available',memory==null?null:100-memory],['Storage available',disk==null?null:100-disk]].map(([label,value])=><div className="health-line" key={String(label)}><span>{String(label)}</span><div className="mini-meter"><span style={{width:`${value??0}%`}}/></div><b>{percent(value)}</b></div>)}</div></div><small className="muted">Measured availability, not a security score.</small></Card>}
 {has('alerts')&&<Card><div className="widget-heading"><h3>Recent Alerts</h3><Link to="/alerts">View All</Link></div><div className="widget-scroll">{alerts.slice(0,4).map((a:any)=><Link className="alert-preview" to="/alerts" key={a.id}><Bell size={16}/><div><b>{a.title}</b><small>{a.source} · {a.details}</small></div><span className={`badge ${a.severity==='critical'?'red':'yellow'}`}>{a.severity}</span></Link>)}{!alerts.length&&<p className="muted">No active alerts reported.</p>}</div></Card>}
 {has('history')&&<Card className="overview-history"><div className="widget-heading"><h3>Resource Usage</h3><span>Last {hours} hours</span></div>{history.some((m:any)=>m.cpu!=null||m.memory!=null)?chart():<div className="widget-empty">Waiting for CPU and memory measurements. Check Proxmox token permissions below.</div>}</Card>}
 {has('guests')&&<Card><div className="widget-heading"><h3>Top VMs by Resource Usage</h3><Link to="/proxmox">View All</Link></div>{guests.filter((g:any)=>g.type==='qemu').sort((a:any,b:any)=>(b.cpu??-1)-(a.cpu??-1)).slice(0,5).map((g:any)=><Link className="guest-preview" to="/proxmox" key={g.id}><Monitor size={17}/><div><b>{g.name}</b><small>Node: {g.node}</small></div><div className="mini-meter"><span style={{width:`${Math.min(g.cpu??0,100)}%`}}/></div><b>{percent(g.cpu)}</b></Link>)}{!guests.length&&<p className="muted">No guests visible to the connected token.</p>}</Card>}
 {has('actions')&&<Card><div className="widget-heading"><h3>Quick Actions</h3></div><div className="quick-grid">{[['Create VM','/proxmox?action=Create%20VM',Monitor],['Cluster Settings','/proxmox',Server],['Docker Containers','/docker',Container],['Run Backup','/backups?action=Run%20Backup',Archive],['Network Map','/network',Network],['AI Health Check','',Sparkles]].map(([name,path,Icon]:any)=><button className="btn secondary" key={name} disabled={name==='AI Health Check'&&checking} onClick={()=>path?navigate(path):assess()}><Icon size={16}/>{name}</button>)}</div></Card>}
 {has('map')&&<Card><div className="widget-heading"><h3>Infrastructure Map</h3><Link to="/proxmox">View Nodes</Link></div><div className="infrastructure-map"><div className="map-hub"><Network size={23}/>Connected cluster</div><div>{nodes.map((n:any)=><Link to="/proxmox" key={n.name}><Server size={18}/><span>{n.name}<small>{n.status} · {guests.filter((g:any)=>g.node===n.name).length} guests</small></span></Link>)}{!nodes.length&&<span className="muted">No nodes discovered.</span>}</div></div></Card>}
 {has('backups')&&<Card><div className="widget-heading"><h3>Backup Status</h3><Link to="/backups">View All</Link></div><div className="backup-number"><Archive size={34}/><strong>{backup?.points?.length??'—'}</strong><span>Backup archives</span></div><p>{backup?.jobs?.length??'—'} configured jobs · {backup?.jobs?.filter((j:any)=>j.enabled).length??'—'} enabled</p><small className="muted">Archives and schedules reported by the provider. See Monitoring for completed task outcomes.</small></Card>}
 {has('assistant')&&<Card><div className="widget-heading"><h3>AI Assistant</h3><button className="btn primary" onClick={assess} disabled={checking}>{checking?'Reading…':'Ask AI'}</button></div><div className="assistant-preview"><Sparkles size={22}/><p>{answer||'Request a summary of the current live measurements and alerts.'}</p></div></Card>}
 {has('services')&&<Card className="overview-inventory"><div className="widget-heading"><h3>Automatically Discovered Services</h3><input aria-label="Search services" placeholder="Search services or host…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="compact-services">{resources.slice(0,60).map((r:any)=><Link to={r.kind==='Docker container'?'/docker':'/proxmox'} key={r.id}><Activity size={15}/><div><b>{r.name}</b><small>{r.host} · {r.kind}</small></div><span className={`badge ${['running','online'].includes(r.status)?'green':'gray'}`}>{r.status}</span></Link>)}{!resources.length&&<p className="muted">No services visible yet. Saving a cluster starts automatic API discovery.</p>}</div>{resources.length>60&&<p className="muted">Showing 60 matches. Narrow your search or export the full report.</p>}
 {data.services?.filter((s:any)=>s.status!=='reachable').map((s:any)=><details className="permission-help" key={s.name}><summary>{s.name}: {s.status} — connection details</summary><p>{s.error}</p><p>For HTTP 403 on nodes, in Proxmox open Datacenter → Permissions. Assign PVEAuditor at path / with Propagate enabled to both the user and API token. A token with Privilege Separation needs its own permission entry.</p></details>)}
 {!!data.discoveryLimitations?.length&&<details className="permission-help"><summary>Guest discovery access ({data.discoveryLimitations.length})</summary>{data.discoveryLimitations.map((message:string)=><p key={message}>{message}</p>)}<p>VM application discovery uses the existing QEMU guest agent via Proxmox. Inventory commands require guest-agent execution permission (VM.GuestAgent.Unrestricted on Proxmox 9). No HomeCloud agent installation is required.</p></details>}
 </Card>}
 </div><p className="overview-sample">Last sample: {new Date(data.sampledAt).toLocaleString()} · Counts include only resources visible to your credentials.</p>
 <Modal open={customize} title="Choose overview widgets" onClose={()=>setCustomize(false)}><div className="widget-options">{widgets.map(w=><label key={w}><input type="checkbox" checked={has(w)} onChange={()=>setVisible(v=>has(w)?v.filter(x=>x!==w):[...v,w])}/>{w.charAt(0).toUpperCase()+w.slice(1)}</label>)}</div><button className="btn primary" onClick={()=>setCustomize(false)}>Done</button></Modal>
 </div>;
}
