import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Play,CheckCircle,AlertTriangle,Clock,RefreshCw,Download,ExternalLink} from 'lucide-react';
import {PieChart,Pie,Cell,Tooltip,ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Legend} from 'recharts';
import {useApi} from '../hooks';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const state=(t:any)=>t.status==='running'||t.status==='RUNNING'||(!t.endtime&&!t.status)?'Running':(t.exitstatus||t.status)==='OK'?'Completed':!t.status?'Unknown':'Failed';
const seconds=(t:any)=>t.starttime?Math.max(0,(t.endtime||Date.now()/1000)-t.starttime):null;
const duration=(v:any)=>v==null?'Unknown':v<60?`${Math.floor(v)}s`:`${Math.floor(v/60)}m ${Math.floor(v%60)}s`;
const colors=['#22c55e','#3b82f6','#ef4444','#a855f7','#f59e0b','#14b8a6'];
export default function ProxmoxTasks({role,clusterUrl,hours}:{role?:string;clusterUrl?:string;hours:string}){
 const live=useApi<any>(`/proxmox/tasks?hours=${hours}`,null),navigate=useNavigate(),rows=live.data?.tasks||[];
 const [search,setSearch]=useState(''),[node,setNode]=useState('all'),[status,setStatus]=useState('all'),[type,setType]=useState('all'),[page,setPage]=useState(0),[size,setSize]=useState(10),[selected,setSelected]=useState<any>(null),[details,setDetails]=useState<any>(null),[logs,setLogs]=useState<any[]>([]),[offset,setOffset]=useState(0),[auto,setAuto]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[run,setRun]=useState(false);
 const logBox=useRef<HTMLPreElement>(null),admin=['owner','admin'].includes(role||'');
 const filtered=rows.filter((t:any)=>(node==='all'||t.node===node)&&(status==='all'||state(t)===status)&&(type==='all'||t.type===type)&&[t.upid,t.id,t.node,t.type,t.user,t.status].join(' ').toLowerCase().includes(search.toLowerCase()));
 useEffect(()=>setPage(0),[search,node,status,type,size,hours]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)),shown=filtered.slice(Math.min(page,pages-1)*size,(Math.min(page,pages-1)+1)*size);
 useEffect(()=>{if(!selected)return;let active=true;const load=async()=>{try{const path=`/tasks/${encodeURIComponent(selected.node)}/${encodeURIComponent(selected.upid)}`;const [d,l]=await Promise.all([api(path),api(`${path}/log?start=${offset}`)]);if(active){setDetails(d);setLogs(l.logs||[]);setError('');}}catch(e:any){if(active)setError(e.message);}};load();const timer=window.setInterval(load,5000);return()=>{active=false;window.clearInterval(timer);};},[selected?.upid,selected?.node,offset]);
 useEffect(()=>{if(auto&&logBox.current)logBox.current.scrollTop=logBox.current.scrollHeight;},[logs,auto]);
 const select=(t:any)=>{setSelected(t);setDetails(null);setLogs([]);setOffset(0);setError('');};
 const download=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([logs.map(l=>`${l.n}: ${l.t}`).join('\n')],{type:'text/plain'}));a.href=url;a.download=`proxmox-task-log-${selected.node}-${offset}.txt`;a.click();URL.revokeObjectURL(url);};
 const stop=async()=>{setBusy(true);try{await confirmedApi(`/tasks/${encodeURIComponent(selected.node)}/${encodeURIComponent(selected.upid)}`,{method:'DELETE'});await live.refresh();setDetails(await api(`/tasks/${encodeURIComponent(selected.node)}/${encodeURIComponent(selected.upid)}`));}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const finished=rows.filter((t:any)=>t.endtime),avg=finished.length?finished.reduce((s:number,t:any)=>s+(seconds(t)||0),0)/finished.length:null;
 const distribution=(key:(t:any)=>string)=>Object.entries(rows.reduce((a:any,t:any)=>{const k=key(t);a[k]=(a[k]||0)+1;return a;},{})).map(([name,value])=>({name,value}));
 const history=Object.values(rows.reduce((a:any,t:any)=>{const day=new Date(t.starttime*1000).toLocaleDateString(),s=state(t);a[day]??={day,Completed:0,Running:0,Failed:0,Unknown:0};a[day][s]++;return a;},{})).reverse();
 const chart=(title:string,data:any[])=> <Card><h3>{title}</h3>{data.length?<><div className="task-pie"><ResponsiveContainer width="100%" height={140}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={40} outerRadius={60}>{data.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="task-legend">{data.map((d:any,i)=><span key={d.name}><i style={{background:colors[i%colors.length]}}/>{d.name} <b>{d.value}</b></span>)}</div></>:<p className="muted">No tasks reported.</p>}</Card>;
 return <section className="task-manager"><div className="page-header"><div><h2>Tasks &amp; Logs</h2><p className="muted">Live cluster operations and node task logs.</p></div><div className="header-actions"><button className="btn secondary" disabled={live.loading} onClick={live.refresh}><RefreshCw size={15}/> Refresh</button><button className="btn primary" onClick={()=>setRun(true)} disabled={!admin}><Play size={15}/> Run Task</button></div></div>
 {(live.error||error)&&<p className="error" role="alert">{live.error||error}</p>}{live.data?.errors?.map((e:string)=><p className="error" key={e}>{e}</p>)}{live.data?.truncated?.length>0&&<p className="muted">Showing up to 500 tasks per node. Narrow the time range to see more detail. Counts describe the returned tasks.</p>}
 <div className="task-stats">{[[Play,rows.filter((t:any)=>state(t)==='Running').length,'Running Tasks'],[CheckCircle,rows.filter((t:any)=>state(t)==='Completed').length,'Completed'],[AlertTriangle,rows.filter((t:any)=>state(t)==='Failed').length,'Failed Tasks'],[Clock,duration(avg),'Average Duration']].map(([Icon,value,label]:any)=><Card className="vm-stat" key={label}><span className="vm-stat-icon"><Icon size={25}/></span><div><strong>{live.data?value:'Unknown'}</strong><small>{label}</small><small className="muted">Returned tasks · last {hours} hours</small></div></Card>)}</div>
 <div className="task-workspace"><Card className="vm-list-card"><div className="vm-toolbar"><div><h3>Recent Tasks</h3><small className="muted">Select a task to inspect its status and log.</small></div><input aria-label="Search tasks" placeholder="Search tasks..." value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Task node" value={node} onChange={e=>setNode(e.target.value)}><option value="all">All Nodes</option>{live.data?.nodes?.map((n:any)=><option key={n.node}>{n.node}</option>)}</select><select aria-label="Task status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option>{['Running','Completed','Failed','Unknown'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Task type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All Types</option>{Array.from(new Set(rows.map((t:any)=>t.type))).map((t:any)=><option key={t}>{t}</option>)}</select></div>
 <div className="table-wrap"><table className="task-table"><thead><tr>{['Task / ID','Target','Node','User','Status','Started','Duration','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((t:any)=><tr key={t.upid} className={selected?.upid===t.upid?'task-selected':''}><td><b>{t.type}</b><small className="task-id" title={t.upid}>{t.upid}</small></td><td>{t.id||'—'}</td><td>{t.node}</td><td>{t.user||'Unknown'}</td><td><Badge tone={state(t)==='Failed'?'red':state(t)==='Running'?'blue':state(t)==='Unknown'?'gray':'green'}>{state(t)}</Badge></td><td>{new Date(t.starttime*1000).toLocaleString()}</td><td>{duration(seconds(t))}</td><td><button className="btn secondary small" onClick={()=>select(t)}>View</button></td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Loading tasks...':'No matching tasks reported.'}</p>}
 <div className="vm-pagination"><small>Showing {filtered.length?Math.min(page,pages-1)*size+1:0}–{Math.min((Math.min(page,pages-1)+1)*size,filtered.length)} of {filtered.length} tasks</small><button className="btn secondary small" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>{Math.min(page,pages-1)+1} / {pages}</span><button className="btn secondary small" disabled={page>=pages-1} onClick={()=>setPage(page+1)}>Next</button><select aria-label="Tasks per page" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,25,50].map(n=><option key={n} value={n}>{n} / page</option>)}</select></div></Card>
 <div className="task-detail-stack"><Card><div className="vm-toolbar"><h3>Task Details</h3>{selected&&<button className="btn secondary small" onClick={()=>setSelected(null)}>Close</button>}</div>{selected?<><Badge tone={state(details||selected)==='Failed'?'red':'blue'}>{state(details||selected)}</Badge><h3>{selected.type}</h3><dl className="task-details">{Object.entries({Task:selected.upid,Node:selected.node,Target:selected.id||'—',User:details?.user||selected.user||'Unknown',Started:new Date(selected.starttime*1000).toLocaleString(),Duration:duration(seconds({...selected,...details})),Result:details?.exitstatus||selected.status||'Pending',Progress:'Not reported by Proxmox'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="header-actions"><button className="btn danger" disabled={!admin||busy||details?.status!=='running'} onClick={stop}>Stop Task</button>{clusterUrl&&<a className="btn secondary" href={clusterUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Open Proxmox</a>}</div></>:<p className="muted">Choose a task from the list.</p>}</Card>
 <Card><div className="vm-toolbar"><h3>Live Task Log</h3><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto-scroll</label></div><pre className="task-log" ref={logBox}>{logs.length?logs.map(l=>`${l.n}: ${l.t}`).join('\n'):selected?'No log lines received yet.':'Select a task to load its log.'}</pre>{selected&&<><small className="muted">Updates every 5 seconds · up to 500 lines per page.</small><div className="header-actions"><button className="btn secondary small" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-500))}>Previous lines</button><button className="btn secondary small" disabled={logs.length<500} onClick={()=>setOffset(offset+500)}>Next lines</button><button className="btn secondary small" disabled={!logs.length} onClick={download}><Download size={14}/> Download page</button></div></>}</Card></div></div>
 <div className="task-charts">{chart('Task Types',distribution(t=>t.type||'Unknown'))}{chart('Task Status',distribution(state))}<Card><h3>Task History</h3><small className="muted">Returned tasks grouped by start date.</small>{history.length?<ResponsiveContainer width="100%" height={210}><BarChart data={history}><XAxis dataKey="day"/><YAxis allowDecimals={false}/><Tooltip/><Legend/>{['Completed','Running','Failed','Unknown'].map((s,i)=><Bar key={s} dataKey={s} stackId="status" fill={colors[i]}/>)}</BarChart></ResponsiveContainer>:<p className="muted">No history reported for this period.</p>}</Card></div>
 <Modal open={run} onClose={()=>setRun(false)} title="Run a Proxmox task"><p className="muted">Choose an operation. Its form submits to Proxmox and returns a task ID.</p><div className="header-actions"><button className="btn primary" onClick={()=>navigate('/proxmox?action=Create%20VM')}>Create VM</button><button className="btn secondary" onClick={()=>navigate('/proxmox?action=Create%20CT')}>Create Container</button><button className="btn secondary" onClick={()=>navigate('/backups?action=Run%20Backup')}>Run Backup</button></div></Modal>
 </section>;
}
