import {useEffect,useMemo,useState} from 'react';
import {Database,HardDrive,Folder,Search,RefreshCw,Plus,ShieldCheck,ExternalLink} from 'lucide-react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';
import {useApi} from '../hooks';
import {confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(v:any)=>v==null?'Unavailable':`${(v/(v>=1024**4?1024**4:1024**3)).toFixed(1)} ${v>=1024**4?'TiB':'GiB'}`;
const colors=['#3985ff','#a855f7','#1dd59c','#ffac33','#22b8e4'];
const total=(rows:any[],key:string)=>rows.length&&rows.every(r=>typeof r[key]==='number')?rows.reduce((n,r)=>n+r[key],0):null;
// Shared storage has one cluster capacity; local stores remain distinct per node.
const distinct=(rows:any[])=>rows.filter((r,i)=>r.shared!==true||rows.findIndex(s=>s.shared===true&&s.name===r.name)===i);
export default function ProxmoxStorage({role,clusterUrl}:{role?:string;clusterUrl?:string}){
 const live=useApi<any>('/proxmox/storage',null),rows=live.data?.resources||[],admin=['admin','owner'].includes(role||'');
 const [search,setSearch]=useState(''),[node,setNode]=useState('all'),[type,setType]=useState('all'),[selected,setSelected]=useState(''),[period,setPeriod]=useState('day'),[modal,setModal]=useState(false),[addType,setAddType]=useState('dir'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const filtered=useMemo(()=>rows.filter((r:any)=>(node==='all'||r.node===node)&&(type==='all'||r.type===type)&&`${r.name} ${r.node} ${r.type}`.toLowerCase().includes(search.toLowerCase())),[rows,node,type,search]);
 useEffect(()=>{if(!rows.some((r:any)=>r.id===selected))setSelected(rows[0]?.id||'');},[rows,selected]);
 const current=rows.find((r:any)=>r.id===selected),unique=distinct(rows),local=unique.filter((r:any)=>r.shared===false),shared=unique.filter((r:any)=>r.shared===true);
 const add=(kind:string)=>{setAddType(kind);setError('');setModal(true);};
 const create=async(e:any)=>{e.preventDefault();setBusy(true);setError('');try{const body=Object.fromEntries(new FormData(e.currentTarget));const result:any=await confirmedApi('/proxmox/storage',{method:'POST',body:JSON.stringify({...body,type:addType})});setMessage(result.message);setModal(false);await live.refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const toggle=async()=>{if(!current)return;setBusy(true);setError('');try{await confirmedApi(`/proxmox/storage/${encodeURIComponent(current.name)}/enabled`,{method:'PUT',body:JSON.stringify({enabled:current.status==='disabled'})});setMessage('Storage configuration updated.');await live.refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const offline=rows.filter((r:any)=>r.status==='offline').length,warnings=rows.filter((r:any)=>r.usage>=80).length,healthy=rows.filter((r:any)=>r.status==='online'&&r.usage!=null&&r.usage<80).length;
 return <section className="vm-manager pve-storage"><div className="vm-title"><div><h2>Storage</h2><p>Manage storage resources and monitor capacity across your Proxmox cluster.</p></div><div><button className="btn secondary" disabled={live.loading} onClick={live.refresh}><RefreshCw size={14}/>Refresh</button>{admin&&<button className="btn primary" onClick={()=>add('dir')}><Plus size={14}/>Add Storage</button>}</div></div>
 {(live.error||error)&&<p role="alert" className="login-error">{error||live.error}</p>}{message&&<p role="status" className="vm-message">{message}</p>}
 <div className="vm-stats">{[[Database,'Total Storage',unique],[HardDrive,'Local Storage',local],[Database,'Shared Storage',shared]].map(([Icon,label,list]:any)=><div className="vm-stat" key={label}><Icon size={25}/><div><small>{label}</small><strong>{bytes(total(list,'capacity'))}</strong><span>{bytes(total(list,'used'))} used</span></div></div>)}<div className="vm-stat"><Folder size={25}/><div><small>Storage Resources</small><strong>{live.data?unique.length:'—'}</strong><span>{rows.filter((r:any)=>r.status==='online').length} online node entries</span></div></div></div>
 <div className="storage-workspace"><div className="storage-main"><Card className="vm-list-card"><div className="widget-title"><div><h3>Storage Resources</h3><small className="muted">Select a storage resource to inspect its contents and history.</small></div></div><div className="vm-filters"><label className="vm-search"><Search size={14}/><input aria-label="Search storage" placeholder="Search storage…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Storage type" value={type} onChange={e=>setType(e.target.value)}><option value="all">All Types</option>{Array.from(new Set(rows.map((r:any)=>r.type))).map((value:any)=><option key={value}>{value}</option>)}</select><select aria-label="Storage node" value={node} onChange={e=>setNode(e.target.value)}><option value="all">All Nodes</option>{Array.from(new Set(rows.map((r:any)=>r.node))).map((value:any)=><option key={value}>{value}</option>)}</select></div><div className="table-wrap"><table className="storage-table"><thead><tr>{['Name','Type','Node','Total','Used','Available','Usage','Status','Actions'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((r:any)=><tr key={r.id} className={selected===r.id?'selected':''} onClick={()=>setSelected(r.id)}><td><b>{r.name}</b>{r.shared===true&&<small className="storage-shared">Shared</small>}</td><td>{r.type}</td><td>{r.node}</td><td>{bytes(r.capacity)}</td><td>{bytes(r.used)}</td><td>{bytes(r.available)}</td><td><Usage value={r.usage}/></td><td><Badge tone={r.status==='online'?'green':r.status==='offline'?'red':'gray'}>{r.status}</Badge></td><td><button className="btn ghost" aria-label={`Inspect ${r.name} on ${r.node}`} onClick={()=>setSelected(r.id)}>View</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="vm-empty">{live.loading?'Loading live storage…':live.error?'Storage could not be loaded. Check the connection and token permissions.':'No storage resources match these filters.'}</p>}</Card>
 {admin&&<Card><h3>Quick Actions</h3><div className="storage-quick">{[['dir','Directory'],['lvm','LVM'],['lvmthin','LVM-Thin'],['nfs','NFS'],['iscsi','iSCSI'],['rbd','Ceph RBD'],['cephfs','CephFS']].map(([value,label])=><button className="btn secondary" key={value} onClick={()=>add(value)}><Plus size={14}/>{label}</button>)}</div></Card>}
 {current&&<StorageDetail key={current.id} current={current} period={period} admin={admin} clusterUrl={clusterUrl} busy={busy} toggle={toggle}/>}
 </div><div className="storage-side">{current&&<StorageChart key={`${current.id}-${period}`} current={current} period={period} setPeriod={setPeriod}/>}
 <Card><h3>Storage Distribution</h3>{unique.some((r:any)=>r.capacity>0)?<><ResponsiveContainer width="100%" height={180}><PieChart><Pie data={unique.filter((r:any)=>r.capacity>0)} dataKey="capacity" nameKey="id" innerRadius={48} outerRadius={73} isAnimationActive={false}>{unique.filter((r:any)=>r.capacity>0).map((r:any,i:number)=><Cell key={r.id} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any)=>bytes(v)}/></PieChart></ResponsiveContainer><div className="storage-legend">{unique.map((r:any,i:number)=><button key={r.id} onClick={()=>setSelected(r.id)}><i style={{background:colors[i%colors.length]}}/><span>{r.shared?r.name:`${r.name} (${r.node})`}</span><b>{bytes(r.capacity)}</b></button>)}</div></>:<p className="muted">Capacity readings unavailable.</p>}<small className="muted">Shared resources counted once. Different storage IDs can still refer to the same physical disks.</small></Card>
 <Card><div className="widget-title"><h3>Storage Health</h3><ShieldCheck size={21}/></div><div className="storage-health"><span><b>{offline}</b>Offline</span><span><b>{warnings}</b>≥80% used</span><span><b>{healthy}</b>Online, below 80%</span></div><small className="muted">Based on availability and reported capacity; not a disk integrity test.</small>{!!live.data?.errors?.length&&<details><summary>{live.data.errors.length} readings unavailable</summary>{live.data.errors.map((e:string)=><p key={e}>{e}</p>)}</details>}</Card>
 <Card><h3>Top Storage Usage</h3>{[...unique].filter((r:any)=>r.usage!=null).sort((a:any,b:any)=>b.usage-a.usage).slice(0,5).map((r:any)=><button className="storage-top" key={r.id} onClick={()=>setSelected(r.id)}><span>{r.name} ({r.node})</span><Usage value={r.usage}/></button>)}</Card></div></div>
 <Modal open={modal} title="Add Proxmox Storage" onClose={()=>!busy&&setModal(false)}><form className="form-grid vm-form" onSubmit={create}><label>Type<select value={addType} onChange={e=>setAddType(e.target.value)}>{[['dir','Directory'],['lvm','LVM'],['lvmthin','LVM-Thin'],['nfs','NFS'],['iscsi','iSCSI'],['rbd','Ceph RBD'],['cephfs','CephFS']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Storage ID<input name="storage" pattern="[A-Za-z][A-Za-z0-9_-]*" required/></label>{({dir:['path'],lvm:['vgname'],lvmthin:['vgname','thinpool'],nfs:['server','export'],iscsi:['portal','target'],rbd:['pool'],cephfs:[]} as Record<string,string[]>)[addType].map(key=><label key={`${addType}-${key}`}>{({path:'Absolute directory path',vgname:'Existing volume group',thinpool:'Existing thin pool',server:'NFS server',export:'NFS export path',portal:'iSCSI portal',target:'iSCSI target IQN',pool:'Existing Ceph pool'} as any)[key]}<input name={key} required/></label>)}<label className="cluster-wide">Restrict to nodes (optional)<input name="nodes" placeholder="node01,node02"/></label><p className="muted cluster-wide">Registers an existing storage resource in Proxmox. LVM groups, thin pools and Ceph pools must already exist. Proxmox validates the configuration and permissions.</p>{error&&<p className="login-error cluster-wide">{error}</p>}<div className="modal-actions"><button type="button" className="btn secondary" disabled={busy} onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':'Add Storage'}</button></div></form></Modal></section>;
}
function Usage({value}:{value:any}){return <div className="storage-usage"><span>{value==null?'Unknown':`${Math.round(value)}%`}</span><i><b style={{width:`${Math.max(0,Math.min(100,value||0))}%`,background:value>=90?'#f05265':value>=80?'#ffac33':'#1dd59c'}}/></i></div>}
function StorageChart({current,period,setPeriod}:{current:any;period:string;setPeriod:(s:string)=>void}){
 const detail=useApi<any>(`/proxmox/storage/${encodeURIComponent(current.node)}/${encodeURIComponent(current.name)}?timeframe=${period}`,null);
 const history=(detail.data?.history||[]).map((p:any)=>({time:p.time*1000,usage:p.total>0&&p.used!=null?p.used/p.total*100:null}));
 return <Card><div className="widget-title"><h3>Storage Usage History</h3><select aria-label="Storage history period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="hour">Last hour</option><option value="day">Last day</option><option value="week">Last week</option><option value="month">Last month</option></select></div><small className="muted">{current.node} / {current.name}</small>{history.some((p:any)=>p.usage!=null)?<ResponsiveContainer width="100%" height={180}><AreaChart data={history}><XAxis dataKey="time" tickFormatter={v=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} tick={{fontSize:9}}/><YAxis domain={[0,100]} width={30} tick={{fontSize:9}}/><Tooltip labelFormatter={v=>new Date(v).toLocaleString()} formatter={(v:any)=>`${Number(v).toFixed(1)}%`}/><Area dataKey="usage" stroke="#3985ff" fill="#3985ff33" isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer>:<p className="vm-empty">{detail.loading?'Loading history…':'No storage history reported.'}</p>}{detail.error&&<p role="alert">{detail.error}</p>}</Card>;
}
function StorageDetail({current,period,admin,clusterUrl,busy,toggle}:{current:any;period:string;admin:boolean;clusterUrl?:string;busy:boolean;toggle:()=>void}){
 const detail=useApi<any>(`/proxmox/storage/${encodeURIComponent(current.node)}/${encodeURIComponent(current.name)}?timeframe=${period}`,null);
 const open=()=>{if(clusterUrl){const url=new URL(clusterUrl);url.hash=`v1:0:=${current.node}/storage/${current.name}`;window.open(url.toString(),'_blank','noopener,noreferrer');}};
 return <Card><div className="widget-title"><h3>{current.name} · {current.node}</h3><div className="storage-quick"><button className="btn secondary" disabled={!clusterUrl} onClick={open}><ExternalLink size={13}/>Open Proxmox</button>{admin&&<button className="btn secondary" disabled={busy} onClick={toggle}>{current.status==='disabled'?'Enable':'Disable'} Storage</button>}</div></div><small className="muted">Enable/disable changes this storage ID across its configured nodes.</small><h4>Stored Content</h4><div className="table-wrap"><table><thead><tr><th>Volume</th><th>Content</th><th>Size</th></tr></thead><tbody>{(Array.isArray(detail.data?.content)?detail.data.content:[]).map((r:any)=><tr key={r.volid}><td>{r.volid}</td><td>{r.content}</td><td>{bytes(r.size)}</td></tr>)}</tbody></table></div>{!detail.data?.content?.length&&<p className="muted">{detail.loading?'Loading contents…':'No contents reported.'}</p>}{detail.error&&<p role="alert">{detail.error}</p>}{!!detail.data?.errors?.length&&<details><summary>Unavailable details</summary>{detail.data.errors.map((e:string)=><p key={e}>{e}</p>)}</details>}</Card>;
}
