import {useEffect,useState,ReactNode} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {Server,Monitor,Box,Cpu,MemoryStick,HardDrive,ShieldCheck,RefreshCw,Plus,Terminal,Archive,ListChecks,ExternalLink} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,PieChart,Pie,Cell,Tooltip} from 'recharts';
import {useApi} from '../hooks';
import {api} from '../api';
import {ClusterConnection} from '../components/ClusterConnection';
import {Card,Badge} from '../components/UI';
import {DataTable} from '../components/DataTable';
import ClusterNodes from './ClusterNodes';
const tabs=['Overview','Nodes','Virtual Machines','LXC Containers','Storage','Networks','Tasks & Logs','Backup','Settings','Node Services'];
const bytes=(v:any)=>v==null?'Unknown':Number(v)>=1024**4?`${(v/1024**4).toFixed(1)} TiB`:`${(v/1024**3).toFixed(1)} GiB`;
const pct=(v:any)=>v==null?'Unknown':`${v}%`;
const duration=(v:any)=>v==null?'Unknown':`${Math.floor(v/86400)}d ${Math.floor(v%86400/3600)}h ${Math.floor(v%3600/60)}m`;
const sum=(rows:any[],key:string)=>rows.length&&rows.every(r=>typeof r[key]==='number')?rows.reduce((n,r)=>n+r[key],0):null;
const colors=['#3b82f6','#8b5cf6','#22c55e','#f59e0b','#14b8a6'];
export default function ProxmoxOverview({management}:{management:(view:string)=>ReactNode}){
 const live=useApi<any>('/proxmox',null),tasks=useApi<any>('/tasks',null),history=useApi<any>('/dashboard',null),network=useApi<any>('/network',null),session=useApi<any>('/auth/me',null);
 const [view,setView]=useState('Overview'),[hours,setHours]=useState('24'),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[taskResult,setTaskResult]=useState<any>(null);
 const [params]=useSearchParams(),navigate=useNavigate();
 useEffect(()=>{if(params.get('action')==='Create VM')setView('Virtual Machines');if(params.get('action')==='Create CT')setView('LXC Containers');},[params.get('action')]);
 const data=live.data,nodes=data?.nodes||[],vms=data?.vms||[],lxc=data?.lxc||[],storage=data?.storage||[],errors=data?.errors||[],services=data?.nodeServices||[];
 const cluster=data?.clusterStatus?.find((r:any)=>r.type==='cluster'),online=nodes.filter((n:any)=>n.status==='online').length;
 const totalCores=sum(nodes,'cores'),usedMemory=sum(nodes,'memoryBytes'),totalMemory=sum(nodes,'memoryTotal');
 const totalStorage=sum(storage,'capacity'),usedStorage=sum(storage,'used');
 const cpuUsed=nodes.length&&nodes.every((n:any)=>n.cores!=null&&n.cpu!=null)?nodes.reduce((n:number,r:any)=>n+r.cores*r.cpu/100,0):null;
 const health=!data?'Unknown':errors.length?'Limited access':nodes.some((n:any)=>n.status!=='online')||cluster?.quorate===0||cluster?.quorate===false?'Needs attention':'Online';
 const recent=(tasks.data?.proxmox||[]).filter((t:any)=>t.starttime>=Date.now()/1000-Number(hours)*3600).sort((a:any,b:any)=>b.starttime-a.starttime);
 const permissionErrors=errors.some((e:string)=>e.includes('403'));
 const create=(kind:string)=>{setView(kind==='Create VM'?'Virtual Machines':'LXC Containers');navigate(`/proxmox?action=${encodeURIComponent(kind)}`);};
 const operator=['operator','admin','owner'].includes(session.data?.user?.role);
 const refresh=async()=>{setBusy(true);setFailure('');try{live.setData(await api('/proxmox?refresh=1'));await Promise.all([tasks.refresh(),history.refresh(),network.refresh()]);}catch(e:any){setFailure(e.message);}finally{setBusy(false);}};
 const inspectTask=async(t:any,log=false)=>{setFailure('');try{setTaskResult(await api(`/tasks/${encodeURIComponent(t.node)}/${encodeURIComponent(t.upid)}${log?'/log':''}`));}catch(e:any){setFailure(e.message);}};
 const nodeTable=(rows:any[])=><DataTable rows={rows} columns={[{key:'name',label:'Node name',render:(r:any)=><span className="pve-node-name"><Server size={21}/><span><b>{r.name}</b><small>{r.ip||'IP not reported'}</small></span></span>},{key:'status',label:'Status',render:(r:any)=><Badge tone={r.status==='online'?'green':'red'}>{r.status||'Unknown'}</Badge>},{key:'cpu',label:'CPU usage',render:(r:any)=><div className="pve-measure"><span>{pct(r.cpu)}</span><Spark rows={history.data?.metrics||[]} node={r.name} metric="cpu" hours={hours} color="#3b82f6"/></div>},{key:'memoryPercent',label:'Memory usage',render:(r:any)=><div className="pve-measure"><span>{pct(r.memoryPercent)}</span><Spark rows={history.data?.metrics||[]} node={r.name} metric="memory" hours={hours} color="#a855f7"/></div>},{key:'uptime',label:'Uptime',render:(r:any)=>duration(r.uptime)},{key:'inspect',label:'Details',render:()=> <button className="btn ghost" onClick={()=>setView('Node Services')}>Services</button>}]}/>;
 const taskTable=(rows:any[])=><DataTable rows={rows} columns={[{key:'upid',label:'Task ID',render:(r:any)=><button title={r.upid} className="pve-text-button" onClick={()=>inspectTask(r)}>{r.upid?.slice(0,27)}…</button>},{key:'node',label:'Node'},{key:'type',label:'Type'},{key:'id',label:'Guest ID'},{key:'status',label:'Status',render:(r:any)=><Badge tone={r.status==='OK'?'green':r.status?'red':'blue'}>{r.status||(r.endtime?'Unknown':'Running')}</Badge>},{key:'starttime',label:'Start time',render:(r:any)=>new Date(r.starttime*1000).toLocaleString()},{key:'duration',label:'Duration',render:(r:any)=>r.endtime?`${r.endtime-r.starttime}s`:'In progress'},{key:'logs',label:'Logs',render:(r:any)=><button className="btn ghost" onClick={()=>inspectTask(r,true)}>View log</button>}]}/>;
 return <div className="pve-page"><div className="pve-breadcrumb">Proxmox <span>›</span> {data?.cluster?.name||'Cluster'}</div>
 <div className="pve-heading"><div><h1>Proxmox Cluster: {data?.cluster?.name||'Not connected'} <Badge tone={health==='Online'?'green':health==='Unknown'?'gray':'yellow'}>{health}</Badge></h1><p>Manage your nodes, virtual machines and containers.</p></div><div className="pve-heading-actions"><a className="btn secondary" href="https://pve.proxmox.com/pve-docs/" target="_blank" rel="noreferrer">Documentation <ExternalLink size={13}/></a>{session.data?.user?.role==='owner'&&<ClusterConnection compact label="Add / Edit Cluster"/>}{operator&&<><button className="btn primary" onClick={()=>create('Create VM')}><Plus size={15}/> Create VM</button><button className="btn secondary" onClick={()=>create('Create CT')}>Create CT</button></>}</div></div>
 <div className="pve-tabbar"><div role="tablist" aria-label="Proxmox sections">{tabs.map(t=><button key={t} role="tab" aria-selected={view===t} onClick={()=>setView(t)}>{t}</button>)}</div><select aria-label="Task history period" value={hours} onChange={e=>setHours(e.target.value)}><option value="1">Last hour</option><option value="24">Last 24 hours</option><option value="168">Last 7 days</option></select><button aria-label="Refresh Proxmox" className="btn secondary" disabled={busy} onClick={refresh}><RefreshCw size={15}/></button></div>
 {(live.error||failure)&&<p className="login-error" role="alert">{failure||live.error}</p>}
 {!!errors.length&&<details className="pve-errors"><summary>{errors.length} unavailable API readings{permissionErrors?' — Proxmox permissions need attention':''}</summary>{permissionErrors&&<p>In Proxmox → Datacenter → Permissions, grant PVEAuditor at / with Propagate enabled to both the user and its privilege-separated API token. This provides read access. Management actions require their own additional privileges.</p>}<ul>{errors.map((e:string)=><li key={e}>{e}</li>)}</ul></details>}
 {view==='Overview'?<><div className="pve-stats">{[
 ['Total Nodes',data?nodes.length:'—',`${online} Online`,Server,'Nodes'],['Total VMs',data?vms.length:'—',`${vms.filter((v:any)=>v.status==='running').length} Running`,Monitor,'Virtual Machines'],['Total LXC',data?lxc.length:'—',`${lxc.filter((v:any)=>v.status==='running').length} Running`,Box,'LXC Containers'],['Total CPU',cpuUsed==null?'Unknown':cpuUsed.toFixed(1),totalCores==null?'Core capacity unknown':`of ${totalCores} cores in use`,Cpu,'Nodes'],['Total Memory',bytes(usedMemory),`of ${bytes(totalMemory)}`,MemoryStick,'Nodes'],['Total Storage',bytes(usedStorage),'Per-node entries; shared pools may repeat',HardDrive,'Storage']
 ].map(([label,value,sub,Icon,target]:any)=><button className="pve-stat" key={label} onClick={()=>setView(target)}><div><small>{label}</small><strong>{value}</strong><span>{sub}</span></div><i><Icon size={25}/></i></button>)}</div>
 <div className="pve-grid"><Card className="pve-wide"><WidgetHeader title="Cluster Nodes" action="View All Nodes" onClick={()=>setView('Nodes')}/>{nodes.length?nodeTable(nodes.slice(0,5)):<p className="muted">{live.loading?'Loading nodes…':'Connect a cluster through Cluster Settings to load its nodes.'}</p>}</Card>
 <Card><WidgetHeader title="Cluster Health"/><div className="pve-health"><ShieldCheck size={39}/><div><b>{health}</b><small>Based on available API readings</small></div></div><div className="pve-health-row"><span>Quorum status</span><b>{cluster?.quorate==null?'Not reported':cluster.quorate?'Quorate':'Not quorate'}</b></div><div className="pve-health-row"><span>Online nodes</span><b>{data?`${online}/${nodes.length}`:'Unknown'}</b></div>{services.slice(0,4).map((s:any)=><div key={s.id} className="pve-health-row"><span>{s.node}: {s.name}</span><b>{s.status}</b></div>)}<button className="pve-text-button" onClick={()=>setView('Node Services')}>View Full Health →</button></Card>
 <Card className="pve-wide"><WidgetHeader title="Recent Tasks" action="View All Tasks" onClick={()=>setView('Tasks & Logs')}/>{recent.length?taskTable(recent.slice(0,5)):<p className="muted">{tasks.error||'No tasks reported during this period.'}</p>}</Card>
 <Card><WidgetHeader title="Resource Summary"/>{usedStorage!=null&&usedStorage>0?<div className="pve-storage-chart"><ResponsiveContainer width="100%" height={155}><PieChart><Pie data={storage.filter((s:any)=>s.used>0)} dataKey="used" nameKey="name" innerRadius={48} outerRadius={70} isAnimationActive={false}>{storage.filter((s:any)=>s.used>0).map((s:any,i:number)=><Cell key={s.id} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any)=>bytes(v)}/></PieChart></ResponsiveContainer><b>{bytes(usedStorage)}</b></div>:<p className="muted">Storage measurements unavailable.</p>}<div className="pve-storage-list">{storage.slice(0,5).map((s:any,i:number)=><button key={s.id} onClick={()=>setView('Storage')}><i style={{background:colors[i%colors.length]}}/><span>{s.node}/{s.name}</span><b>{bytes(s.used)} ({pct(s.usage)})</b></button>)}</div><small className="muted">Per-node usage; shared storage entries may represent the same pool. Capacity: {bytes(totalStorage)}.</small></Card></div>
 <Card className="pve-quick"><WidgetHeader title="Quick Actions"/><div>{[['Create VM','Create an empty virtual machine',Monitor,()=>create('Create VM'),!operator],['Create CT','Create an unprivileged container',Box,()=>create('Create CT'),!operator],['Backup Guest','Run a VM or container backup',Archive,()=>navigate('/backups?action=Run%20Backup'),!operator],['Cluster Backup','Manage real backup schedules',HardDrive,()=>navigate('/backups'),false],['Shell Access','Open Proxmox web console',Terminal,()=>window.open(data.cluster.url,'_blank','noopener,noreferrer'),!data?.cluster?.url],['Task Viewer','Inspect task status and logs',ListChecks,()=>setView('Tasks & Logs'),false]].map(([label,sub,Icon,click,disabled]:any)=><button key={label} disabled={disabled} onClick={click}><Icon size={24}/><span><b>{label}</b><small>{sub}</small></span></button>)}</div></Card></>
 :view==='Nodes'?<ClusterNodes data={data} metrics={history.data?.metrics||[]} tasks={recent} network={network.data} hours={hours} role={session.data?.user?.role} refresh={refresh}/>
 :view==='Settings'?<Card><h3>Cluster Settings</h3><p className="muted">One active cluster is supported. Editing replaces its connection; nodes and guests are discovered automatically.</p><ClusterConnection compact/>{data?.cluster?.url&&<a className="btn secondary" href={data.cluster.url} target="_blank" rel="noreferrer">Open Proxmox</a>}</Card>
 :view==='Tasks & Logs'?<Card><WidgetHeader title="Tasks & Logs"/>{tasks.error&&<p role="alert">{tasks.error}</p>}{taskTable(recent)}</Card>
 :view==='Backup'?<Card><h3>Cluster Backups</h3><p className="muted">Use provider-managed schedules and inspect submitted backup tasks.</p><Link className="btn primary" to="/backups">View Backup Jobs</Link><Link className="btn secondary" to="/backups?action=Run%20Backup">Run Guest Backup</Link><Link className="btn secondary" to="/schedules">Schedules</Link></Card>
 :view==='Networks'?<Card><WidgetHeader title="Node Networks"/>{network.error&&<p role="alert">{network.error}</p>}<DataTable rows={(network.data?.interfaces||[]).filter((r:any)=>r.provider==='proxmox')} columns={['node','name','address','type','active'].map(key=>({key,label:key}))}/>{network.data?.errors?.length>0&&<details><summary>Unavailable network readings</summary><ul>{network.data.errors.map((e:string)=><li key={e}>{e}</li>)}</ul></details>}</Card>
 :<div className="pve-management" key={view}>{management(view)}</div>}
 {taskResult&&<Card><div className="widget-title"><h3>Task Result</h3><button className="btn ghost" onClick={()=>setTaskResult(null)}>Close</button></div><pre className="live-output">{JSON.stringify(taskResult,null,2)}</pre></Card>}
 <footer className="pve-footer"><span>{data?.sampledAt?`Last measurement: ${new Date(data.sampledAt).toLocaleString()}`:'Waiting for cluster measurements'}</span><ClusterConnection compact/></footer></div>;
}
function WidgetHeader({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="widget-title"><h3>{title}</h3>{action&&<button className="pve-text-button" onClick={onClick}>{action} →</button>}</div>;}
function Spark({rows,node,metric,hours,color}:{rows:any[];node:string;metric:string;hours:string;color:string}){const points=rows.filter(r=>new Date(r.time).getTime()>Date.now()-Number(hours)*3600000).map(r=>({value:r.nodes?.find((n:any)=>n.name===node)?.[metric]??null}));return points.some(r=>r.value!=null)?<div className="pve-spark"><ResponsiveContainer width="100%" height={30}><AreaChart data={points}><Area dataKey="value" stroke={color} fill={`${color}18`} strokeWidth={1.5} isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div>:null;}
