import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Settings,Link as LinkIcon,Bell,Shield,Calendar,Palette,Server,Download,Upload,RotateCcw} from 'lucide-react';
import {useApi} from '../hooks';
import {api} from '../api';
import {Card,Badge} from '../components/UI';
import {ClusterConnection} from '../components/ClusterConnection';
import UpdateButton from '../components/UpdateButton';
import {loadAppearance,saveAppearance,appearanceDefaults} from '../appearance';
export default function ProxmoxSettings({role}:{role?:string}){
 const live=useApi<any>('/settings',null),navigate=useNavigate(),admin=['owner','admin'].includes(role||''),owner=role==='owner';
 const [category,setCategory]=useState('General'),[appearance,setAppearance]=useState(loadAppearance),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const data=live.data,system=data?.system;
 const put=async(values:any)=>{setBusy(true);setError('');try{await api('/settings',{method:'PUT',body:JSON.stringify(values)});setMessage('Settings saved.');await live.refresh();window.dispatchEvent(new Event('homecloud-settings'));}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const exportSettings=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify({schema:1,settings:data.settings,appearance},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='homecloud-settings.json';a.click();URL.revokeObjectURL(url);};
 const importSettings=async(e:any)=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>16384)throw new Error('Settings file must be smaller than 16 KiB.');const value=JSON.parse(await file.text());if(value.schema!==1||!value.settings)throw new Error('Choose a HomeCloud settings export.');await put({siteName:value.settings.siteName,description:value.settings.description,refresh:value.settings.refresh});}catch(e:any){setError(e.message);}finally{e.target.value='';}};
 const shown=(name:string)=>category==='General'||category===name;
 return <section className="pve-settings"><div className="page-header"><div><h2>Settings</h2><p className="muted">Configure HomeCloud Hub, its cluster connection and display preferences.</p></div><button className="btn secondary" disabled={live.loading} onClick={live.refresh}>Refresh Status</button></div>
 <div className="settings-categories" role="tablist" aria-label="Settings categories">{[['General','System configuration',Settings],['Integrations','Connected services',LinkIcon],['Notifications','Alerts and rules',Bell],['Security','Access and auditing',Shield],['Automation','Backup schedules',Calendar],['Appearance','Display preferences',Palette]].map(([name,sub,Icon]:any)=><button role="tab" aria-selected={category===name} className={category===name?'selected':''} key={name} onClick={()=>setCategory(name)}><Icon size={24}/><span><b>{name}</b><small>{sub}</small></span></button>)}</div>
 {(live.error||error)&&<p className="error" role="alert">{live.error||error}</p>}{message&&<p role="status">{message}</p>}{!data&&<p className="muted">{live.loading?'Loading settings...':'Settings unavailable.'}</p>}
 <div className="settings-grid">
 {shown('General')&&<><Card><h3><Server size={19}/> System Information</h3><p className="muted">HomeCloud Hub {system?.version||'Unknown'} · API runtime</p><dl className="task-details">{Object.entries({Hostname:system?.hostname||'Unknown',Platform:system?`${system.platform} ${system.release}`:'Unknown','Node.js':system?.runtime||'Unknown','API process uptime':system?`${Math.floor(system.uptime/3600)}h ${Math.floor(system.uptime%3600/60)}m`:'Unknown',Timezone:system?.timezone||'Unknown','Notification delivery':data?.capabilities?.notifications||'Unknown'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><small className="muted">Runtime details describe the API container; VM and Docker host versions are not inferred.</small>{owner&&<div className="settings-update"><UpdateButton/></div>}</Card>
 <Card><h3><Settings size={19}/> General Settings</h3>{data&&<form key={JSON.stringify(data.settings)} onSubmit={e=>{e.preventDefault();put(Object.fromEntries(new FormData(e.currentTarget)));}}><label>System name<input name="siteName" required maxLength={120} defaultValue={data.settings.siteName}/></label><label>Description<textarea name="description" maxLength={500} defaultValue={data.settings.description}/></label><label>Page refresh interval (seconds)<input name="refresh" type="number" min={15} max={300} required defaultValue={data.settings.refresh}/></label><button className="btn primary" disabled={!admin||busy}>Save Changes</button></form>}</Card></>}
 {shown('Appearance')&&<Card><h3><Palette size={19}/> Appearance</h3><p className="muted">Preferences are saved in this browser.</p><label>Accent color<input aria-label="Accent color" type="color" value={appearance.accent} onChange={e=>setAppearance({...appearance,accent:e.target.value})}/></label><label>Dashboard density<select value={appearance.density} onChange={e=>setAppearance({...appearance,density:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="settings-switch"><input type="checkbox" checked={appearance.animations} onChange={e=>setAppearance({...appearance,animations:e.target.checked})}/> Enable animations</label><button className="btn primary" onClick={()=>{saveAppearance(appearance);setMessage('Display preferences saved for this browser.');}}>Save Appearance</button><button className="btn secondary" onClick={()=>{setAppearance(appearanceDefaults);saveAppearance(appearanceDefaults);}}>Reset Appearance</button></Card>}
 {shown('Security')&&<Card><h3><Shield size={19}/> Security Settings</h3><p className="muted">Role permissions protect management actions. Sensitive operations require confirmation and are audited.</p><dl className="task-details"><div><dt>Your role</dt><dd>{role||'Unknown'}</dd></div><div><dt>Audit logging</dt><dd>Enabled</dd></div><div><dt>Two-factor login</dt><dd>{data?.capabilities?.twoFactor?'Available':'Not implemented'}</dd></div></dl><div className="header-actions"><button className="btn secondary" disabled={!admin} onClick={()=>navigate('/users')}>Manage Users</button><button className="btn secondary" onClick={()=>navigate('/audit')}>View Audit Logs</button></div></Card>}
 {shown('Notifications')&&<Card><h3><Bell size={19}/> Notification Settings</h3><p className="muted">Alerts appear inside HomeCloud Hub. Configure thresholds and inspect active alerts through the monitoring tools.</p><div className="header-actions"><button className="btn secondary" onClick={()=>navigate('/alerts')}>Manage Alert Rules</button><button className="btn secondary" onClick={()=>navigate('/monitoring')}>View Monitoring</button></div><small className="muted">SMTP, Discord and Telegram delivery are not configured by this application.</small></Card>}
 {shown('Integrations')&&<Card><h3><LinkIcon size={19}/> Integration Status</h3>{data?.integrations?.map((s:any)=><div className="settings-integration" key={s.name}><b>{s.name}</b><Badge tone={s.status==='reachable'?'green':s.status==='not-configured'?'gray':'yellow'}>{s.status}</Badge>{s.name==='proxmox'&&owner?<ClusterConnection compact label="Configure"/>:<button className="btn secondary small" onClick={()=>navigate(({docker:'/docker',truenas:'/storage',opnsense:'/network',tailscale:'/vpn'} as any)[s.provider||s.name]||'/monitoring')}>View</button>}</div>)}<p className="muted">Configure Proxmox here. Other integration credentials are configured on the Ubuntu server using <code>sudo homecloud config</code>, followed by <code>sudo homecloud restart</code>.</p></Card>}
 {shown('Automation')&&<Card><h3><Calendar size={19}/> Automation</h3><p className="muted">Backup schedules and retention rules execute through their connected providers.</p><div className="header-actions"><button className="btn secondary" onClick={()=>navigate('/schedules')}>Manage Schedules</button><button className="btn secondary" onClick={()=>navigate('/retention')}>Retention Policies</button><button className="btn secondary" onClick={()=>navigate('/backups')}>Backup Jobs</button></div></Card>}
 </div><div className="settings-footer"><Card><h3><RotateCcw size={19}/> Reset General Settings</h3><p className="muted">Restore the site name, description and refresh interval to their defaults.</p><button className="btn secondary" disabled={!admin||busy} onClick={()=>put({siteName:'HomeCloud Hub',description:'Homelab management',refresh:30})}>Reset to Defaults</button></Card><Card><h3>Export &amp; Import</h3><p className="muted">Export general settings and browser appearance. Import restores general settings. Connection credentials and accounts are excluded.</p><div className="header-actions"><button className="btn secondary" disabled={!data} onClick={exportSettings}><Download size={15}/> Export Settings</button><label className="btn secondary"><Upload size={15}/> Import Settings<input aria-label="Import settings file" type="file" accept="application/json,.json" disabled={!admin||busy} onChange={importSettings}/></label></div></Card></div></section>;
}
