import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Archive,CheckCircle,AlertTriangle,Database,Calendar,RefreshCw,Plus,Play,RotateCcw,ShieldCheck} from 'lucide-react';
import {PieChart,Pie,Cell,Tooltip,ResponsiveContainer} from 'recharts';
import {useApi} from '../hooks';
import {api} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(v:any)=>v==null?'Unknown':`${(v/(v>=1024**4?1024**4:1024**3)).toFixed(1)} ${v>=1024**4?'TiB':'GiB'}`;
const colors=['#3985ff','#1dd59c','#a855f7','#ffac33','#ef4444'];
export default function ProxmoxBackups({role,hours,onTasks,onStorage}:{role?:string;hours:string;onTasks:()=>void;onStorage:()=>void}){
 const live=useApi<any>('/backups',null),tasks=useApi<any>(`/proxmox/tasks?hours=${hours}`,null),stores=useApi<any>('/proxmox/storage',null),guests=useApi<any>('/proxmox',null),navigate=useNavigate();
 const [search,setSearch]=useState(''),[node,setNode]=useState('all'),[status,setStatus]=useState('all'),[view,setView]=useState('jobs'),[kind,setKind]=useState('all'),[page,setPage]=useState(0),[size,setSize]=useState(10),[modal,setModal]=useState<'run'|'schedule'|'policy'|null>(null),[current,setCurrent]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const admin=['owner','admin'].includes(role||''),operator=admin||role==='operator',jobs=live.data?.jobs||[],raw=live.data?.points||[],resources=stores.data?.resources||[];
 // The same shared archive can be visible from multiple cluster nodes.
 const points=raw.filter((p:any,i:number)=>raw.findIndex((s:any)=>s.storage===p.storage&&s.volid===p.volid&&(s.node===p.node||resources.some((r:any)=>r.node===p.node&&r.name===p.storage&&r.shared===true)&&resources.some((r:any)=>r.node===s.node&&r.name===s.storage&&r.shared===true)))===i);
 const backupTasks=(tasks.data?.tasks||[]).filter((t:any)=>t.type==='vzdump'),success=backupTasks.filter((t:any)=>t.status==='OK'),failed=backupTasks.filter((t:any)=>t.endtime&&t.status&&t.status!=='OK'),next=jobs.filter((j:any)=>j.enabled!==0&&j.enabled!==false&&j['next-run']).sort((a:any,b:any)=>a['next-run']-b['next-run'])[0];
 const total=points.length&&points.every((p:any)=>typeof p.size==='number')?points.reduce((s:number,p:any)=>s+p.size,0):points.length?null:live.data?0:null;
 const filtered=(view==='jobs'?jobs:points).filter((r:any)=>(node==='all'||r.node===node)&&(status==='all'||(view==='jobs'?(r.enabled===0||r.enabled===false?'disabled':'enabled'):(r.protected?'protected':'unprotected'))===status)&&(kind==='all'||r.type===kind)&&Object.values(r).join(' ').toLowerCase().includes(search.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/size)),actual=Math.min(page,pages-1),shown=filtered.slice(actual*size,(actual+1)*size);
 useEffect(()=>setPage(0),[search,node,status,view,kind,size]);
 const refresh=async()=>{await Promise.all([live.refresh(),tasks.refresh(),stores.refresh(),guests.refresh()]);};
 const runJob=async(j:any)=>{setBusy(true);setError('');try{const r=await api(`/backups/${encodeURIComponent(j.id)}/run`,{method:'POST'});setMessage(`Backup submitted: ${r.result?.task||'request accepted'}. Inspect Tasks & Logs for completion.`);await tasks.refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const toggle=async(j:any)=>{setBusy(true);try{await api(`/schedules/${encodeURIComponent(j.id)}/toggle`,{method:'POST'});await live.refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const submit=async(e:any)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{const r=await api(modal==='run'?'/proxmox/backup':'/backups',{method:'POST',body:JSON.stringify(body)});setMessage(modal==='run'?`Backup submitted: ${r.result?.task||'request accepted'}. Check Tasks & Logs.`:'Backup schedule saved in Proxmox.');setModal(null);await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const storageData=Object.entries(points.reduce((a:any,p:any)=>{if(typeof p.size==='number')a[p.storage]=(a[p.storage]||0)+p.size;return a;},{})).map(([name,value])=>({name,value}));
 const targets=resources.filter((r:any)=>String(r.content||'').split(',').includes('backup')).filter((r:any,i:number,a:any[])=>!r.shared||a.findIndex(s=>s.shared&&s.name===r.name)===i);
 const allGuests=[...(guests.data?.vms||[]),...(guests.data?.lxc||[])];
 return <section className="backup-manager"><div className="page-header"><div><h2>Backups</h2><p className="muted">Manage cluster backup jobs, archives and operations.</p></div><div className="header-actions"><button className="btn secondary" onClick={refresh} disabled={live.loading}><RefreshCw size={15}/> Refresh</button><button className="btn primary" disabled={!operator} onClick={()=>{setError('');setModal('run');}}><Plus size={15}/> Create Backup</button></div></div>
 {[live.error,tasks.error,stores.error,error,...(live.data?.errors||[]),...(tasks.data?.errors||[]),...(stores.data?.errors||[])].filter(Boolean).map((e:string,i:number)=><p className="error" role="alert" key={i}>{e}</p>)}{message&&<p role="status">{message}</p>}{tasks.data?.truncated?.length>0&&<p className="muted">Backup task counts use up to 500 returned tasks per node. Narrow the time range for more detail.</p>}
 <div className="backup-stats">{[[Archive,live.data?points.length:'Unknown','Backup Archives','Accessible stored archives'],[CheckCircle,tasks.data?success.length:'Unknown','Successful Tasks',`Last ${hours} hours · returned history`],[AlertTriangle,tasks.data?failed.length:'Unknown','Failed Tasks',`Last ${hours} hours · returned history`],[Database,bytes(total),'Total Backup Size','Known archive sizes'],[Calendar,next?new Date(next['next-run']*1000).toLocaleString():'Not reported','Next Scheduled',next?.comment||'From Proxmox scheduler']].map(([Icon,value,label,sub]:any)=><Card className="vm-stat" key={label}><span className="vm-stat-icon"><Icon size={24}/></span><div><small>{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div></Card>)}</div>
 <div className="backup-workspace"><Card className="vm-list-card"><div className="vm-toolbar"><h3>{view==='jobs'?'Backup Jobs':'Backup Archives'}</h3><select aria-label="Backup view" value={view} onChange={e=>{setView(e.target.value);setStatus('all');setKind('all');}}><option value="jobs">Jobs</option><option value="archives">Archives</option></select><input placeholder="Search backups..." aria-label="Search backups" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Backup node" value={node} onChange={e=>setNode(e.target.value)}><option value="all">All Nodes</option>{Array.from(new Set([...jobs,...points].map((r:any)=>r.node).filter(Boolean))).map((n:any)=><option key={n}>{n}</option>)}</select><select aria-label="Backup status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option>{(view==='jobs'?['enabled','disabled']:['protected','unprotected']).map(s=><option key={s}>{s}</option>)}</select>{view==='archives'&&<select aria-label="Archive type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All Types</option><option value="qemu">VM</option><option value="lxc">LXC</option></select>}</div>
 <div className="table-wrap"><table className="backup-table"><thead><tr>{(view==='jobs'?['Name / ID','Node','Guests','Target','Schedule','Status','Actions']:['Archive','Node','Type / Guest','Storage','Created','Size','Actions']).map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{shown.map((r:any)=>view==='jobs'?<tr key={r.id}><td><b>{r.comment||r.id}</b><small className="task-id" title={r.id}>{r.id}</small></td><td>{r.node||'All Nodes'}</td><td>{r.vmid|| (r.all?'All guests':r.pool||'Provider selection')}</td><td>{r.storage||'Default'}</td><td>{r.schedule||'Not reported'}</td><td><Badge tone={r.enabled===0||r.enabled===false?'gray':'green'}>{r.enabled===0||r.enabled===false?'Disabled':'Enabled'}</Badge></td><td><div className="header-actions"><button className="btn secondary small" disabled={!operator||busy||!r.node} title={!r.node?'Cluster-wide jobs run through the Proxmox scheduler':''} onClick={()=>runJob(r)}>Run</button><button className="btn secondary small" disabled={!admin||busy} onClick={()=>toggle(r)}>Toggle</button><button className="btn secondary small" onClick={()=>{setCurrent(r);setModal('policy');}}>Policy</button></div></td></tr>:<tr key={r.id}><td><span className="backup-archive" title={r.volid}>{r.volid}</span>{r.protected&&<Badge>Protected</Badge>}</td><td>{r.node}</td><td>{r.type==='qemu'?'VM':r.type==='lxc'?'LXC':r.type} {r.vmid||''}</td><td>{r.storage}</td><td>{r.created?new Date(r.created).toLocaleString():'Unknown'}</td><td>{bytes(r.size)}</td><td><button className="btn secondary small" disabled={!admin} onClick={()=>navigate('/restore')}>Restore</button></td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Loading backups...':'No matching backups reported.'}</p>}
 <div className="vm-pagination"><small>Showing {filtered.length?actual*size+1:0}–{Math.min((actual+1)*size,filtered.length)} of {filtered.length}</small><button className="btn secondary small" disabled={!actual} onClick={()=>setPage(actual-1)}>Previous</button><span>{actual+1}/{pages}</span><button className="btn secondary small" disabled={actual>=pages-1} onClick={()=>setPage(actual+1)}>Next</button><select aria-label="Backups per page" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,25,50].map(n=><option key={n} value={n}>{n} / page</option>)}</select></div></Card>
 <div className="backup-side"><Card><h3>Backup Storage</h3>{storageData.length?<><ResponsiveContainer width="100%" height={170}><PieChart><Pie data={storageData} dataKey="value" innerRadius={45} outerRadius={70}>{storageData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any)=>bytes(v)}/></PieChart></ResponsiveContainer><div className="task-legend">{storageData.map((s:any,i)=><span key={s.name}><i style={{background:colors[i%colors.length]}}/>{s.name}<b>{bytes(s.value)}</b></span>)}</div></>:<p className="muted">No archive sizes reported.</p>}<small className="muted">Shared archives deduplicated when storage metadata identifies them.</small></Card><Card><div className="vm-toolbar"><h3>Recent Backup Activity</h3><button className="btn secondary small" onClick={onTasks}>View All</button></div>{backupTasks.slice(0,5).map((t:any)=><button className="backup-activity" key={t.upid} onClick={onTasks}><ShieldCheck size={18}/><span><b>{t.node} · Guest {t.id||'selection'}</b><small>{t.status||'Running'} · {new Date(t.starttime*1000).toLocaleString()}</small></span></button>)}{!backupTasks.length&&<p className="muted">No backup tasks reported in this period.</p>}</Card></div></div>
 <div className="backup-bottom"><Card><h3>Backup Schedules</h3><strong className="stat-value">{live.data?jobs.filter((j:any)=>j.enabled!==0&&j.enabled!==false).length:'Unknown'}</strong><p className="muted">Enabled Proxmox jobs</p><button className="btn secondary" onClick={()=>navigate('/schedules')}>Manage Schedules</button><button className="btn primary" disabled={!admin} onClick={()=>{setError('');setModal('schedule');}}>Add Schedule</button></Card><Card><h3>Retention Policies</h3><p className="muted">{jobs.filter((j:any)=>j['prune-backups']).length} jobs report retention rules.</p><button className="btn secondary" onClick={()=>navigate('/retention')}>Configure Policy</button></Card><Card><h3>Backup Targets</h3>{targets.map((r:any)=><div className="backup-target" key={r.id}><b>{r.name}</b><small>{r.status||'Unknown'} · {bytes(r.available)} available</small></div>)}{!targets.length&&<p className="muted">No backup targets reported.</p>}<button className="btn secondary" onClick={onStorage}>Manage Targets</button></Card><Card><h3>Quick Actions</h3><div className="backup-quick"><button className="btn secondary" disabled={!operator} onClick={()=>setModal('run')}><Play size={17}/> Run Backup Now</button><button className="btn secondary" disabled={!admin} onClick={()=>navigate('/restore')}><RotateCcw size={17}/> Restore Backup</button><button className="btn secondary" onClick={()=>{setView('archives');setStatus('all');}}>Browse Archives</button><button className="btn secondary" onClick={onTasks}>Inspect Backup Logs</button></div></Card></div>
 <Modal open={!!modal} onClose={()=>setModal(null)} title={modal==='policy'?'Backup Retention Policy':modal==='schedule'?'Create Backup Schedule':'Run Guest Backup'}>{modal==='policy'?<><p>{current?.comment||current?.id}</p><pre>{current?.['prune-backups']||'No retention rule reported for this job.'}</pre><button className="btn primary" disabled={!admin} onClick={()=>navigate('/retention')}>Edit Policy</button></>:<form onSubmit={submit}>{error&&<p className="error" role="alert">{error}</p>}<div className="form-grid">{modal==='schedule'&&<label>Name<input name="name" required/></label>}<label>Node<select name="node" required>{(guests.data?.nodes||[]).map((n:any)=><option key={n.name} value={n.name}>{n.name}</option>)}</select></label><label>{modal==='schedule'?'Guest IDs (comma separated)':'Guest ID'}<input name="vmid" required placeholder={allGuests.map((g:any)=>g.id).slice(0,4).join(', ')}/></label><label>Backup storage<select name="storage" required>{Array.from(new Set(targets.map((r:any)=>r.name))).map((n:any)=><option key={n}>{n}</option>)}</select></label>{modal==='schedule'&&<><label>Proxmox calendar schedule<input name="schedule" required placeholder="daily or 02:00"/></label><label>Retention rule (optional)<input name="retention" placeholder="keep-last=7,keep-weekly=4"/></label></>}</div><p className="muted">The task runs in Proxmox. Completion and errors appear in Tasks &amp; Logs.</p><button className="btn primary" disabled={busy||!targets.length}>{busy?'Submitting...':'Submit'}</button></form>}</Modal>
 </section>;
}
