import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Camera,Database,HardDrive,Clock,Calendar,RefreshCw,Plus} from 'lucide-react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip} from 'recharts';
import {useApi} from '../hooks';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const colors=['#168aff','#00cc8d','#ffb329','#8854ef','#ed427b','#16bcc9'];
const bytes=(v:any)=>v==null?'Not reported':v>=1024**4?`${(v/1024**4).toFixed(1)} TiB`:v>=1024**3?`${(v/1024**3).toFixed(1)} GiB`:v>=1024**2?`${(v/1024**2).toFixed(1)} MiB`:v>=1024?`${(v/1024).toFixed(1)} KiB`:`${v} B`;
const date=(v:any)=>v?new Date(v).toLocaleString():'Not reported';
export default function StorageSnapshots({onTab}:{onTab:(t:string)=>void}){
 const live=useApi<any>('/storage/snapshots',null),session=useApi<any>('/auth/me',null),d=live.data,rows=d?.resources||[],targets=d?.targets||[],schedules=d?.schedules||[];
 const admin=['owner','admin'].includes(session.data?.user?.role),operator=admin||session.data?.user?.role==='operator';
 const [search,setSearch]=useState(''),[target,setTarget]=useState('all'),[type,setType]=useState('all'),[selected,setSelected]=useState(''),[page,setPage]=useState(0),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const filtered=rows.filter((r:any)=>(target==='all'||r.targetId===target)&&(type==='all'||r.type===type)&&`${r.name} ${r.dataset} ${r.created||''}`.toLowerCase().includes(search.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/8)),active=Math.min(page,pages-1),shown=filtered.slice(active*8,active*8+8),current=rows.find((r:any)=>r.id===selected)||filtered[0];
 const measured=rows.filter((r:any)=>r.size!=null),total=measured.reduce((n:number,r:any)=>n+r.size,0),oldest=rows.filter((r:any)=>r.created).sort((a:any,b:any)=>a.created.localeCompare(b.created))[0];
 const groups:any[]=Object.values(rows.reduce((a:any,r:any)=>{const g=a[r.targetId]||(a[r.targetId]={name:r.dataset,count:0,size:0});g.count++;g.size+=r.size||0;return a},{}));
 const [browse,setBrowse]=useState<any>(null);
 const browseFiles=async()=>{setModal('Browse Files');setBrowse(null);setBusy(true);try{setBrowse(await api('/storage/snapshots/browse?id='+encodeURIComponent(current.resourceId)))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const refresh=async()=>{setBusy(true);try{live.setData(await api('/storage/snapshots'));setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const run=async(path:string,method:string,body:any)=>{setBusy(true);setError('');try{const result=await confirmedApi(path,{method,body:JSON.stringify(body)});setMessage(result.message||'Operation completed.');setModal('');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const operation=(op:string)=>current.provider==='proxmox'?run(`/storage/snapshots/guest/${op}`,'POST',{node:current.node,kind:current.kind,vmid:current.vmid,name:current.name}):run(`/truenas/snapshot/${encodeURIComponent(current.resourceId)}${op==='rollback'?'/rollback':''}`,op==='delete'?'DELETE':'POST',{});
 const submit=(e:any)=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));if(modal==='Clone')return run('/truenas/dataset/clone','POST',{snapshot:current.resourceId,name:f.name});const t=targets.find((r:any)=>r.id===f.target);if(!t)return;return modal==='Schedule Snapshot'?run('/truenas/schedule','POST',{dataset:t.resourceId,hour:f.hour,minute:f.minute,lifetime:f.lifetime}):t.provider==='truenas'?run('/truenas/snapshot','POST',{dataset:t.resourceId,name:f.name}):run('/storage/snapshots/guest/create','POST',{...t,name:f.name});};
 return <section className="storage-overview storage-datasets storage-snapshots"><div className="page-header"><div><small className="muted">Storage / Snapshots</small><h1>Snapshots</h1><p className="muted">Manage TrueNAS dataset snapshots and Proxmox VM and container snapshots.</p></div><div className="header-actions"><button className="btn secondary" disabled={busy||live.loading} onClick={refresh}><RefreshCw size={14}/>Refresh</button>{admin&&<button className="btn secondary" disabled={!targets.some((t:any)=>t.provider==='truenas')||busy} onClick={()=>setModal('Schedule Snapshot')}><Calendar size={14}/>Schedule Snapshot</button>}{operator&&<button className="btn primary" disabled={!targets.length||busy} onClick={()=>setModal('Create Snapshot')}><Plus size={14}/>Create Snapshot</button>}</div></div>
 <div className="dataset-stat-grid">{[[Camera,'Total Snapshots',d?rows.length:'--','Reported snapshots'],[HardDrive,'Measured Used Space',measured.length?bytes(total):'Not reported',`${measured.length} of ${rows.length} measured`],[Database,'Sources with Snapshots',groups.length,'Datasets, VMs and CTs'],[Clock,'Oldest Snapshot',oldest?new Date(oldest.created).toLocaleDateString():'Not reported','Reported creation date'],[Calendar,'Enabled Schedules',schedules.filter((s:any)=>s.enabled).length,'TrueNAS periodic tasks']].map(([Icon,label,value,sub]:any)=><Card key={label}><div><small className="muted">{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div><span><Icon size={23}/></span></Card>)}</div>
 <div className="tabs" role="tablist">{['Storage Pools','Disks','Datasets / Volumes','Snapshots','Docker Volumes','Performance','Settings'].map(t=><button role="tab" aria-selected={t==='Snapshots'} className={t==='Snapshots'?'active':''} key={t} onClick={()=>onTab(t)}>{t}</button>)}</div>
 {(error||live.error)&&<p className="error" role="alert">{error||live.error}</p>}{message&&<p className="storage-feedback" role="status">{message}<button className="btn ghost small" onClick={()=>setMessage('')}>Dismiss</button></p>}
 <div className="dataset-layout"><Card className="storage-pool-table"><div className="storage-overview-toolbar"><h3>Snapshots</h3><input aria-label="Search snapshots" placeholder="Search name, source or date..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Snapshot source" value={target} onChange={e=>{setTarget(e.target.value);setPage(0)}}><option value="all">All Sources</option>{targets.map((t:any)=><option value={t.id} key={t.id}>{t.node?`${t.node} / `:''}{t.name}</option>)}</select><select aria-label="Snapshot type" value={type} onChange={e=>{setType(e.target.value);setPage(0)}}><option value="all">All Types</option>{['VM','CT','ZFS'].map(t=><option key={t}>{t}</option>)}</select></div><div className="table-wrap"><table><thead><tr>{['Name','Dataset / Guest','Type','Created','Used Space','Status','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((r:any)=><tr key={r.id} className={r.id===current?.id?'selected':''}><td><button className="storage-resource-name" onClick={()=>setSelected(r.id)}><Camera size={14}/>{r.name}</button></td><td>{r.dataset}</td><td>{r.type}</td><td>{date(r.created)}</td><td>{bytes(r.size)}</td><td><Badge tone="blue">{r.status}</Badge></td><td><button className="btn secondary small" onClick={()=>setSelected(r.id)}>Inspect</button></td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Loading snapshots...':'No matching snapshots reported. Create a snapshot or check provider limitations below.'}</p>}<div className="storage-overview-pagination"><small>Showing {filtered.length?active*8+1:0} to {Math.min((active+1)*8,filtered.length)} of {filtered.length}</small><button className="btn secondary small" disabled={!active} onClick={()=>setPage(active-1)}>Previous</button><span>{active+1}/{pages}</span><button className="btn secondary small" disabled={active===pages-1} onClick={()=>setPage(active+1)}>Next</button></div></Card>
 <Card><h3>Snapshot Details</h3>{current?<><div className="dataset-title"><Camera size={30}/><h3>{current.name}</h3></div><dl className="dataset-details">{[['Source',current.dataset],['Provider',current.provider],['Type',current.type],['Created',date(current.created)],['Used Space',bytes(current.size)],['Referenced Space',bytes(current.referenced)],['Status',current.status],['Parent',current.parent],['Description',current.description],['GUID',current.guid]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Not reported'}</dd></div>)}</dl>{admin&&<div className="header-actions"><button className="btn primary small" disabled={busy} onClick={()=>operation('rollback')}>Restore</button>{current.provider==='truenas'&&<button className="btn secondary small" disabled={busy} onClick={()=>setModal('Clone')}>Clone</button>}<button className="btn danger small" disabled={busy} onClick={()=>operation('delete')}>Delete</button></div>}<p className="muted">Restore rolls back the source contents. Provider restrictions apply; deletion does not force removal of dependent clones.</p>{current.provider==='truenas'&&<button className="btn secondary small" disabled={busy} onClick={browseFiles}>Browse Files</button>}<Link className="btn secondary small" to="/audit">View Action History</Link></>:<p className="muted">Select a snapshot to inspect it.</p>}</Card></div>
 <div className="dataset-bottom"><Card><h3>Snapshots by Source</h3><div className="dataset-usage-list">{groups.sort((a,b)=>b.count-a.count).slice(0,8).map(g=><div className="snapshot-source" key={g.name}><span>{g.name}</span><meter min="0" max={Math.max(...groups.map(x=>x.count))} value={g.count}/><b>{g.count}</b></div>)}</div>{!groups.length&&<p className="muted">No snapshot counts reported.</p>}</Card><Card><h3>Measured Snapshot Usage</h3>{total>0?<ResponsiveContainer width="100%" height={180}><PieChart><Pie data={groups.filter(g=>g.size>0)} dataKey="size" nameKey="name" innerRadius={48} outerRadius={75} isAnimationActive={false}>{groups.filter(g=>g.size>0).map((g,i)=><Cell key={g.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any)=>bytes(v)}/></PieChart></ResponsiveContainer>:<p className="muted">No snapshot space measurements reported.</p>}<small className="muted">Proxmox snapshot disk usage is not supplied by its snapshot list.</small></Card><Card><div className="widget-title"><h3>Snapshot Schedules</h3><Link to="/schedules">View All</Link></div>{schedules.slice(0,4).map((s:any)=><div className="storage-task-item" key={s.id}><b>{s.dataset}</b><small>{s.schedule?.hour}:{s.schedule?.minute} / {s.lifetime_value} {s.lifetime_unit}</small><Badge tone={s.enabled?'green':'gray'}>{s.enabled?'Enabled':'Disabled'}</Badge>{admin&&<button className="btn secondary small" disabled={busy} onClick={()=>run(`/truenas/schedule/${s.id}/toggle`,'POST',{})}>{s.enabled?'Disable':'Enable'}</button>}</div>)}{!schedules.length&&<p className="muted">No TrueNAS periodic snapshot tasks reported.</p>}<Link to="/proxmox">View Proxmox tasks</Link></Card></div>
 {!!d?.errors?.length&&<Card><details><summary>Provider limitations ({d.errors.length})</summary>{d.errors.map((e:string)=><p className="muted" key={e}>{e}</p>)}</details></Card>}<small className="muted">Last measurement: {date(d?.sampledAt)}</small>
 <Modal open={!!modal} title={modal} onClose={()=>!busy&&setModal('')}>{modal==='Browse Files'?<><p className="muted">{browse?.path}</p>{busy&&<p>Loading...</p>}<div className="table-wrap dataset-browse"><table><thead><tr><th>Name</th><th>Type</th><th>Size</th></tr></thead><tbody>{browse?.entries?.map((r:any)=><tr key={r.path}><td>{r.name}</td><td>{r.type}</td><td>{bytes(r.size)}</td></tr>)}</tbody></table></div>{error&&<p className="error" role="alert">{error}</p>}<small className="muted">Read-only snapshot root listing, up to 200 entries. ZFS volumes have no browsable filesystem.</small></>:<form className="form-grid" onSubmit={submit}>{modal!=='Clone'&&<label>Source<select name="target" required>{targets.filter((t:any)=>modal!=='Schedule Snapshot'||t.provider==='truenas').map((t:any)=><option value={t.id} key={t.id}>{t.node?`${t.node} / `:''}{t.name}</option>)}</select></label>}{modal==='Schedule Snapshot'?<><label>Hour (TrueNAS server time)<input name="hour" type="number" min="0" max="23" defaultValue="2" required/></label><label>Minute<input name="minute" type="number" min="0" max="59" defaultValue="0" required/></label><label>Retention days<input name="lifetime" type="number" min="1" max="3650" defaultValue="7" required/></label><p className="muted">Creates a daily, non-recursive TrueNAS snapshot task.</p></>:<label>{modal==='Clone'?'New pool/dataset path':'Snapshot name'}<input name="name" required placeholder={modal==='Clone'?'tank/restored-data':'before-update'}/></label>}{error&&<p role="alert" className="error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Working...':'Submit'}</button></form>}</Modal>
 </section>;
}
