import {useState} from 'react';
import {HardDrive,Database,Shield,Activity,RefreshCw,Download,Search} from 'lucide-react';
import {useApi} from '../hooks';
import {api} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const size=(n:any)=>typeof n==='number'&&Number.isFinite(n)?n>=1024**4?`${(n/1024**4).toFixed(1)} TiB`:`${(n/1024**3).toFixed(1)} GiB`:'Not reported';
const knownHealth=(v:any)=>!!v&&!/^(unknown|n\/a)$/i.test(v);
const healthy=(v:any)=>/^(PASSED|OK|HEALTHY)$/i.test(v||'');
const tabs=['Storage Pools','Disks','Datasets / Volumes','Snapshots','Shares','Docker Volumes','Performance','Settings'];
export default function StorageDisks({onTab}:{onTab:(tab:string)=>void}){
 const live=useApi<any>('/storage/disks',null),[search,setSearch]=useState(''),[type,setType]=useState('all'),[host,setHost]=useState('all'),[selected,setSelected]=useState(''),[page,setPage]=useState(0),[report,setReport]=useState<any>(null),[reportDisk,setReportDisk]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[full,setFull]=useState(false);
 const disks=live.data?.resources||[],disk=disks.find((d:any)=>d.id===selected)||disks[0],filtered=disks.filter((d:any)=>(type==='all'||d.type===type)&&(host==='all'||(d.node||d.provider)===host)&&`${d.name} ${d.model||''} ${d.serial||''} ${d.node||''}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/8)),active=Math.min(page,pages-1),shown=filtered.slice(active*8,active*8+8);
 const measured=disks.filter((d:any)=>typeof d.size==='number'&&d.size>0),capacity=measured.reduce((n:number,d:any)=>n+d.size,0),known=disks.filter((d:any)=>knownHealth(d.health)),good=known.filter((d:any)=>healthy(d.health)),currentReport=reportDisk===disk?.id?report:null;
 const choose=(d:any)=>{setSelected(d.id);setError('')};
 const smart=async()=>{if(!disk||disk.provider!=='proxmox')return;const id=disk.id;setBusy(true);setError('');try{setReport(await api(`/storage/disks/${encodeURIComponent(disk.node)}/smart?disk=${encodeURIComponent(disk.name)}`));setReportDisk(id);}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const exportReport=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(currentReport||disk,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='homecloud-disk-report.json';a.click();URL.revokeObjectURL(url)};
 return <section className="storage-overview storage-disks"><div className="page-header"><div><small className="muted">Storage / Disks</small><h1>Disks</h1><p className="muted">Physical disks reported by your Proxmox nodes and TrueNAS server.</p></div><div className="header-actions"><button className="btn secondary" disabled={live.loading} onClick={live.refresh}><RefreshCw size={14}/>Scan Disks</button><button className="btn primary" disabled={busy||disk?.provider!=='proxmox'} onClick={smart}><Activity size={14}/>{busy?'Reading...':'Read S.M.A.R.T.'}</button></div></div>
 <div className="disk-stat-grid">{[[HardDrive,'Total Disks',live.data?disks.length:'--',`${good.length} passed / ${known.length} health readings`],[Database,'Reported Capacity',measured.length?size(capacity):'Not reported',`${measured.length} disks with size readings`],[Shield,'Health Warnings',known.length-good.length,'Reported failing or warning statuses'],[Activity,'Hosts',new Set(disks.map((d:any)=>d.node||d.provider)).size,'Hosts with disk inventory']].map(([Icon,label,value,sub]:any)=><Card key={label}><div><small className="muted">{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div><span><Icon size={24}/></span></Card>)}</div>
 <div className="tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={t==='Disks'} className={t==='Disks'?'active':''} key={t} onClick={()=>onTab(t)}>{t}</button>)}</div>
 {(live.error||error)&&<p role="alert" className="error">{live.error||error}</p>}
 <div className="disk-layout"><Card className="storage-pool-table"><div className="storage-overview-toolbar"><h3>Disk List</h3><label><Search size={14}/><input aria-label="Search disks" placeholder="Search name, model, serial..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><select aria-label="Disk type" value={type} onChange={e=>{setType(e.target.value);setPage(0)}}><option value="all">All Types</option>{[...new Set(disks.map((d:any)=>d.type).filter(Boolean))].map((t:any)=><option key={t}>{t}</option>)}</select><select aria-label="Disk host" value={host} onChange={e=>{setHost(e.target.value);setPage(0)}}><option value="all">All Hosts</option>{[...new Set(disks.map((d:any)=>d.node||d.provider))].map((t:any)=><option key={t}>{t}</option>)}</select></div><div className="table-wrap"><table><thead><tr>{['Name / Host','Model','Type','Size','Assignment','Health','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((d:any)=><tr key={d.id} className={d.id===disk?.id?'selected':''}><td><button className="storage-resource-name" onClick={()=>choose(d)}><HardDrive size={14}/> {d.name}</button><small className="docker-image">{d.node||d.provider}</small></td><td>{d.model||'Not reported'}</td><td>{d.type||'Unknown'}</td><td>{size(d.size)}</td><td>{d.assignment||'Not reported'}</td><td><Badge tone={!knownHealth(d.health)?'gray':healthy(d.health)?'green':'yellow'}>{d.health||'Unknown'}</Badge></td><td><button className="btn secondary small" onClick={()=>choose(d)}>Inspect</button></td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Scanning connected hosts...':'No disks reported. Check the connector permissions and host errors below.'}</p>}<div className="storage-overview-pagination"><small>Showing {filtered.length?active*8+1:0} to {Math.min((active+1)*8,filtered.length)} of {filtered.length} disks</small><button className="btn secondary small" disabled={!active} onClick={()=>setPage(active-1)}>Previous</button><span>{active+1}/{pages}</span><button className="btn secondary small" disabled={active===pages-1} onClick={()=>setPage(active+1)}>Next</button></div></Card>
 <Card><h3>Disk Details</h3>{disk?<><div className="disk-title"><HardDrive size={35}/><div><h3>{disk.name}</h3><small className="muted">{disk.model||'Model not reported'}</small></div></div><dl className="disk-details">{[['Host',disk.node||disk.provider],['Type',disk.type],['Size',size(disk.size)],['Serial',disk.serial],['Assignment',disk.assignment],['Health',currentReport?.report?.health||disk.health],['Wear reading',disk.wearout==null?null:String(disk.wearout)],['GPT',disk.gpt==null?null:disk.gpt?'Yes':'No']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not reported'}</dd></div>)}</dl><div className="header-actions"><button className="btn secondary small" disabled={busy||disk.provider!=='proxmox'} onClick={smart}>Refresh S.M.A.R.T.</button><button className="btn secondary small" onClick={()=>setFull(true)}>View Details</button></div>{disk.provider!=='proxmox'&&<p className="muted">This TrueNAS inventory reports disk identity and size. S.M.A.R.T. readings are not supplied by this connector.</p>}</>:<p className="muted">Select a detected disk.</p>}</Card></div>
 <div className="disk-bottom"><Card><h3>Disk Capacity</h3><div className="disk-capacity-list">{measured.map((d:any)=><button key={d.id} onClick={()=>choose(d)}><span>{d.name}<small className="docker-image">{d.node||d.provider}</small></span><i><b style={{width:`${d.size/Math.max(...measured.map((r:any)=>r.size))*100}%`}}/></i><b>{size(d.size)}</b></button>)}</div><small className="muted">Physical capacity; allocated storage and free space are shown in Storage Pools.</small></Card><Card><div className="widget-title"><h3>S.M.A.R.T. Status</h3><button className="btn secondary small" disabled={!disk} onClick={exportReport}><Download size={13}/>Export</button></div>{currentReport?<><Badge tone={healthy(currentReport.report.health)?'green':'gray'}>{currentReport.report.health||'Status not reported'}</Badge><small className="docker-image">Last read: {new Date(currentReport.sampledAt).toLocaleString()}</small><div className="table-wrap disk-smart"><table><thead><tr><th>Attribute</th><th>Raw</th><th>Threshold</th><th>Failing</th></tr></thead><tbody>{(currentReport.report.attributes||[]).map((a:any)=><tr key={a.id||a.name}><td>{a.name}</td><td>{a.raw??a.value}</td><td>{a.threshold??'--'}</td><td>{a.fail||'--'}</td></tr>)}</tbody></table>{currentReport.report.text&&<pre>{currentReport.report.text}</pre>}</div><button className="btn secondary small" onClick={()=>setFull(true)}>View Full S.M.A.R.T. Data</button></>:<p className="muted">Select a Proxmox disk and read its S.M.A.R.T. data. Unreported health is unknown.</p>}</Card></div>
 {!!live.data?.errors?.length&&<Card><details open><summary>Host discovery limitations</summary>{live.data.errors.map((e:string)=><p className="muted" key={e}>{e}</p>)}</details></Card>}<small className="muted">Last scan: {live.data?.sampledAt?new Date(live.data.sampledAt).toLocaleString():'Not available'}</small><Modal open={full} title="Disk Report" onClose={()=>setFull(false)}><pre className="disk-report">{JSON.stringify({disk,smart:currentReport},null,2)}</pre></Modal></section>;
}
