import {useState} from 'react';
import {Database,HardDrive,Folder,Camera,Plus,RefreshCw,Search,Copy,Shield,Download} from 'lucide-react';
import {ResponsiveContainer,PieChart,Pie,Cell,Tooltip} from 'recharts';
import {useApi} from '../hooks';
import {api,confirmedApi} from '../api';
import {Card,Badge,Modal} from '../components/UI';
const bytes=(n:any)=>typeof n==='number'&&Number.isFinite(n)?n>=1024**4?`${(n/1024**4).toFixed(1)} TiB`:n>=1024**3?`${(n/1024**3).toFixed(1)} GiB`:n>=1024**2?`${(n/1024**2).toFixed(1)} MiB`:n>=1024?`${(n/1024).toFixed(1)} KiB`:`${n} B`:'Not reported';
const colors=['#3387ff','#11c98e','#ffac32','#9254ed','#16b9c8','#e25d91'];
const tabs=['Storage Pools','Disks','Datasets / Volumes','Snapshots','Docker Volumes','Performance','Settings'];
export default function StorageDatasets({onTab}:{onTab:(t:string)=>void}){
 const live=useApi<any>('/storage/datasets',null),session=useApi<any>('/auth/me',null);
 const [search,setSearch]=useState(''),[pool,setPool]=useState('all'),[type,setType]=useState('all'),[selected,setSelected]=useState(''),[page,setPage]=useState(0),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[extra,setExtra]=useState<any>(null);
 const d=live.data,rows=[...(d?.resources||[])].sort((a:any,b:any)=>Number(b.provider==='truenas')-Number(a.provider==='truenas')||a.name.localeCompare(b.name)),summary=d?.summary||{},admin=['owner','admin'].includes(session.data?.user?.role),operator=admin||session.data?.user?.role==='operator',resource=rows.find((r:any)=>r.id===selected)||rows[0],tn=resource?.provider==='truenas',filesystem=tn&&resource.type==='Dataset',snapshots=(d?.snapshots||[]).filter((s:any)=>s.dataset===resource?.resourceId);
 const filtered=rows.filter((r:any)=>(pool==='all'||`${r.provider}:${r.pool}`===pool)&&(type==='all'||r.type===type)&&`${r.name} ${r.node||''} ${r.mountpoint||''}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/8)),active=Math.min(page,pages-1),shown=filtered.slice(active*8,active*8+8);
 const distribution=rows.map((r:any)=>({...r,chartUsed:r.provider==='truenas'?r.usedByDataset??(rows.some((c:any)=>c.provider==='truenas'&&c.name.startsWith(r.name+'/'))?null:r.used):r.used})).filter((r:any)=>typeof r.chartUsed==='number'&&r.chartUsed>0);
 const choose=(r:any)=>{setSelected(r.id);setExtra(null);setError('')};
 const open=(name:string)=>{setModal(name);setError('');setExtra(null)};
 const read=async(kind:string)=>{open(kind);setBusy(true);try{setExtra(await api(`/storage/datasets/${kind==='Browse'?'browse':'permissions'}?dataset=${encodeURIComponent(resource.resourceId)}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const refresh=async()=>{try{setBusy(true);live.setData(await api('/storage/datasets?refresh=1'));setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const submit=async(e:any)=>{e.preventDefault();const f:any=Object.fromEntries(new FormData(e.currentTarget));let path='/truenas/dataset',method='POST',body:any={name:f.name};if(modal==='Set Permissions'){path='/truenas/dataset/permissions';method='PUT';body={dataset:resource.resourceId,mode:f.mode,uid:f.uid,gid:f.gid}}else if(modal==='Create ZFS Volume')body={...body,type:'VOLUME',volsize:Number(f.size)*1024**3,compression:f.compression};else if(modal==='Create Dataset')body={...body,type:'FILESYSTEM',compression:f.compression,...(f.quota?{quota:Number(f.quota)*1024**3}:{})};else if(modal==='Take Snapshot'){path='/truenas/snapshot';body={name:f.name,dataset:resource.resourceId}}else if(modal==='Clone Dataset'){path='/truenas/dataset/clone';body={name:f.name,snapshot:f.snapshot}}setBusy(true);setError('');try{await confirmedApi(path,{method,body:JSON.stringify(body)});setMessage('Operation completed.');setModal('');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const exportResource=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(resource,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='homecloud-storage-resource.json';a.click();URL.revokeObjectURL(url)};
 return <section className="storage-overview storage-datasets"><div className="page-header"><div><small className="muted">Storage / Datasets &amp; Volumes</small><h1>Datasets / Volumes</h1><p className="muted">TrueNAS datasets and ZFS volumes, plus Proxmox VM and container storage volumes.</p></div><div className="header-actions"><button className="btn secondary" disabled={busy||live.loading} onClick={refresh}><RefreshCw size={14}/>Refresh</button>{admin&&<button className="btn primary" disabled={!d?.truenasEnabled} onClick={()=>open('Create Dataset')}><Plus size={14}/>Create Dataset</button>}</div></div>
 <div className="dataset-stat-grid">{[[Database,'Datasets / Volumes',d?rows.length:'--','Reported resources'],[HardDrive,'Pool Capacity',bytes(summary.capacity),'Shared Proxmox pools counted once'],[Database,'Pool Used Space',bytes(summary.used),'Measured online pools'],[HardDrive,'Pool Available',bytes(summary.available),'Provider-reported free space'],[Folder,'Mount Points',rows.filter((r:any)=>r.mountpoint&&r.mountpoint!=='none').length,'Reported dataset paths']].map(([Icon,label,value,sub]:any)=><Card key={label}><div><small className="muted">{label}</small><strong>{value}</strong><small className="muted">{sub}</small></div><span><Icon size={23}/></span></Card>)}</div>
 <div className="tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={t==='Datasets / Volumes'} className={t==='Datasets / Volumes'?'active':''} onClick={()=>onTab(t)} key={t}>{t}</button>)}</div>
 {(live.error||error)&&<p role="alert" className="error">{live.error||error}</p>}{message&&<p role="status" className="storage-feedback">{message}<button className="btn ghost small" onClick={()=>setMessage('')}>Dismiss</button></p>}
 <div className="dataset-layout"><Card className="storage-pool-table"><div className="storage-overview-toolbar"><h3>Datasets / Volumes</h3><label><Search size={14}/><input aria-label="Search datasets or volumes" placeholder="Search name, host or mount point..." value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><select aria-label="Dataset pool" value={pool} onChange={e=>{setPool(e.target.value);setPage(0)}}><option value="all">All Pools</option>{[...new Set(rows.map((r:any)=>`${r.provider}:${r.pool}`))].map((p:any)=><option key={p} value={p}>{p}</option>)}</select><select aria-label="Resource type" value={type} onChange={e=>{setType(e.target.value);setPage(0)}}><option value="all">All Types</option>{[...new Set(rows.map((r:any)=>r.type))].map((t:any)=><option key={t}>{t}</option>)}</select></div><div className="table-wrap"><table><thead><tr>{['Name / Host','Pool','Type','Size / Quota','Used','Available','Mount Point','Status','Actions'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{shown.map((r:any)=><tr key={r.id} className={r.id===resource?.id?'selected':''}><td><button className="storage-resource-name" onClick={()=>choose(r)}><Folder size={14}/> {r.name}</button><small className="docker-image">{r.node||r.provider}{r.shared?' / Shared':''}</small></td><td>{r.pool}</td><td>{r.type}</td><td>{bytes(r.size)}</td><td>{bytes(r.used)}</td><td>{bytes(r.available)}</td><td>{r.mountpoint||'--'}</td><td><Badge tone={r.status==='Mounted'?'green':r.status==='Locked'?'yellow':'gray'}>{r.status}</Badge></td><td><button className="btn secondary small" onClick={()=>choose(r)}>Inspect</button></td></tr>)}</tbody></table></div>{!shown.length&&<p className="muted">{live.loading?'Loading datasets and volumes...':'No matching resources reported. Check the provider limitations below.'}</p>}<div className="storage-overview-pagination"><small>Showing {filtered.length?active*8+1:0} to {Math.min((active+1)*8,filtered.length)} of {filtered.length} resources</small><button className="btn secondary small" disabled={!active} onClick={()=>setPage(active-1)}>Previous</button><span>{active+1}/{pages}</span><button className="btn secondary small" disabled={active===pages-1} onClick={()=>setPage(active+1)}>Next</button></div></Card>
 <Card><h3>Resource Details</h3>{resource?<><div className="dataset-title"><Folder size={32}/><div><h3>{resource.name}</h3><small className="muted">{resource.mountpoint||resource.node||resource.provider}</small></div></div><dl className="dataset-details">{[['Pool',resource.pool],['Type',resource.type],['Size / Quota',bytes(resource.size)],['Used',bytes(resource.used)],['Available',bytes(resource.available)],['Compression',resource.compression],['Deduplication',resource.deduplication],['Mount Point',resource.mountpoint],['Created',resource.created],['VM / CT ID',resource.vmid],['Format',resource.format],['Status',resource.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'Not reported'}</dd></div>)}</dl>{typeof resource.used==='number'&&typeof resource.available==='number'&&resource.used+resource.available>0&&<div className="dataset-used"><i><b style={{width:`${Math.min(100,resource.used/(resource.used+resource.available)*100)}%`}}/></i><small>{Math.round(resource.used/(resource.used+resource.available)*100)}% used of reported used + available</small></div>}<div className="header-actions">{operator&&tn&&<button className="btn secondary small" disabled={busy} onClick={()=>open('Take Snapshot')}><Camera size={13}/>Snapshot</button>}{filesystem&&resource.mountpoint&&<button className="btn secondary small" disabled={busy} onClick={()=>read('Browse')}><Folder size={13}/>Browse</button>}<button className="btn secondary small" onClick={exportResource}><Download size={13}/>Export</button></div>{resource.provider==='proxmox'&&<p className="muted">Proxmox reports allocated volume size. Filesystem usage and mount paths inside guests are not supplied by storage inventory.</p>}</>:<p className="muted">Select a resource to inspect it.</p>}</Card></div>
 <div className="dataset-bottom"><Card><h3>Storage Usage by Resource</h3><div className="dataset-usage-list">{[...rows].filter((r:any)=>r.used>0).sort((a:any,b:any)=>b.used-a.used).slice(0,8).map((r:any)=><button key={r.id} onClick={()=>choose(r)}><span>{r.name}</span><i><b style={{width:`${r.used/Math.max(...rows.map((x:any)=>x.used||0))*100}%`}}/></i><b>{bytes(r.used)}</b></button>)}</div><small className="muted">Dataset readings can include their children; these values are not added together.</small></Card><Card><h3>Measured Usage Distribution</h3>{distribution.length?<><ResponsiveContainer width="100%" height={165}><PieChart><Pie data={distribution} dataKey="chartUsed" nameKey="name" innerRadius={45} outerRadius={69} isAnimationActive={false}>{distribution.map((r:any,i:number)=><Cell key={r.id} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any)=>bytes(v)}/></PieChart></ResponsiveContainer><div className="dataset-legend">{distribution.slice(0,8).map((r:any,i:number)=><button key={r.id} onClick={()=>choose(r)}><i style={{background:colors[i%colors.length]}}/><span>{r.name}</span><b>{bytes(r.chartUsed)}</b></button>)}</div></>:<p className="muted">No separate usage readings reported.</p>}<small className="muted">Uses dataset-owned usage where reported, otherwise leaf dataset usage. Allocated VM disk sizes are excluded.</small></Card><Card><h3>Quick Actions</h3><div className="dataset-quick-actions">{admin&&<><button className="btn secondary" disabled={!d?.truenasEnabled||busy} onClick={()=>open('Create Dataset')}><Plus size={18}/>Create Dataset</button><button className="btn secondary" disabled={!d?.truenasEnabled||busy} onClick={()=>open('Create ZFS Volume')}><Database size={18}/>Create ZFS Volume</button><button className="btn secondary" disabled={!tn||!snapshots.length||busy} onClick={()=>open('Clone Dataset')}><Copy size={18}/>Clone Snapshot</button></>}<button className="btn secondary" onClick={()=>onTab('Snapshots')}><Camera size={18}/>Snapshots</button><button className="btn secondary" disabled={!filesystem||!resource?.mountpoint||busy} onClick={()=>read('Permissions')}><Shield size={18}/>View Permissions</button><button className="btn secondary" disabled={!filesystem||!resource?.mountpoint||busy} onClick={()=>read('Browse')}><Folder size={18}/>Browse Dataset</button></div>{!d?.truenasEnabled&&<p className="muted">Connect TrueNAS to create ZFS datasets and volumes. Proxmox volume entries are available for inspection.</p>}</Card></div>
 {!!d?.errors?.length&&<Card><details open><summary>Provider limitations</summary>{d.errors.map((e:string)=><p className="muted" key={e}>{e}</p>)}</details></Card>}<small className="muted">Last measurement: {d?.sampledAt?new Date(d.sampledAt).toLocaleString():'Not available'}</small>
 <Modal open={!!modal} title={modal} onClose={()=>!busy&&setModal('')}>{['Browse','Permissions'].includes(modal)?<><p className="muted">{resource?.mountpoint}</p>{busy&&<p>Loading...</p>}{modal==='Browse'&&extra&&<div className="table-wrap dataset-browse"><table><thead><tr><th>Name</th><th>Type</th><th>Size</th></tr></thead><tbody>{(extra.entries||[]).map((r:any)=><tr key={r.path}><td>{r.name}</td><td>{r.type}</td><td>{bytes(r.size)}</td></tr>)}</tbody></table>{!extra.entries?.length&&<p className="muted">No entries reported.</p>}</div>}{modal==='Permissions'&&extra&&<><p>Owner UID: {extra.permissions.uid??'Not reported'} / Group GID: {extra.permissions.gid??'Not reported'}</p><pre className="dataset-report">{JSON.stringify(extra.permissions,null,2)}</pre>{admin&&<button className="btn secondary" onClick={()=>open('Set Permissions')}>Set Permissions</button>}</>}{error&&<p role="alert" className="error">{error}</p>}</>:<form className="form-grid" onSubmit={submit}>{modal==='Set Permissions'?<><label>Unix mode (octal)<input name="mode" required pattern="0?[0-7]{3}" placeholder="750"/></label><label>Owner UID (optional)<input name="uid" type="number" min="0"/></label><label>Group GID (optional)<input name="gid" type="number" min="0"/></label><p className="muted">Applies to the dataset root only. Existing extended ACLs are preserved; TrueNAS rejects mode changes that conflict with them.</p></>:<label>{modal==='Take Snapshot'?'Snapshot name':'New pool/dataset path'}<input name="name" required placeholder={modal==='Take Snapshot'?'snapshot-name':'tank/new-dataset'}/></label>}{modal==='Create ZFS Volume'&&<label>Volume size (GiB)<input name="size" type="number" min="1" step="1" required/></label>}{modal==='Create Dataset'&&<label>Quota (GiB, optional)<input name="quota" type="number" min="0" step="1" placeholder="No quota"/></label>}{['Create Dataset','Create ZFS Volume'].includes(modal)&&<label>Compression<select name="compression" defaultValue="LZ4">{['LZ4','ZSTD','OFF','INHERIT'].map(v=><option key={v}>{v}</option>)}</select></label>}{modal==='Clone Dataset'&&<label>Source snapshot<select name="snapshot" required>{snapshots.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{modal==='Take Snapshot'&&<p className="muted">Dataset: {resource?.resourceId}</p>}{error&&<p role="alert" className="error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Working...':'Submit'}</button></form>}</Modal></section>;
}
